== Una Historia Corta de un Largo Viaje de Babilonia a Bet-el

[.chapter-subtitle--blurb]
Una Alegoría de Stephen Crisp

En los días de mi juventud, cuando vivía en mi hogar, en la casa de mi padre,
escuché a muchas personas hablar de la casa de Dios;
y que cualquiera que lograba entrar en ella, gozaba de todo tipo de felicidad,
tanto en este mundo como en ese que ha de venir.
Y un gran deseo se encendió en mí, de entrar en la casa, si eso era posible; sin embargo,
no sabía dónde estaba, ni tampoco lo sabían los que hablaban de ella;
pues sólo habían escuchado las nuevas y reportaban lo que habían oído. También
había algunos libros escritos por hombres que habían estado en esa casa;
los cuales declaraban mucho del gozo y de la felicidad que habían experimentado en ella.
Conseguí estos libros y los leí una y otra vez,
lo cual fortaleció la creencia en la verdad de las nuevas; sin embargo,
de ninguna manera pude saber cuál era el camino correcto.
Pero mis deseos eran tan ardientes, que me sentí dispuesto a dejar la casa de mi padre,
mi tierra y todo lo demás, y a viajar a cualquier parte,
donde mis piernas me pudieran llevar, para poder encontrar esta casa.

Una vez, cuando le decía a un amigo lo que estaba en mi mente sobre este asunto,
él me dijo en seguida,
que había hombres designados en cada lugar para guiar
a los que estaban dispuestos a ir ahí,
y que esa era su ocupación, y que no tenían nada más que hacer.
Cuando escuché esto fui reconfortado, y le pedí, si me amaba,
que me presentara a uno de esos hombres.
Él me dijo que lo haría; y lo hizo.
Cuando fui donde el hombre,
le hice saber el deseo ferviente que tenía por ir a la casa de Dios,
de la cual había escuchado cosas tan excelentes,
y que tenía entendido que él era uno de los designados para
guiar a cualquiera que estuviera dispuesto a ir,
y para persuadir a los que no estaban dispuestos a ir.
En seguida él me respondió,
que ciertamente era su deber guiar a todos lo que estuvieran dispuestos a ir,
y que si me sometía a sus términos y lo seguía,
me llevaría. Entonces le pregunté cuáles eran sus condiciones y me dijo,
que como el camino era largo y lo conduciría lejos de su casa,
yo debía asumir sus costos y pagar algo adicional, con todo lo cual estuve de acuerdo.

Así que emprendimos nuestro viaje temprano en la mañana;
pero antes de que hubiéramos recorrido un día entero de viaje,
vi a mi guía detenerse algunas veces y mirar a su alrededor,
y que a veces sacaba un libro pequeño de su bolsillo y leía un poco para sí mismo;
lo que me hizo comenzar a creer que él no conocía el camino mejor que yo.
Sin embargo, no dije nada;
sino que continué siguiéndolo de esa manera por varios días de viaje;
y entre más nos alejábamos, más perdido estaba mi guía. A veces seguía un poco,
luego miraba a su alrededor y se volvía para otro lado;
y a veces continuaba por un rato y después se devolvía. Así que mis sospechas se incrementaron,
y me encontré en una gran ansiedad de espíritu, pero le hablé muy poco sobre esto.

Pero un día, mientras viajábamos,
conocimos a un hombre que notó mi rostro entristecido y mi cansancio.
Y me habló muy gentilmente: "`Joven, ¿a dónde vas?`"
Y cuando empecé a contarle algo sobre mi viaje, quiso que me sentara sobre el zacate,
en un lugar sombreado, y que le platicara un poco sobre mi viaje; y así lo hicimos,
y le conté cómo me había ido hasta el momento.
Mientras le estaba diciendo mi historia, mi guía se durmió, lo cual no lamenté,
porque de esta manera tuve más libertad para hablar con el hombre.
Y cuando le conté todo, se compadeció de mí y me dijo,
(según cierto conocimiento suyo) que mi guía nunca había estado en la casa,
ni sabía el camino hacia ella, que sólo había adquirido algunas señales del camino,
las cuales había recibido, como yo o cualquier otro hombre las puede recibir; además,
que si yo lo seguía toda mi vida, nunca me acercaría más a ella,
y al final me daría cuenta de que había gastado mi tiempo,
dinero y esfuerzo sin ningún propósito.

Este discurso me asombró tanto, que quedé perplejo y no sabía qué rumbo tomar.
El hombre, al ver la agonía en que me encontraba,
comenzó a consolarme y me dijo que la casa que yo
buscaba estaba mucho más cerca de lo que pensaba,
y que si abandonaba a mi guía y lo seguía a él, pronto me mostraría la casa.
"`Y`", agregó, "`al observar que tú debes asumir los gastos de este hombre,
y que además debes darle dinero,
te aseguro que no es la costumbre de los guías que pertenecen a esta casa de Dios,
tomar dinero para guiar a las personas hasta ahí.
Yo mismo he sido guía de muchos en mi vida,
pero nunca he tomado ni un centavo de ellos por eso.`"

Para entonces, como puedes asumir, oh, cómo fue consolado mi espíritu abatido;
una nueva esperanza surgió,
y con ella la resolución de abandonar a mi guía errante y seguir a este nuevo.

Ante esto, desperté a mi guía y le dije lo que pensaba.
Le pagué lo que habíamos acordado,
y le aconsejé que nunca más tratara a una pobre alma como lo había hecho conmigo:
"`Porque veo,`" le dije, "`que no conoces el camino,
excepto por algunas cosas que has aprendido sobre él en un libro.
Sin embargo, si aprender de un libro hubiera servido para encontrar a esta famosa casa,
no te habría necesitado,
ni habría necesitado a nadie más para que me guiara a ella;
porque aunque son muy pocos los que han escrito de ella con experiencia,
yo los he leído a todos diligentemente.
Pero ahora he conocido a un hombre que, a mi juicio,
tiene más experiencia del camino que tú, y he decidido irme con él;
y si estás dispuesto a confesar con honestidad tu ignorancia e ir con nosotros,
entonces ven y siéntete bienvenido;
un guía servirá a dos viajeros en el camino tan bien como a uno.`"
Más no lo pude persuadir; así que lo dejé, para que tomara su propio camino.

Entonces seguí adelante muy alegre con mi nuevo guía,
quien me entretuvo a lo largo del camino con una buena conversación.
Mientras avanzaba por un camino bastante liso y sin detenerse,
me dijo que en poco tiempo veríamos la casa; lo cual hizo que mi viaje fuera más fácil.
Me dijo además, algunas de las reglas y órdenes de la casa,
sobre las cuales no me sentí para nada desanimado;
puesto que consideraba que Dios era un Dios de orden,
y no dudaba de que hubiera buenas reglas en Su casa,
ante las cuales estaba dispuesto a someterme.
Así, mientras seguíamos viajando, de repente me habló, diciendo: "`Allá está la casa.`"
Esto me alegró mucho; porque pensé que no había gastado mi esfuerzo en vano.
Entre más nos acercábamos a ella, más se incrementaba mi gozo; y cuando la vi,
me complací enormemente contemplándola,
viendo las torres y las torrecillas que había sobre ella,
y las tallas y las pinturas que tan excelentemente la adornaban.
En verdad, había más arte utilizada en su construcción de lo que podía imaginarse.
¡Oh!, pensé, si hay tanta gloria fuera de ella,
sin duda alguna habrá incluso más dentro de ella, de la que pronto seré partícipe.

Mientras contemplaba mi felicidad, y habiendo llegado a unos cien metros de la casa,
debíamos bajar a un valle, lo cual hicimos,
y en el fondo del valle corría un río pequeño. Miré alrededor buscando un puente,
pero no vi ninguno, lo que me extrañó;
pero seguimos hasta que llegamos a la orilla del río,
y entonces le pregunté a mi guía dónde estaba el puente.
"`Verdaderamente,`" me dijo, "`no hay ninguno, pero tenemos que cruzarlo,
y todos los que entran en la casa deben hacerlo.`"

Me encontraba un poco preocupado,
pero me dijo que él ya lo había cruzado y que no había peligro alguno.
Ante esto, comencé a pensar dentro de mí: "`He sufrido todos estos dolores,
¿y me voy a rendir por un asunto tan pequeño como este?
¡Qué no habría estado dispuesto a hacer cuando aún estaba en la casa de mi padre,
con tal de alcanzar el conocimiento de la casa de Dios y una posesión en ella!
Ni el agua, ni siquiera el fuego, me hubieran detenido entonces,
si hubiera tenido una posibilidad tan segura como la que tengo ahora`".

Le dije a mi guía que si él estaba dispuesto a ir delante de mí, yo lo seguiría;
así que él entró y yo detrás de él, pero cuando llegué a la mitad del río,
estaba tan profundo que el agua cubría mi cabeza.
Sin embargo, tuve cuidado de mantener mis pies en el suelo,
y entonces llegué bien al otro lado; y mi guía y yo subimos juntos muy contentos.
Cuando llegamos a la cima de la colina había una llanura amplia,
y en medio de ella estaba la casa.
Así que fuimos rápidamente y nos acercamos a ella;
y vi allí un magnífico porche en el extremo oeste de la casa,
y en la puerta había un portero alto y fuerte,
a quien mi guía le habló y le dijo lo siguiente:
"`Este joven ha tenido por mucho tiempo el deseo de ser recibido en la casa de Dios,
por tanto,
lo he conducido hasta aquí.`" El portero le preguntó por dónde había llegado yo,
y él le contestó: "`Llegó a través del río.`" No recuerdo que me hiciera más preguntas,
pero me dio la bienvenida y me permitió entrar a la casa.
Mi guía entró conmigo, y a través de muchos giros y vueltas me llevó hasta un gran salón.

Mis ojos iban de un lado a otro mientras recorría la casa,
y en el gran salón vi a mucha gente que me daba la bienvenida,
pero nadie conocía la angustia de mi alma;
porque comencé a cuestionarme si no me habían engañado otra vez,
pues encontré que la casa estaba pestilente y sucia en casi todas partes,
y tan llena de arañas y telarañas,
que pensé para mí mismo que nunca había sido barrida
desde el día en que se construyó. Asimismo,
me encontré con algunas cosas que me disgustaron aún más, como escucharán más adelante;
sin embargo, me proporcionaron una buena cama para que descansara si es que podía;
y teniendo poco apetito, después de haber visto cómo se preparaba la comida,
me fui a la cama y me dispuse a dormir como pudiera.
Pero ¡ay!, el sueño se apartó de mí, y mi espíritu estaba grandemente angustiado,
y los pensamientos de mi mente eran muchos y dolorosos.
Algunas veces pensaba en las pinturas que estaban fuera,
y cómo eso no calzaba con la suciedad que había dentro, y que si estaba engañado,
qué curso debía tomar.

Después de pensar larga y tediosamente, logré contentarme con este pensamiento:
tal vez mañana sea mejor.
Así que me quedé dormido por un corto tiempo, pero por la mañana antes de levantarme,
escuché a dos o tres personas discutiendo sobre algunos asuntos,
en donde una culpaba a la otra de fraude; y la otra, en lugar de vindicarse a sí misma,
se puso a criticar e insultar con algo parecido.
Se acaloraron tanto en sus palabras, que una amenazó con sacar a la otra de la casa,
y conducirla de nuevo al río, y nunca más permitirle ingresar a la casa.

Mi corazón estaba a punto de estallar de tristeza;
y en la angustia de mi espíritu me levanté y fui a ellos.
Les dije: "`No creí que me fuera a encontrar con tales hechos,
o a escuchar tal lenguaje en la casa de Dios.
Me temo,`" dije, "`que estoy siendo engañado;
y que he sido traído entre ustedes por una apariencia falsa, porque no veo la gloria,
la paz ni la tranquilidad que esperaba.`"
Así que me marché a otra parte de la casa donde escuché un gran ruido y palabras fuertes.
Cuando me acerqué, entendí que la disputa era por la elección de un oficial;
y dos estaban luchando por lograrlo.
Cada uno de ellos había ganado un grupo de seguidores,
y cada grupo se enfurecía en contra del otro.
Tan pronto como pude tomar la palabra,
les hablé y les dije que ese tipo de hechos se parecían
más a un lugar en el mundo llamado Billinsgate,^
footnote:[Desde el tiempo del dominio Romano hasta principios de los años 1980,
Billingsgate era una pescadería en Londres, Inglaterra,
conocida por el lenguaje crudo y abusivo que se escuchaba a través de sus puestos.]
que a la casa de Dios.
Continué un poco más y escuché a algunas mujeres
riñendo e insistiendo sobre las modas en sus ropas,
y a otras sobre los juguetes de sus hijos.
Todo esto y mucho más de lo que mencionaré, aumentó mi dolor enormemente.

Entonces empecé a anhelar hablar con el guía que me había llevado hasta ahí;
y tras una búsqueda diligente por fin lo encontré,
y comencé a hablar con él de esta manera:
"`¿Adónde me has traído? ¿Y dónde están las reglas y el
orden que me dijiste que había en la casa de Dios?
He leído a menudo sobre la belleza, el orden, la paz y la pureza de la casa de Dios,
pero aquí no encuentro nada de eso, sino lo contrario.
Temo que me hayas traído a la casa equivocada y que me hayas engañado.`"
Así que le describí lo que me había encontrado; ante lo cual me contestó,
que era de esperar que los hombres tuvieran debilidades humanas,
y que los hombres no eran más que hombres.
Él quería convencerme de que estuviera satisfecho, y de que siguiera probando el lugar.
Y en cuanto a las reglas y al orden de los que había hablado,
dijo que tenían que ver principalmente con las comidas, las bebidas,
y las reglas para elegir a los oficiales para gobernar la casa de Dios;
que con el tiempo vería, si me quedaba allí. Y en cuanto a la suciedad de la casa,
confesó que aquellos a quienes se les había encargado
el cuidado de mantener la casa limpia,
no habían sido tan diligentes como deberían haberlo sido;
pero esperaba que después de una amonestación, fueran más cuidadosos.

Ante lo dicho le respondí: "`¡Qué! ¿Hablas de debilidades humanas en la casa de Dios?
Esa queja es normal en el mundo, pero ¿cómo puede ser correcta en la casa de Dios,
en la cual he escuchado, nadie puede entrar,
sino aquellos que son redimidos de la tierra y son lavados de sus contaminaciones?
Porque Dios ha dicho, '`todos los utensilios en Mi casa serán santos`';
y los que moran en la casa de Dios deben ser de corazón puro y limpios de manos.`"
También le dije mucho más de lo que había escuchado
y leído concerniente a la casa de Dios.
Además, le dije con claridad, que había llegado a creer tan firmemente en la paz,
la pureza, la gloria y la belleza de la casa de Dios,
que estaba convencido de que ese lugar no era la casa de Dios.
Y aunque no sabía dónde encontrarla, si no lograba encontrarla mientras viviera,
aun así nunca dejaría de buscarla, porque ella era el ferviente deseo de mi corazón,
y pensaba que nada menos que ella me satisfaría.
"`Mas en cuanto a tu casa aquí,`" le dije,
"`no tengo satisfacción en ella; no es el lugar que busco, así que debo dejarte.`"
Me respondió que lamentaba que yo no estuviera satisfecho allí como lo estaba él,
y que si no podía estarlo, él no me pondría ninguna traba, que por su parte,
me había dirigido hasta donde él conocía y no podía hacer más por mí.

Después de terminar nuestra plática, me levanté y me fui, pero no sabía adónde ir.
Varios de los que estaban en la casa me tiraron cosas de manera despectiva,
pero ninguna me lastimó. Así que deambulé algunas
veces hacia el norte y otras hacia el sur;
o hacia cualquier dirección que se me ocurriera.
Sin embargo, donde quiera que fuera, la angustia de mi alma me seguía;
la cual era más de la que cualquier lengua pueda pronunciar, o lápiz declarar,
o cualquiera pueda creer;
excepto que este relato se encuentre con alguien que haya experimentado la misma tribulación;
el cual la entendería. Así que, no tenía consuelo de noche ni de día,
pero aun así seguí adelante, sin saber si viajaba en la dirección correcta o equivocada,
ni me atreví a preguntarle a nadie, por miedo a ser engañado como lo había sido antes.

Así me adentré en la horrenda soledad de un desierto, donde parecía no haber un camino,
sólo de vez en cuando encontraba algunas huellas de hombres y mujeres,
las cuales eran de alguna forma de consuelo para mí en mi dolor;
pero no sabía si ellos habían salido sin ser devorados por fieras, ni qué camino tomar.
No obstante, viajé en este estado lamentable día a día,
preguntándome qué debía hacer--si perder la esperanza por completo en esa condición,
o si debía buscar otro pueblo o ciudad,
para ver si podía conseguir otra guía. La primera opción me pareció desesperada,
pero también abandoné la última opción, habiendo sido tan engañado anteriormente;
de modo que todas estas reflexiones aumentaron la amargura de mi alma.

Un día, mientras caminaba en la tarde, se levantó una terrible tormenta,
con granizo y truenos, y un gran viento, que duró hasta la noche y durante la noche.
Y como estaba cansado, tanto física como mentalmente, me acosté bajo un gran árbol,
y después de un tiempo, me dormí. Cuando me desperté y volví en mí,
estaba aún muy oscuro; y mirando a mi alrededor,
vi una pequeña luz cerca de mí. Se me ocurrió ir hacia ella y ver de qué se trataba;
y en cuanto iba, la luz iba delante de mí.

Entonces me vino a la mente que había escuchado hablar acerca de luces falsas,
como la __ignis fatuus,__^
footnote:[También llamada linterna de los frailes, o fuego fatuo.
La ignis fatuus es una luz parpadeante y fosforescente que se ve durante la noche,
principalmente sobre terrenos pantanosos.
Se cree que su origen se debe a la combustión espontánea
de gases que se elevan de la materia orgánica descompuesta.
El nombre se usaba para referirse a cualquier guía
engañoso o que desviaría a un viajero de su camino.]
y cosas por el estilo, que llevaría a las personas a salirse de su camino.
Pero luego volví a pensar: ¿Cómo seré llevado fuera de mi camino,
cuando no conozco un camino seguro?
Y mientras estaba sentado dejando que estos pensamientos
que luchaban dentro de mí siguieran su curso,
me fijé y observé que la luz estaba tan cerca de mí como al principio,
como si me hubiera estado esperando.
Esto me impresionó fuertemente y pensé dentro de mí,
que quizás algún espíritu bueno había venido a apiadarse de mí,
para sacarme de esa condición miserable.
Así que surgió la resolución en mi mente de que me iba a levantar e iba a seguirla,
deduciendo en mi interior,
que no podría ser llevado a una condición peor que en la que me encontraba ya.
Por consiguiente, me levanté y la seguí; ella iba a un paso lento y gentil al principio,
y yo mantuve mi ojo pegado a ella.
Pero después,
me di cuenta de que gran parte del equipaje y de las provisiones
que había llevado me pesaban en el camino;
entonces tiré una cosa, y luego otra, de las que pensé que no eran necesarias,
pero seguí guardando un saco de ropa, sin saber si iba a necesitarla.

A medida que avanzaba, con la luz delante de mí, ella me sacó del desierto,
a lo largo de una tierra llana, sin árboles ni habitantes;
parecía como si solamente unos cuantos hubieran pasado por ese camino anteriormente.
La luz se mantuvo en ese camino estrecho, sin girar o dar vuelta,
hasta que llegué al pie de una gran montaña. Me costó mucho ascender,
y subiendo la montaña, comencé a evaluar mi gran saco de ropa y atuendos.
Entonces llegué a la conclusión de que mucho de eso
no sería útil para un viajero como yo,
que no sabía qué tan lejos debía ir, ni si iba a necesitarlos,
si alguna vez lograba lo que buscaba;
ni sabía si las modas se ajustarían con el lugar al que iba.
Por tanto, tiré algunas, y luego otras más,
hasta que no me quedó nada más que lo que llevaba puesto.

De este modo, siguiendo a mi guía, por fin llegué a la cima de la montaña,
donde vi otra más alta.
También vi a un hombre que me preguntó hacia dónde iba.
Le dije que no se lo podía decir muy bien, pero que le podía decir adónde deseaba ir.
Él me preguntó: "`¿Adónde?`"
"`A la casa de Dios`", le respondí. Me dijo que ese era, en efecto, el camino;
pero que pensaba que nunca iba a llegar.
Le pregunté: "`¿Por qué?`" "`Porque,`" dijo, "`en esa montaña hay tantas víboras,
áspides y serpientes, y bestias tan venenosas,
que devoran a muchas personas que van por ese camino.
Por mi parte,`" dijo, "`yo también iba,
pero estaba tan asustado por las serpientes venenosas, que me vi obligado a regresar,
y te recomiendo lo mismo.`"
Le respondí: "`Amigo, he seguido esa luz como mi guía por un buen rato ya,
y me ha dirigido a lo largo de este camino, y veo que no me abandona; mira,
¿la puedes ver ahí delante de mí?`" Él respondió: "`Sí, la veo.`"
"`Bueno,`" dije, "`he escuchado de viajeros, que si un hombre tiene un fuego o una luz,
las bestias venenosas no lo pueden lastimar;
y tengo la intención de agilizar mi paso un poco más,
y mantenerme tan cerca de la luz como pueda.
Ven, acompáñame y aventúrate.`"
Él dijo que era verdad, que él había escuchado que el fuego protegía de las bestias;
pero pensaba que la luz no lo haría. Sin embargo, que por su parte,
no aventuraría su preciosa vida entre esas bestias; y que si yo quería, que lo hiciera.
Me deseó lo mejor y nos separamos.

Entonces me apresuré y me acerqué bastante a la luz, y subí la segunda montaña,
y cuando estaba casi en la cima de ella,
vi muchas guaridas de serpientes y agujeros de víboras,
tanto a la derecha como a la izquierda.
Las bestias venenosas se acercaron a mí y me sisearon,
y comencé a sentir un gran temor y a temblar excesivamente.
Pero muchas veces, cuando estaban a punto de morderme,
la luz se ponía o aparecía entre ellas y yo,
y entonces se asustaban y huían a sus agujeros y guaridas.

¡Oh, cuando percibí esto,
cómo saltó mi corazón de alegría dentro de mí! ¡Mi gozo abundó--mi
temor por las serpientes disminuyó! ¡Mi amor por mi amable y tierna
guía se incrementó--mi valor y mi confianza fueron renovados!
Y comencé a creer que me encontraba en el camino correcto para conseguir mi deseo.
Así que continué manteniendo mi mirada en la luz a través de todo aquello,
sin recibir ningún daño,
hasta que llegué a la cima de la montaña. Entonces vi un valle tan extremadamente grande,
que no podía ver el otro lado de él. Todo parecía ser un terreno baldío;
o lugares de agua, ciénagas y fango por todo el valle,
lo cual comenzó a desanimarme otra vez.
"`Pero,`" pensé, "`¿qué debo hacer?
Todo ha estado bien hasta ahora.
Fui extrañamente liberado de las serpientes; y pase lo que pase,
si esta luz no me abandona, la seguiré, aunque sea a través de fuego y agua.`"

Entonces seguí y bajé la montaña, a un paso suave y apacible,
y vi muchas criaturas crueles por el camino, que me sacaron sus aguijones,
pero ninguna me pudo lastimar.
Y me di cuenta de que entre más cerca me mantenía de la luz,
más lejos se mantenían de mí. Así llegué al pie de la montaña, a un valle grande,
muy verde y placentero por un trecho; pero poco a poco,
la luz se dirigió a un gran terreno bajo y lleno de agua que me pareció muy peligroso;
pero al llegar justo al lado del lugar,
vi un camino pequeño y estrecho que corría por el medio,
lo suficientemente ancho como para que un hombre pudiera caminar por él. La luz me condujo
en ese camino estrecho e iba delante de mí. Mientras mantenía mi ojo fijo en ella,
iba seguro, pero si en algún momento comenzaba a mirar alrededor,
mis pies se deslizaban hacia el fango y hacia los charcos,
y luego tenía muchas dificultades para volver al camino.
Si la luz no me hubiera esperado con tanta ternura y amabilidad,
de cierto la habría perdido de vista y perecido en el camino;
pues algunas veces estaba tan lejos de mí que difícilmente la podía discernir;
y por ende aumentaba mi diligencia y era más cuidadoso con mis pasos,
manteniéndome cerca de ella tanto como podía;
de modo que algunas veces la luz brillaba a mi alrededor,
y yo podía caminar en el resplandor de ella con gran plenitud de espíritu.

Después de un largo rato de caminar por ese camino estrecho,
levanté mis ojos hacia el lado más alejado del bajo y húmedo valle,
y vi que había más allá una montaña muy alta,
y que en la cima de ella había una gran casa.
Apenas la vi fui grandemente consolado,
suponiendo que esa podía ser la casa que yo había buscado por tanto tiempo.

Sin embargo, justo después de esto, me encontré con otro ejercicio difícil:
Percibí que muchos que habían viajado por ese camino estrecho, habían caído en el fango;
algunos a la derecha y otros a la izquierda.
Estos yacían revolcándose llenos de envidia;
algunos tratando de alcanzarme para jalarme a ellos;
otros lanzando fango y tierra sobre mí para desanimarme; otros hablaban muy bien,
con el propósito de arrastrarme a hablar con ellos, para que,
al perder así mi preciado tiempo,
me retrasara tanto que perdiera de vista a mi buena guía.
Pero vi sus designios malignos y fui consciente de ellos.
Así que, al mantenerme en mi camino estrecho hasta que llegué al final del valle fangoso,
encontré suelo firme debajo de mis pies, para mi gran consuelo.

Solo había avanzado un poco, cuando mi guía, la luz, entró en una ruta estrecha,
con grandes arbustos por ambos lados; ante lo cual me alegré,
pensando que ahora no podía equivocarme, y no tenía que tener tanto cuidado.
¡Pero, ay!
De pronto encontré muchas rutas y caminos,
que parecían casi tan rectos delante de mí como el camino por el que había empezado,
que si no hubiera sido por la luz, que iba un poco por delante de mí,
seguramente me habría equivocado muchas veces.
Sin embargo, siguiendo cuidadosamente a mi buen guía,
por fin subí la montaña y vi de nuevo la casa.
Entonces vi a un hombre de ese lugar, bastante lejos de mí, y lo llamé: "`¡Hola amigo!
Amigo, ¿cuál es el nombre de aquella casa grande?`"
Me dijo que el nombre era BET-EL. Entonces recordé que ese era el nombre
que se usaba para la casa de Dios en la tierra de mi padre,
donde había escuchado las noticias de ella,
y donde me había propuesto tan fervientemente a encontrarla.

¡Oh!
Ninguna lengua puede expresar la alegría y el consuelo que sentí
en mi alma--al pensar que ahora después de todos mis viajes,
peligros y decepciones, había encontrado lo que estaba buscando.
Así que continué, viajando con una alegría indecible; y mientras avanzaba,
vi la fachada de la casa: Era muy grande y sólo tenía una torre;
no había ningún trabajo tallado, ni pintura,
ni ningún tipo de diseño que pudiera discernirse;
pero todas las piedras estaban curiosamente unidas de arriba a abajo.
También noté, que todas las piedras del edificio eran transparentes,
algunas más que otras; y no vi ventanas.
Y al acercarme a ella, vi que tenía un gran atrio exterior,
con una puerta bastante grande para entrar,
de modo que un hombre pudiera entrar con una gran carga sobre su espalda.
Así que al llegar, entré; y allí vi a muchas personas que estaban alegres,
y que parecían vivir vidas muy agradables.
Algunos de ellos me dijeron que habían vivido ahí por muchos años,
que estaban muy satisfechos y que no les faltaba nada;
porque había un inmenso árbol que crecía en medio del atrio,
y su fruto era bueno y las hojas también, y daba fruto durante todo el año. Además,
muchos fueron tan amables que me invitaron a sentarme y a comer con ellos;
pero yo me rehusé. También me enseñaron una gran cisterna que habían cavado para ellos,
y recoger el agua de los elementos; asimismo,
habían hecho viviendas cómodas en los costados del atrio exterior para alojarse.

Pero esto no me satisfizo, porque vi a mi amada guía pasar a través de todos ellos,
y entrar por una puerta estrecha al otro lado.
Entonces los dejé y me apresuré hacia la puerta por donde
vi que había entrado mi guía. Intenté entrar por ahí,
pero no pude porque era demasiado estrecha;
esto me entristeció grandemente y no sabía qué hacer.
Mis pensamientos me inquietaban por doquier, y probé todas las formas posibles de entrar,
pero todo fue en vano.
"`¡Oh!`", pensé, "`¿todos mis problemas y esfuerzos han llegado a esto?
¿Seré excluido al final?
¿Qué debo hacer?`"
Mientras me encontraba en un estado de perplejidad interno, creí escuchar una voz,
pero no sabía de dónde venía, la cual dijo: "`Joven,
despójate de todas tus vestiduras viejas, y así podrás entrar.`"
Esto me preocupó aún más, porque me resistía a ir desnudo,
pero finalmente pensé que era mejor entrar desnudo, que no entrar del todo.
Así que comencé a desnudarme,
pensando que unos pocos y despreciables trapos no debían impedirme tan grande gozo.
Entonces, cuando quedé completamente desnudo como en el día en que nací,
intenté entrar y no encontré ninguna dificultad.
Y justo en cuanto entré,
salió a mi encuentro uno y echó sobre mí una vestidura de lino puro,
que llegaba hasta mis pies.
Me llevó a una habitación estrecha y me dijo: "`Descansa aquí durante un rato.`"
Luego, me acosté con tanto gozo y consuelo que es imposible de expresar.
Todo a mi alrededor era tan agradable y mi lugar de descanso era tan deleitoso,
y mi corazón estaba tan satisfecho,
que todo en mí se llenó de canciones de alegría. Pero encontré
que mi deber era estar tranquilo y quieto en mi alegre condición,
que había comenzado a disfrutar.

No había pasado mucho tiempo en esta habitación,
cuando salí a ver la belleza y hermosura de esta casa.
Mientras caminaba por ella, encontré todo muy limpio y brillante,
de modo que estaba encantado de una manera admirable.
También me encontré con algunas personas que me dieron
la bienvenida a la casa de Dios con tanta amabilidad,
que se refrescó mi corazón; y mientras me familiarizaba con ellos,
observaba sus conductas, y sus conversaciones me resultaban sumamente reconfortantes.
No había disputas, ni contiendas, ni palabras orgullosas, ni airadas,
sino que todo se llevaba a cabo con mansedumbre y reverencia,
y con el debido respeto entre unos y otros.
Los jóvenes esperaban las palabras de los ancianos,
y las vírgenes tenían un respeto reverente hacia las ancianas;
y había tal cuidado y unidad universales, que me maravillé enormemente.

Un día, mientras le abría mi corazón a un anciano,
le dije que me admiraba mucho y me maravillaba grandemente,
la unidad universal que había notado, más allá de todo lo que había conocido en mi vida.
Me dijo que debía ser así, y que no podía ser de otra forma,
porque el guía que me había llevado hasta ahí, había sido el guía de todos.
Y además me dijo,
que no podía haber contienda excepto cuando dos espíritus luchaban por dominar;
pero que no era así en esa casa.
Su respuesta fue tan completa y satisfactoria para mí, que no le dije más en ese momento,
sino que seguí observando y admirando el orden de todo,
hasta que mi alma se llenó y sentí que mi copa rebosaba.
Así que mis pasadas angustias y decepciones, tristezas y peligros,
ahora no significaban nada para mí, habiendo encontrado una recompensa cien veces mayor.

Entonces regresé a mi descanso, en una habitación más grande que la anterior,
cantando alabanzas a mi Dios,
y declarando las alabanzas de la casa y de los que moraban ahí. Y después de un momento,
fui llamado de la habitación donde me encontraba,
y me dijeron que no había sido llevado a ese lugar
sólo para disfrutar y deleitarme en él;
sino que había trabajo que hacer, y que debía asumir mi parte,
y ser fiel y diligente en mi empleo.
Ante esto contesté,
que era suficiente haber alcanzado ya mis deseos al ser admitido en ese lugar celestial;
pero si había algún trabajo que hacer, estaba dispuesto a hacerlo, cualquiera que fuera;
pues sería mi más grande alegría hacer cualquier cosa para
el crecimiento del honor de la casa de Dios,
y de aquellos que moraban en ella.
Después, él que habló conmigo me dijo,
que era mi deber enseñarles a los niños hasta donde
yo había llegado a aprender y a conocer,
y en la medida en que yo recibiera de vez en cuando más instrucciones.
Me encontraba un poco maravillado ante esto, conociendo mis debilidades;
pero habiendo meditado un poco en esa parte de la frase,
"`recibiera de vez en cuando más instrucciones,`" tomé con
valentía mi trabajo e hice algunos progresos en él,
con gran temor y reverencia; esperando diariamente esas instrucciones que iba a recibir,
y las cuales recibía de manera abundante.
Entonces el trabajo prosperaba en mi mano, y los niños me amaban,
y yo los amaba completamente, como si fueran mis propios hijos;
y muchos de ellos crecieron hasta llegar a un buen entendimiento,
atendiendo para mi gran satisfacción, sus ocupaciones y órdenes.

Después de haber continuado así por un tiempo,
el que había hablado conmigo llegó y me dijo,
que debía hacerme cargo de una parte de la familia,
y darles su comida a su debido tiempo;
repartiendo la comida de cada uno según su estado y condición,
no alimentando a los hombres fuertes con leche, ni a los bebés con carne.
Y para esa obra, me dio una llave que llevaba al tesoro o almacén;
donde pude ver y admirar que estaba lleno en abundancia con toda clase de alimento,
que nunca se agotarían o gastarían mientras el mundo existiera.
Observé que, independientemente de lo que yo como los otros sacábamos de ahí,
para distribuir diariamente entre los miembros de la familia de Dios,
el almacén permanecía lleno como al principio,
y así continúa hasta este día y para siempre.

Ahora, habiendo permanecido por un largo tiempo en esta habitación celestial,
viene a mi mente permitirles a mis parientes, y a los hijos de mi viejo padre,
a quienes dejé en Babilonia, que sepan de mí;
porque supongo que deben creer que estoy perdido o que fui devorado.
Pero estaría contento si alguno, sí, si todos ellos estuvieran aquí para contemplar,
saborear y sentir lo que siento yo.
Y para que nadie diga que he sido más afortunado que otros,
porque he entendido desde que llegué a esta casa, que la misma Luz que se me apareció,
le aparece a cualquier pobre alma angustiada en todo el mundo;
pero que la razón por la que muy pocas llegan aquí,
es porque temen los riesgos y peligros que están en el camino,
más de lo que aman la Luz que las guiaría a través de ellos; por lo tanto ,
se hacen a un lado, refugiándose en un edificio podrido,
que en un momento u otro caerá sobre sus cabezas y perecerán en las ruinas.

Ahora, si a alguno le interesa saber mi nombre,
háganle saber que tenía un nombre en la tierra de mi padre,
pero que en este viaje largo y tedioso, lo he perdido.
Sin embargo,
desde que llegué aquí tengo un "`nuevo nombre,`"
mas no tengo letras ni caracteres para indicarlo,
que puedan ser escritos o leídos.
Aun así, si alguno viene donde yo estoy, sabrá mi nombre.
Pero para satisfacerlos aún más, diré esto: Nací en Egipto, espiritualmente llamado así;
y mi padre fue a Babilonia y vivió allí,
en el tiempo en que los verdaderos hijos de Israel estaban en cautiverio.
Allí me familiaricé con algunos de la tribu de los Judíos,
en el momento en que se estaban devolviendo a su tierra natal;
y me contaron cosas maravillosas de la gloria de la casa que tenían en Jerusalén,
y que les hubiera gustado que fuera con ellos.
Y entendí que Salomón, junto con muchos miles de carpinteros y albañiles,
la habían construido.
Pero consideré dentro de mí que si Salomón y los
carpinteros y los albañiles la habían construido,
entonces los carpinteros y los albañiles podrían derribarla de nuevo,
en un momento u otro.
Así que no me fui con ellos, sino que busqué la ciudad cuyo constructor es Dios,
y ahora la he encontrado.
¡Aleluya en lo Altísimo.
Gloria, honor, y renombre a su digno Nombre y poder, por todas las edades y generaciones!
Amén.
