== Una Historia Corta de un Largo Viaje desde Babilonia hasta Bet-el

[.chapter-subtitle--blurb]
Una Alegoría por Stephen Crisp

En los días de mi juventud, cuando vivía en mi hogar, en la casa de mi padre,
escuché a muchas personas hablar de la casa de Dios;
y que quienquiera que haya logrado entrar en ella,
gozó de todo tipo de felicidad tanto en este mundo como en ese que ha de venir.
Y un gran deseo se encendió en mí, de entrar en la casa, si fuera posible;
sin embargo no sabía dónde estaba, tampoco lo sabían los que hablaban de ella;
sino que sólo habían escuchado las nuevas,
y reportaban lo que habían oído. También habían algunos libros,
que fueron escritos por hombres que habían estado en esa casa;
esos libros declaraban mucho sobre el gozo y felicidad que tuvieron en esa casa.
Conseguí estos libros y los leí una y otra vez;
lo cual fortalecía mi creencia en la verdad de las nuevas: sin embargo,
de ninguna manera podía saber cuál era el camino correcto.
Pero mis deseos eran tan ardientes, que me vi dispuesto a dejar la casa de mi padre,
mi tierra y todo lo demás, y viajar a cualquier parte,
donde fuera que mis piernas me pudieran llevar, para poder encontrar esta casa.

Y una vez, cuando le decía a un amigo lo que estaba en mi mente sobre este asunto,
él me dijo en seguida,
que habían hombres designados en cada lugar para
guiar a los que estaban dispuestos a ir ahí,
y que esa era su ocupación, y no tenían nada más que hacer.
Cuando escuché esto fui reconfortado, y deseaba, si él me amaba,
que me presentara a uno de esos hombres.
Él me dijo que lo haría; y lo hizo.
Cuando fui donde el hombre,
le hice saber del deseo ferviente que tenía por ir a la casa de Dios,
de la cual había escuchado cosas tan excelentes.
También le dije que tenía entendido que él era uno de los designados
para guiar allí a cualquiera que estuviera dispuesto a ir,
y para persuadir a la gente que no estaba dispuesta a ir.
En seguida él me respondió, y me dijo,
que ciertamente era su deber guiar a todos lo que estuvieran dispuestos a ir;
y si me sometía a sus términos, y lo seguía,
me llevaría allí. Le pregunté cuáles eran sus condiciones.
Dijo que el camino era largo, y lo conduciría lejos de su casa,
por lo que debía asumir sus costos, y pagar algo adicional,
todo con lo cual estuve de acuerdo.

Así que emprendimos nuestro viaje, temprano en la mañana;
pero antes de que tuviéramos un día entero de viaje,
vi a mi guía detenerse algunas veces, y mirar a su alrededor,
y a veces sacaba un libro pequeño de su bolsillo, y leía un poco para sí mismo;
lo que me hizo comenzar a creer que él no conocía el camino mejor que yo.
Sin embargo, no dije nada; sino que lo seguí de esta manera, por varios días de viaje;
y entre más nos alejábamos, más perdido estaba mi guía. A veces seguía un poco,
y luego miraba a su alrededor, y se volvía para otro lado,
y de nuevo continuaba por un tiempo y después se
devolvía. Así que mis sospechas se incrementaban,
y me encontré en una gran ansiedad de espíritu, pero le hablé muy poco sobre esto.

Pero un día, mientras viajábamos,
conocimos a un hombre que notó mi rostro entristecido y mi condición de cansancio.
Y me habló muy gentilmente; "`Hombre joven,`" dijo, "`¿a dónde vas?`"
Y cuando empecé a contarle algo sobre mi viaje, quiso que me sentara sobre el zacate,
en un lugar sombreado, y le platicara un poco sobre mi viaje: y así lo hicimos,
y le conté cómo me había ido hasta el momento.
Mientras le estaba diciendo mi historia, mi guía se durmió, lo cual no lamentaba,
porque de esta manera, tuve más libertad para hablar con el hombre.
Y cuando le había contado todo, se compadeció de mí,
y me dijo (según cierto conocimiento suyo) que mi guía nunca había estado en la casa,
ni sabía el camino hacia ella, sino que solo había adquirido algunas señales del camino,
las cuales había recibido, como yo o cualquier otro hombre las puede recibir; además,
que si yo lo seguía por todos mis días, nunca me acercaría más a ella,
y al final me daría cuenta de que había gastado mi tiempo, dinero,
y trabajo sin ningún propósito.

Este discurso me asombró tanto, que estaba perplejo, y no sabía qué rumbo tomar.
El hombre, al ver la agonía en que me encontraba, comenzó a consolarme,
y me dijo que la casa que yo buscaba estaba mucho más cerca de lo que pensaba;
y si abandonaba a mi guía y lo seguía, pronto me mostraría la casa.
"`Y,`" dijo, "`Soy alguien que pertenece a esa casa,
y he pertenecido a ella por muchos años. Y considerando,`" dijo,
"`que usted debe asumir los gastos de este hombre, y además debe darle dinero,
le aseguro que no es la costumbre de los guías que pertenecen a esta casa de Dios,
tomar dinero para guiar a las personas hasta ahí.
Yo mismo he sido guía de muchos en mi tiempo,
pero nunca tomé ni un centavo de ellos para eso.`"

Para entonces, como usted puede asumir, oh, cómo fue consolado mi espíritu abatido;
una nueva esperanza había surgido, y una resolución para abandonar a mi guía errante,
y seguir a este nuevo.

Ante esto, desperté a mi guía y le dije lo que pensaba.
Le pagué lo que habíamos acordado,
y le aconsejé nunca más tratar a una pobre alma como lo había hecho conmigo:
"`porque veo,`" le dije, "`que no conoce el camino,
excepto por algunas cosas que ha aprendido sobre ello en un libro.
Sin embargo, si aprender de un libro hubiera servido para encontrar a esta famosa casa,
no lo necesitaría a usted, ni a nadie más para que me guiara a ella;
porque aunque son muy pocos los que han escrito de ella con experiencia, no obstante,
los he leído todos diligentemente.
Pero ahora he conocido a un hombre que a mi juicio,
tiene más experiencia del camino que la que usted tiene, y he decidido irme con él;
y si usted está dispuesto a confesar con honestidad su ignorancia, e ir con nosotros,
entonces venga y siéntase bienvenido; un guía servirá a dos viajeros en el camino,
tan bien como a uno.`"
Más no lo pude persuadir; así que lo dejé para que tomara su propio camino a su gusto.

Entonces seguí adelante muy alegre con mi nuevo guía;
quien me entretenía a largo del camino con un buen discurso.
A medida en que avanzaba por un camino bastante liso, y sin detenerse,
me dijo que en poco tiempo veríamos la casa; lo cual hacía que mi viaje fuera más fácil.
Me dijo además algo de las reglas y decretos de la casa,
sobre las cuales no me sentía para nada desanimado;
puesto que consideraba que Dios era un Dios de orden,
y no dudaba de que había buenas reglas en Su casa,
antes las cuales estaba dispuesto a someterme.
Así, mientras estábamos viajando, de repente me habló, diciendo.
"`Ahí está la casa.`"
Me alegré mucho por esto; creyendo ahora que no había gastado mi esfuerzo en vano.
Entre más nos acercábamos a ella, más se incrementaba mi gozo; y cuando la vi,
me complací enormemente contemplándola,
viendo las torres y las torrecillas que habían sobre ella,
y las tallas y las pinturas que tan excelentemente la adornaban; en verdad,
había más arte utilizado en su presentación de lo que se podría imaginar.
¡Oh!
Pensé, si hay tanta gloria fuera de ella,
sin duda alguna habrá incluso más gloria dentro de ella,
de la cual dentro de poco podré participar.

Mientras contemplaba mi felicidad, y habiendo llegado a unos cien metros de la casa,
debíamos bajar a un valle; lo cual hicimos: y en el fondo del valle,
corría un río pequeño. Miré alrededor buscando un puente, pero no pude ver ninguno;
lo que me dejó perplejo; pero seguimos hasta que llegamos a la orilla del río;
entonces le pregunté a mi guía sobre dónde estaba el puente.
"`Verdaderamente,`" me dijo, "`no hay ninguno, pero tenemos que cruzarlo,
y todos los que entran en esa casa deben hacerlo.`"

Me encontraba un poco preocupado, pero él me dijo que él ya lo había cruzado;
y que no había peligro alguno.
Con todo esto, comencé a pensar dentro de mí, he sufrido todos estos dolores,
¿y debo rendirme por un asunto tan pequeño como este?
¿Qué no habría estado dispuesto a hacer cuando aún estaba en la casa de mi padre,
para alcanzar el conocimiento de la casa de Dios, y una posesión en ella?
Ni el agua, ni siquiera el fuego me hubieran detenido entonces,
si tuviera una posibilidad tan segura como la tengo ahora.

Le dije a mi guía que si él estaba dispuesto a ir delante de mí, yo lo seguiría:
así que él fue, y yo detrás de él, pero cuando llegué al medio,
estaba tan profundo que el agua cubrió mi cabeza.
Sin embargo, tuve cuidado de mantener mis pies en el suelo,
y entonces llegué bien al otro lado; y mi guía y yo contentos subimos juntos.
Cuando llegamos a la cima de la colina, había una llanura amplia,
y en medio de ella estaba la casa.
Así que fuimos rápidamente y nos acercamos a ella;
y vi allí un magnífico porche en el extremo oeste de la casa,
y en la puerta había un portero alto y fuerte,
a quién mi guía le habló y le dijo lo siguiente:
--"`Este hombre joven ha tenido por mucho tiempo
el deseo de ser recibido en la casa de Dios;
por tanto, lo he conducido aquí.`" El portero le preguntó por dónde había venido;
y él le contestó, "`Él vino a través del río.`" No recuerdo que me hiciera más preguntas,
pero me dio la bienvenida, y me permitió entrar a la casa.
Mi guía entró conmigo a través de muchos giros y curvas hasta un gran salón.

Mis ojos iban de un lado a otro cuando iba por la casa; y en el gran salón,
ahí vi a mucha gente que me daba la bienvenida,
pero nadie conocía la angustia de mi alma;
porque comencé a cuestionarme si no me habían engañado otra vez:
pues encontré la casa pestilente y sucia, en casi todas las partes,
y tan llena de arañas y telarañas,
que pensé para mí mismo que nunca había sido barrida desde el día en que fue construida.
Asimismo, hubo algunas cosas allí con las que me encontré y que me disgustaron aún más,
como escucharán más adelante; sin embargo,
me proporcionaron una buena cama para que descansara, si fuera posible;
y teniendo poco apetito, después de haber visto cómo se preparaba la comida,
me fui a la cama, y me dispuse a dormir como pudiera.
Pero ¡ay!
El sueño se apartó de mí, y mi espíritu estaba grandemente angustiado,
y eran muchos y dolorosos los pensamientos de mi mente.
Algunas veces pensaba en las pinturas que estaba afuera,
y cómo eso no calzaba con la suciedad que había dentro, y que si estaba engañado,
qué curso debería tomar.

Después de pensar larga y tediosamente, logré contentarme con este pensamiento:
tal vez mañana sea mejor.
Así que me quedé dormido por un corto tiempo, pero en la mañana antes de levantarme,
escuché a dos o tres personas discutiendo sobre algunos asuntos,
en donde uno culpaba al otro de fraude; y el otro, en lugar de vindicarse a sí mismo,
se puso a criticar e insultar con algo parecido.
Se pusieron tan intensos en sus palabras,
que uno amenazó con sacar al otro de las puertas, y conducirlo de nuevo a través del río,
y nunca más permitirle ingresar a la casa.

Mi corazón estaba a punto de estallar de tristeza;
y en la angustia de mi espíritu me levanté y fui a ellos.
Les dije, "`No creía que me iba a encontrar con tales hechos,
o escuchar tal lenguaje en la casa de Dios.
Me temo,`" dije, "`que estoy siendo engañado;
y que he sido traído entre ustedes por una apariencia falsa, porque no veo la gloria,
la paz y la tranquilidad que esperaba.`"
Así que me marché a otra parte de la casa donde escuché un gran ruido y palabras fuertes.
Cuando me acerqué, entendí que la disputa era sobre elegir un oficial;
y dos estaban luchando por lograrlo,
y cada uno de ellos había ganado un grupo de seguidores,
y cada grupo se enfurecía en contra del otro.
Tan pronto como pude tomar la palabra, les hablé y les dije,
que semejantes hechos como estos se parecen más a un lugar en el mundo llamado Billinsgate,^
footnote:[Desde el tiempo del dominio Romano hasta principios de los años 1980,
Billingsgate era una pescadería en Londres, Inglaterra,
conocida por el lenguaje crudo y abusivo que se escuchaba a través de sus puestos.]
que a la casa de Dios.
Continué un poco más adelante;
y escuché ahí a algunas mujeres riñendo e insistiendo sobre las modas en sus ropas,
y otras sobre los juguetes de sus hijos.
Todo esto y mucho más de lo que mencionaré, aumentó mi dolor enormemente.

Ahora anhelaba hablar con el guía que me trajo hasta aquí;
y tras una búsqueda diligente por fin lo encontré, y comencé de esta manera con él:
"`¿A dónde me has traído? ¿Y dónde están las reglas
y el orden que me dijo que habían en la casa de Dios?
He leído a menudo sobre la belleza, el orden, la paz y la pureza de la casa de Dios,
pero aquí no encuentro nada de eso, sino lo contrario.
Temo que me haya traído a la casa equivocada y que me haya engañado.`"
Así que le describí lo que me había encontrado;
ante lo cual me contestó que es de esperarse que los hombres tengan debilidades humanas,
y que los hombres no sean sino hombres.
Él quería convencerme de que estuviera satisfecho, y para que volviera a probar el lugar.
Y en cuanto a las reglas y al orden de los que habló,
dijo que tenían que ver principalmente con las comidas y las bebidas,
y sobre las reglas para elegir los oficiales para gobernar la casa de Dios;
que con el tiempo vería, si me quedaba allí. Y, en cuanto a la suciedad de la casa,
él confesó que aquellos a quienes se les encargó el cuidado de mantener la casa limpia,
no habían sido tan diligentes como deberían haber sido;
pero él esperaba que después de la amonestación, fueran más cuidadosos.

Ante lo dicho, le respondí: "`¡Qué! ¿Habla de debilidades humanas en la casa de Dios?
Esa queja es normal en el mundo,
pero ¿cómo puede ser apta para la casa de Dios en
la cual he escuchado que nadie puede venir,
sino aquellos que son redimidos de la tierra, y son lavados de sus contaminaciones?
Porque Dios ha dicho, todos los utensilios en Mi casa deben ser santos;
y los que moran en la casa de Dios deben ser de corazón puro y limpio de manos.`"
También le dije mucho más de lo que había escuchado
y leído concerniente a la casa de Dios.
Además, le dije con claridad, que había llegado a creer tan firmemente en la paz,
la pureza, la gloria, y la belleza de la casa de Dios,
que estaba convencido de que esto no era nada de ella;
y aunque no sabía dónde encontrarla; si nunca lograra encontrarla mientras viviera,
aún así no me rendiría en buscarla, porque era el ferviente deseo de mi corazón,
y pensaba que nada menos que ella me satisfaría.
"`Más en cuanto a su casa aquí,`" le dije,
"`no tengo ninguna satisfacción en ella; no es el lugar que busco,
así que debo dejarla.`"
Me respondió que lamentaba que yo no estuviera satisfecho allí como lo estaba él;
y que si no podía estarlo, él no pondría ninguna traba sobre mí: por su parte,
me había dirigido hasta donde él sabía y no podía hacer más por mí.

Después de haber terminado nuestra plática, me levanté y me fui, más no sabía dónde ir.
Varios de los que estaban en la casa, me tiraron cosas de manera despectiva,
pero ninguno me lastimó. Así que deambulé algunas
veces hacia el Norte y otras hacia el Sur;
o cualquier dirección que se me ocurría. Sin embargo, donde sea que fuera,
la angustia de mi alma me seguía;
la cual era más que lo que cualquier lengua pudiera pronunciar, o lápiz pudiera declarar,
o cualquiera pudiera creer,
excepto que este relato se encuentre con alguien que haya experimentado la misma tribulación;
el cuál la entendería. Así que, no tenía consuelo de noche ni de día,
pero aún así seguía, sin saber si viajaba en la dirección correcta o equivocada,
ni me atrevía a preguntarle a alguien por miedo a ser engañado como lo había sido antes.

Así me metí en la horrenda soledad de un desierto, donde pareciera no haber un camino,
solo de vez en cuando encontré algunas huellas de hombres y mujeres,
las cuales fueron de alguna forma consuelo para mí en mi dolor;
pero no sabía si ellos salieron sin ser devorados por fieras, ni qué camino tomar.
No obstante, viajé en este estado lamentable día a día,
preguntándome qué debía hacer--ya sea desesperarme por completo en esa condición,
o si debiera mejor buscar otro pueblo o ciudad,
para ver si podía conseguir otra guía. La primera opción me pareció desesperada,
pero también abandoné la última opción, habiendo sido tan engañado anteriormente;
de modo que todas estas consultas aumentaron la amargura de mi alma.

Un día mientras caminaba en la tarde, se levantó una terrible tormenta,
con granizo y truenos, y un gran viento, que duró hasta la noche,
y también durante la noche.
Y estando cansado, tanto física como mentalmente, me acosté bajo un gran árbol,
y después de un tiempo, me dormí. Cuando desperté y volví en mí mismo,
estaba aún muy oscuro; y mirando a mi alrededor,
vi una pequeña luz cerca de mí. Se me ocurrió ir hasta ella y ver de qué se trataba;
y en cuanto iba, la luz iba delante de mí.

Entonces me vino a la mente que había escuchado hablar acerca de luces falsas,
como la __ignis fatuus__,^
footnote:[También llamada linterna de los frailes, o fuego fatuo,
la ignis fatuus es una luz parpadeante y fosforescente que se ve durante la noche,
principalmente sobre terrenos pantanosos.
Se cree que su origen se debe a la combustión espontánea
de gases que se elevan de la materia orgánica descompuesta.
El nombre se usaba para referirse a cualquier guía
engañoso o que desviaría a un viajero de su camino.]
y cosas por el estilo que llevaría a las personas a salirse de su camino.
Pero luego volví a pensar: ¿Cómo seré llevado fuera de mi camino,
cuando no conozco un camino seguro?
Y mientras me senté para dejar que estos pensamientos
que luchaban dentro de mí siguieran su curso,
me fijé y observé que la luz estaba tan cerca de mí como al principio,
como si me hubiera esperado.
Me encontré muy afectado ante esto, y pensé dentro de mí,
que quizás algún espíritu bueno vino a apiadarse de mí,
para sacarme de esta condición miserable.
Así que surgió una resolución en mi mente de que me iba a levantar e iba a seguirla,
deduciendo en mi interior,
que no podría ser llevado en una condición peor que en la que me encontraba ahora.
Por consiguiente, me levanté y la seguí;
y ella iba a un paso lento y gentil al principio, y mantuve mi ojo pegado a ella.
Pero después, encontré que gran parte del equipaje y de las provisiones que había traído,
me pesaban en el camino; entones tiré una cosa,
y luego otra cosa que pensé que no era necesaria, pero seguí guardando un saco de ropa,
sin saber si iba a necesitarla.

A medida que avanzaba, con la luz delante de mí, me condujo fuera del desierto,
a lo largo de una tierra llana, sin árboles o habitantes;
parecía como si solamente unos cuantos hubieran pasado por ese camino anteriormente.
La luz se mantenía en ese camino estrecho, sin ningún giro o vuelta,
hasta que llegué al pie de una gran montaña; y subiendo esa montaña,
me costó mucho ascender, y comencé a considerar mi gran saco de ropa y atuendos.
Luego llegué a la conclusión de que muchos de ellos
no serían útiles para un viajero como yo,
que no sabía qué tan lejos debía ir,
ni si iba a necesitarlos si alguna vez lograra lo que buscaba;
ni sabía si las modas se ajustarían con el lugar al que iba.
Por tanto tiré algunas, y luego otras más,
hasta que no me quedaba nada más que lo que llevaba puesto.

De este modo, siguiendo a mi guía, por fin subí a la cima de esta montaña,
donde vi otra más alta.
También vi a un hombre que me preguntó a dónde iba.
Le dije que no le podía decir muy bien, pero que le podía decir a dónde deseaba ir.
Él me preguntó ¿a dónde?
Le dije, a la casa de Dios.
Él me dijo que este era en verdad el camino; pero él pensó que nunca iba a llegar.
Le pregunté, ¿por qué? "`Porque,`" dijo, "`en esa montaña hay tantas víboras,
cobras y serpientes, y tales bestias venenosas,
que devoran a muchas personas que van por ese camino.
Por mi parte,`" dijo, "`yo también iba,
pero estaba tan asustado por esas serpientes venenosas, que me vi obligado a regresar,
y le recomiendo lo mismo a usted.`"
Le respondí, "`Amigo, he seguido a esa luz como mi guía por un buen rato ya,
y me ha dirigido a lo largo de este camino, y veo que no me abandona; mira,
¿la puedes ver ahí delante de mí?`" Él respondió, "`Sí, la veo.`"
"`Bueno,`" dije entonces, "`he escuchado a través de viajeros,
que si un hombre tiene un fuego o una luz, las bestias venenosas no lo pueden lastimar;
y tengo la intención de agilizar mi paso un poco más,
y mantenerme tan cerca de la luz como pueda.
Ven, acompáñame y aventúrate.`"
Él dijo que era verdad, que él había escuchado que un fuego protegería de esas bestias;
pero pensaba que aquella luz no lo haría. Sin embargo, por su parte,
no aventuraría su preciosa vida entre esas bestias; y que si yo quisiera,
lo podría hacer.
Me deseó lo mejor, y así nos separamos.

Entonces me apresuré, y me acerqué bastante a la luz, y subí a la segunda montaña;
y cuando estaba casi en la cima de ella,
vi muchas guaridas de serpientes y agujeros de víboras,
tanto a la derecha como a la izquierda.
Las bestias venenosas se acercaron a mí y me sisearon, y comencé a sentir un gran temor,
y a temblar excesivamente.
Pero muchas veces, cuando ellas estaban listas para picarme,
la luz se ponía o aparecía entre ellas y yo,
y entonces ellas se asustaban y corrían a sus hoyos y guaridas.

Cuando percibí esto, ¡Oh! ¡cómo saltó mi corazón de alegría dentro de mí! Abundó mi gozo,
--mi temor por las serpientes disminuyó,
--mi amor por mi amable y tierno guía incrementó,--mi valor y mi confianza fueron renovados,
--y comencé a creer que me encontraba en el camino correcto para conseguir mi deseo.
Así que continué, manteniendo mi mirada en la luz a través de todas ellas,
sin recibir ningún daño,
hasta que llegué a la cima de la montaña. Entonces vi un valle extremadamente grande,
de modo que no podía ver el otro lado de él. Todo parecía ser un terreno baldío,
o lugares de agua, ciénagas y fango por todo el valle,
lo cual comenzó a desanimarme otra vez.
"`Pero,`" pensé, "`¿Qué debo hacer?
Todo ha estado bien hasta ahora.
Fui extrañamente liberado de las serpientes; y pase lo que pase,
si esta luz no me abandona, la seguiré, aunque sea por medio del fuego y de agua.`"

Entonces seguí, y bajé la montaña, a un paso suave y apacible,
y vi a muchas de esas criaturas crueles por el camino, que me lanzaron sus aguijones,
pero ninguno me pudo lastimar.
Y me di cuenta que entre más cerca me mantenía a la luz,
más se mantenían lejos de mí. Entonces bajé al pie de la montaña, a un valle grande,
que era muy verde y por un momento fue placentero; pero poco a poco,
la luz se dirigió a un gran terreno bajo y lleno de agua que me pareció muy peligroso;
pero al llegar justo al lado del lugar,
vi un pequeño camino estrecho que iba por el medio del mismo,
lo suficientemente ancho para que un hombre pudiera caminar
sobre él. La luz me llevó hacia ese camino estrecho,
y fue delante de mí. Mientras mantenía mi ojo fijo en ella, iba seguro,
pero si en algún momento comenzaba a mirar alrededor,
mis pies se deslizaban hacia el fango y los charcos,
y entonces tenía muchas dificultades para volver al camino.
Si la luz no me hubiera esperado con tanta ternura y amabilidad,
de cierto la habría perdido de vista y perecido en el camino;
pues algunas veces estaba tan lejos de mí que difícilmente la podía discernir;
y por ende aumentaba mi diligencia, y era más cuidadoso con mis pasos,
manteniéndome tan cerca de ella tanto como podía;
de modo que algunas veces la luz brillaba a mi alrededor,
y yo podía caminar en el resplandor de ella con gran plenitud de espíritu.

Después de un largo tiempo de haber caminado por este camino estrecho,
levanté mis ojos hacia el lado más alejado del bajo y húmedo valle,
y vi que había más allá una montaña muy alta, y en la cima de ella había una gran casa:
que apenas la vi fui grandemente consolado,
suponiendo que esta podía ser la casa que yo había buscado por tanto tiempo.

Sin embargo justo después de esto, me encontré con otro ejercicio difícil:
percibí que había muchos que habían estado viajando en este camino estrecho,
pero que habían caído en el fango; algunos a la derecha y otros a la izquierda.
Estos yacían revolcándose llenos de envidia;
algunos tratando de alcanzarme para jalarme a ellos;
otros lanzando fango y tierra sobre mí para desanimarme: otros hablaban muy bien,
con el propósito de invitarme a hablar con ellos, para que,
al perder así mi preciado tiempo,
me retrasara tanto que perdiera de vista a mi buen guía. Pero vi sus designios malignos,
y era consciente de ellos.
Así que, al mantenerme en mi camino estrecho hasta que llegué al final del valle fangoso,
entonces encontré suelo firme debajo de mis pies, para mi gran consuelo.

Solo había avanzado un poco, cuando mi guía, la luz, entró en una ruta estrecha,
con grandes arbustos por ambos lados; ante lo cual me alegré,
pensando que ahora no podía equivocarme, y no tenía que tener tanto cuidado.
Pero ¡Ay!
De pronto encontré tantas rutas, y caminos,
que aparecían casi tan directamente delante de mí como aquel camino por el que empecé,
que si no hubiera sido por la luz, que iba un poco por delante de mí,
seguramente me hubiera equivocado muchas veces.
Sin embargo, siguiendo cuidadosamente a mi buen guía, por fin subí la montaña,
y vi de nuevo la casa.
Después vi a un hombre de ese lugar, bastante lejos de mí, y lo llamé, "`¡Hola amigo!
Amigo, ¿cuál es el nombre de aquella casa grande?`"
Me dijo que el nombre era BET-EL. Entonces recordé que ese era el nombre
que se usaba para la casa de Dios en la tierra de mi padre,
donde había escuchado las noticias de ella,
y donde me había propuesto tan fervientemente a encontrarla.

¡Oh!
Ninguna lengua puede expresar la alegría y el consuelo que sentí
en mi alma--pensar que ahora después de todos mis viajes,
peligros, y decepciones, había encontrado lo que estaba buscando.
Así que continuaba, viajando con una alegría indecible; y mientras avanzaba,
vi la fachada de la casa: era muy grande, y tenía tan solo una torre;
no había ningún trabajo tallado, ni pintura,
ni ningún tipo de diseño que pudiera discernirse;
pero todas las piedras estaban curiosamente unidas desde arriba hacia abajo.
También noté, que todas las piedras del edificio eran transparentes,
algunas más que otras; y no vi ventanas.
Y al acercarme a ella, vi que tenía un gran atrio exterior,
con un portón bastante grande para entrar,
de modo que un hombre pudiera entrar con una gran carga sobre su espalda.
Así que habiendo llegado, entré; y allí vi a muchas personas que estaban alegres,
y parecían vivir vidas muy agradables.
Algunos de ellos me dijeron, que habían vivido ahí por muchos años,
que estaban bien satisfechos y que no les faltaba nada;
porque había un inmenso árbol que crecía en el medio del atrio, y su fruto era bueno,
y las hojas también, y daba fruto durante todo el año. Además,
muchos eran tan amables como para invitarme a sentarme y a comer con ellos;
pero yo me rehusé. También me enseñaron una gran cisterna que habían cavado para sí,
para recoger el agua de los elementos;
asimismo habían hecho viviendas convenientes en los
costados del atrio exterior para alojarse.

Pero esto no me satisfacía, porque vi a mi amado guía pasar a través de todos ellos,
y entrar en una puerta estrecha en un lado más lejano.
Ante esto, los dejé, y me apresuré hacia la puerta, donde vi que mi guía había entrado.
Intenté entrar ahí, pero no pude porque era demasiado estrecha;
esto me entristeció grandemente, y no sabía qué debía hacer.
Mis pensamientos me inquietaban por doquier, y probé todas las formas posibles de entrar,
pero todo fue en vano.
"`¡Oh!`"
Pensé, "`¿Todos mis problemas y esfuerzos han llegado a esto?
¿Debo ser excluido al final?
¿Qué debo hacer?`"
Mientras me encontraba en un estado de perplejidad interno, creí escuchar una voz,
pero no sabía de dónde provenía, la cual dijo, "`joven,
despójese de todas sus vestiduras viejas, y así podrá entrar.`"
Esto me preocupó aún más; porque me resistía a ir desnudo:
pero finalmente pensé que es mejor ir desnudo, que no ir del todo.
Así que por fin comencé a desnudarme,
pensando que unos pocos y despreciables trapos no deberían impedirme de tan grande gozo.
Entonces cuando quedé completamente desnudo como en el día en que nací,
intenté entrar y no encontré ninguna dificultad.
Y justo en cuanto entré,
alguien apareció y me arrojó una vestidura de lino puro sobre mí,
que llegaba hasta mis pies.
Me llevó a una habitación estrecha y me dijo, "`Descansa aquí durante un rato.`"
Luego, me acosté con tanto gozo y consuelo que es imposible expresarlo.
Todo a mi alrededor era tan agradable y mi lugar de descanso era tan deleitoso,
y mi corazón tan satisfecho,
que todo en mí se llenó de canciones de alegría. Pero encontré
que mi deber era estar tranquilo y quieto en mi alegre condición,
que había comenzado a disfrutar.

No había pasado mucho tiempo en esta habitación,
cuando salí a ver la belleza y hermosura de esta casa.
Mientras caminaba por ella, encontré todo muy limpio y brillante,
de modo que estaba encantado de una manera admirable.
También me encontré con algunas personas que me dieron la bienvenida
a la casa de Dios con tanta amabilidad que refrescó mi corazón:
y mientras me familiarizaba con ellos, notaba su conducta,
y sus discursos me fueron sumamente reconfortantes.
No había disputas, ni contiendas, ni palabras orgullosas ni airadas,
pero todo se llevaba a cabo con mansedumbre y reverencia;
y con el debido respeto el uno con el otro.
Los hombres jóvenes esperaban por las palabras de los ancianos,
y las vírgenes tenían un respeto reverente hacia las matronas;
y había tal cuidado y unidad universales, que me maravillé enormemente.

Un día, mientras le abría mi corazón a un anciano,
le dije que admiraba mucho la unidad universal que había notado,
la cual me maravillaba grandemente, más allá de todo lo que había conocido en mi vida.
Me dijo que debía ser así, y no podía ser de otra forma,
porque el guía que me había traído ahí, había sido el guía de todos.
Y además me dijo,
que no podía haber contienda excepto cuando dos espíritus luchan por dominar;
pero que no era así en esta casa.
Su respuesta fue tan completa y satisfactoria para mí, que no le dije más en ese momento,
sino que seguía observando y admirando el orden de todo, hasta que mi alma se llenó,
y sentí que mi copa se rebosó. Así que mis pasadas angustias y decepciones,
tristezas y peligros, ahora no significaban nada para mí,
habiendo encontrado cien veces más, la recompensa mayor.

Entonces regresé de nuevo a mi descanso, en una habitación más grande que la anterior,
cantando alabanzas a mi Dios, y declarando las alabanzas de la casa,
y de aquellos que moraban ahí. Y después de un momento,
fui llamado desde la habitación donde me encontraba,
y me dijeron que no había sido traído a ese lugar solo para disfrutar y deleitarme en él;
pero que había trabajo por hacer, y que debía asumir mi parte,
y ser fiel y diligente en mi empleo.
Ante esto contesté,
que era suficiente haber alcanzado ya mis deseos al ser admitido en este lugar celestial;
pero si había algún trabajo que hacer, estaba dispuesto a hacerlo, cualquiera que fuera;
pues sería mi más grande alegría hacer cualquier cosa para
el crecimiento del honor de la casa de Dios,
y de aquellos que moraban en ella.
Después, él que habló conmigo,
me dijo que era mi deber enseñarles a los niños hasta
donde yo había llegado a aprender y conocer,
y en la medida en que yo reciba de vez en cuando más instrucciones.
Me encontraba un poco maravillado ante esto, conociendo mis debilidades:
pero habiendo meditado un poco en esa parte de la oración,
que "`debo recibir de vez en cuando más instrucciones,`" tomé con valentía mi trabajo,
e hice algunos progresos en él, con gran temor y reverencia;
esperando diariamente esas instrucciones que iba a recibir,
y las cuales recibí de manera abundante.
Entonces el trabajo prosperaba en mi mano, y los niños me amaban,
y yo los amaba completamente, como si fueran mis propios hijos:
y muchos de ellos crecieron hasta llegar a un buen entendimiento,
atendiendo para mi gran satisfacción, sus ocupaciones y órdenes.

Después de haber continuado así por un tiempo, el que habló conmigo,
vino y me dijo que debía hacerme cargo de una parte de la familia,
y darles su comida en su debido tiempo;
repartiendo la comida de todos según su estado y condición,
no alimentando a los hombres fuertes con leche, ni a los bebés con carne.
Y para esta obra, me dio una llave que llevaba al tesoro o almacén;
donde pude ver y admirar que estaba lleno en abundancia con toda clase de alimento,
que nunca podría agotarse o gastarse mientras el mundo existiera.
Aquí observé que cualquier cosa que pudiéramos sacar de ahí, tanto yo como los otros,
para distribuir diariamente entre los miembros de la familia de Dios,
el almacén permanecería aún así lleno como al principio,
y así continúa hasta este día y para siempre.

Ahora, habiendo continuado por un largo tiempo en esta habitación celestial,
viene a mi mente permitirles a mis parientes, y a los hijos de mi viejo padre,
a quién dejé en Babilonia, que sepan de mí;
porque supongo que deben creer que estoy perdido o que fui devorado.
Pero estaría contento si alguno, sí, todos ellos, estuvieran aquí para contemplar,
saborear y sentir lo que siento yo.
Y que nadie diga que fui más afortunado que otros, porque he entendido,
desde que llegué a esta casa, que la misma Luz que se me apareció,
aparece a cualquier pobre alma angustiada en todo el mundo;
pero la razón por la que muy pocos vienen aquí es porque
temen los riesgos y peligros que están en el camino,
más de lo que aman la Luz que los guiaría a través de ellos;
por lo tanto se hacen a un lado, refugiándose en un edificio podrido,
que en un tiempo u otro, caerá sobre sus cabezas, y perecerán en las ruinas.

Ahora, si alguno le interesa saber mi nombre,
hágale saber que tenía un nombre en la tierra de mi padre,
pero que en este viaje largo y tedioso, lo he perdido.
Sin embargo,
desde que llegué a aquí tengo un "`nuevo nombre,`"
más no tengo letras ni caracteres para indicarlo,
que puedan ser escritos o leídos.
Aún así, si alguno viene donde yo estoy, sabrá mi nombre.
Pero para satisfacerlos aún más, diré esto: Nací en Egipto, espiritualmente llamado así;
y mi padre fue a Babilonia y vivió allí en el tiempo en
que los verdaderos hijos de Israel estuvieron en cautiverio.
Allí me familiaricé con algunos de la tribu de los Judíos,
en el momento en que se estaban devolviendo a su tierra natal;
y me contaron cosas maravillosas de la gloria de la casa que tenían en Jerusalén,
y les hubiera gustado que fuera con ellos.
Y entendí que Salomón,
junto con muchos miles de carpinteros y albañiles la habían construido.
Pero consideré dentro de mí que si Salomón y los
carpinteros y los albañiles la habían construido,
entonces los carpinteros y los albañiles podrían derribarla de nuevo,
en un momento u otro.
Así que no me fui con ellos, sino que busqué una ciudad cuyo constructor es Dios,
y ahora la he encontrado; "`Aleluya en lo Altísimo;`" gloria, honor,
prominencia a su digno Nombre y poder, por todas las edades y generaciones.
Amén.
