== Un Camino Simple

Amigos y pueblo,

Mi espíritu ha sido profundamente ejercitado con respecto a muchos,
quienes han llegado a sentir algo que es bueno despertarse y moverse en sus corazones,
para llevarlos a una consideración seria del curso de sus
vidas y del verdadero estado interno de sus almas inmortales.

Cuando, en algunos momentos,
ustedes comenzaron a volver sus mentes hacia esta
cosa buena que se había despertado dentro de ustedes,
muchas dudas y objeciones se levantaron en sus corazones,
pensando que podían ser desviados, engañados o descarriados; o pensando que esta cosa,
que internamente luchaba contra ustedes, los llevaría al camino erróneo de los cuáqueros,
como los maestros del mundo lo llaman.
Entonces ustedes son tentados a despreciarla,
e incluso a encontrar un nombre con que criticarla, por el cual llamarla,
nombres que los ministros del anticristo tienen muchos para ofrecerles;
como llamarla una luz natural, un don común del Espíritu, ¡pero no un don que salva!;
la convicción de una consciencia natural, obras de la ley,
o una obra del diablo para perturbar al alma de su paz, y algunos, una luz diabólica,
etc.

Y así, cuando ustedes son llevados a despreciar con alguno de estos nombres,
ese buen Espíritu que lucha contra ustedes,
encuentran alivio otra vez por un corto tiempo,
y se toman la libertad de actuar en contra de Él,
y de hacer y decir lo que este Espíritu en lo secreto condena.
Pero luego este se vuelve a levantar, y quebranta su paz,
y trae tribulación y angustia sobre sus almas.
Entonces se levantan dudas por un lado y dudas por el otro,
y sus pobres almas están rodeadas y envueltas en dudas y temores.
A veces tienen miedo de estar resistiéndose a la Verdad para su propia destrucción,
pero otras veces temen que sea una ilusión, y que estén siendo engañados.
Además de esto, encuentran a muchos hombres entendidos y sabios del mundo,
que les dicen que no hay nada bueno dentro de ustedes.

Aquí ustedes están en un gran aprieto, esforzándose bajo muchos pensamientos tristes,
y muchos razonamientos confusos surgen en sus mentes.
La carne ahora lucha fuertemente contra lo que viene a perturbarla,
y el Espíritu lucha fuertemente contra lo que lo resiste y se le rebela.
Estos dos son contrarios, y ambos están en ustedes; y ustedes, pobres criaturas,
deben sentir la lucha de ambos, y debido a sus tinieblas, dudas, y temores,
apenas saben (o por lo menos con certeza) cuál es el bueno.
En este estado y condición ¡qué aceptable sería un mensajero, uno entre mil,
que le muestre a tal persona lo que puede librar su alma de descender al hoyo,
y salvar su vida del destructor! Job 33:23-24.

Realmente muchos en estos días están en esta difícil condición;
por el bien de ellos muchas veces yo soy llevado a un profundo ejercicio,
de día y de noche,
y mi clamor a Dios es que Su poder glorioso pueda levantarse más y más
para abrir estas puertas que están cerradas y selladas sobre estos,
y para sacar a los espíritus encarcelados fuera de la prisión,
y fuera de la esclavitud de este Egipto espiritual,
donde nuestro Señor fue y es crucificado espiritualmente,
y para que Él pueda expulsar las nubes de oscuridad, en las que surgen los temores,
las dudas y los razonamientos, y para que Él pueda despejar el camino en todos ellos,
para que su Luz surja de la oscuridad,
de la cual surge la respuesta a esas dudas y preguntas.

Y por el mismo Espíritu que contiende con ustedes, soy movido a enviarles esto a todos,
como una palabra de exhortación y consejo en el nombre y temor del Señor Dios,
por la cual, todos los que la reciben correctamente,
y hacen un verdadero uso y prueba de ella, encontrarán ayuda y beneficio;
y experimentarán la boca del interrogador cerrada,
y la respuesta de paz testificada en sus almas inmortales,
en el tiempo debido del Señor. Por lo tanto, consideren esto:
todo don bueno y perfecto viene de arriba, del Padre de las Luces y de los Espíritus,
que no quiere la muerte del pecador, sino más bien que se vuelva y viva.
Por lo tanto Él,
de Su infinito amor y de Sus tiernas misericordias para los hijos de los hombres,
ha preparado un camino para acercarse a ellos,
aun cuando ellos todavía están en sus pecados,
lo cual Él no hace sino por medio de Jesucristo el Mediador del nuevo pacto,
a quien Él ha dado gratuitamente como una luz para el mundo oscuro,
para que ilumine a todo el que viene al mundo, Juan 1:1-4,7,9. Por tanto,
quienquiera que sean ustedes, han sido iluminados por Cristo,
aunque todavía sean tinieblas en sí mismos, como los efesios una vez lo fueron.
Aun así, la Luz resplandece en su oscuridad,
o de otra manera no habría dos naturalezas y semillas
contrarias obrando en ustedes como lo están;
y esta Luz por la cual ustedes son iluminados es la vida de Jesús, Juan 1:4,
la cual Él ha dado en rescate por el hombre.

Pero sepan esto, ustedes que están inquiriendo,
que eso dentro de ustedes que les manifiesta las cosas que son reprobables,
es la Luz con la cual Cristo los ha iluminado,
como dijo el apóstol de Cristo en su epístola a los Efesios,
5:13-14. Y ese principio que los lleva a hacer o decir esas cosas por
las que ustedes son reprobados secretamente en sus propias consciencias,
eso es la oscuridad y el enemigo de la paz de sus almas,
en cuya oscuridad aquellos que caminan no saben hacia donde van.
Esta ministra una paz y un placer para ustedes,
y ministra un deleite para sus mentes carnales por un tiempo; sin embargo la otra,
a saber, la Luz, la reprobadora, tiene poder para quitarles la paz otra vez,
y para juzgarlos, y para hacer que aquello que era dulce para ustedes se haga amargo;
y ni la oscuridad, ni la vanidad de sus mentes puede librarlos de este golpe.

Ahora, para que puedan determinar qué hacer en tal estado, consideren,
ustedes que han tenido estas luchas internas con respecto a la Luz en sus consciencias,
si es verdadera o no, o si ustedes la reconocerán o no,
y están pensando en sí mismos qué es lo mejor que ustedes pueden hacer,
si continuar tenazmente en contra de ella, o someterse a ella: Yo les digo, consideren,
si ustedes se rebelan en contra de ella, nunca sabrán a dónde los llevará;
como fue dicho en el tiempo antiguo, Job 24:13,
"`Aquellos que se rebelan en contra de la Luz no conocen sus caminos.`"
De modo que, si toman el curso de la rebelión,
eso no hará sino incrementar su ignorancia del camino en el cual la Luz guía,
y la hará más terrible para ustedes cada vez que ella aparezca en ustedes,
hasta que lleguen a este estado del cual se habló en Job 24:17:
"`la mañana será para todos ellos como sombra de muerte.`"
Porque cuánto más se rebelen en contra de ella,
más crecerá la oscuridad en ustedes diariamente,
y por lo tanto serán menos capaces de resolver ustedes
mismos esas cosas dudosas que llenan sus mentes,
sino que así como la oscuridad se incrementa en ustedes,
así el poder de ella los atará como una cadena, y ahogará todo buen deseo en ustedes.
Y así, por la rebelión en contra de la Luz,
algunos hombres pierden el sentido mismo y conocimiento de ella,
haciéndose insensibles y extraños a ella, aunque ella esté dentro de ellos;
porque la costumbre del pecado quita el sentido y el sentimiento de la carga de ella.

Pero a ustedes les escribo,
que todavía no han llegado a este estado de dureza de corazón,
sino que son llevados diariamente a un sentido de la carga del pecado,
y están listos para decir:
"`si estuviéramos seguros de que aquello que nos muestra
nuestro pecado es la verdad y el camino de Dios,
lo seguiríamos, lo amaríamos y lo recibiríamos`",
pero se mantienen lejos por las dudas y los cuestionamientos.
Ciertamente les digo, que antes de que estas dudas puedan ser resueltas,
ustedes deben probar este camino, tal como han probado el otro (para su propio dolor),
antes de que puedan ser efectivamente informados,
porque los argumentos no serán suficientes en este caso.
Por lo tanto,
pongan a prueba lo que este principio puede hacer por ustedes cuando lo obedezcan,
el cual ustedes ya saben que tiene el poder de condenarlos
y de quebrar su paz cuando ustedes lo desobedecen.

¿Por qué van a estar siempre encerrados en incredulidad y en dudas,
y así privados de intentar y probar la Luz, tal como ustedes han probado la oscuridad,
para que entonces puedan cosechar el fruto de ella para salvación,
como también ustedes han cosechado el fruto de lo otro para condenación?

¡Oh, estimado pueblo!
Consideren esto: ustedes no pueden obedecer esta Luz de Cristo Jesús en sus consciencias,
sino al tomar una cruz diaria en contra de sus voluntades, deseos y afectos,
porque la Luz es contraria a ellos.
Aquello que lleva a obedecer sus deseos, también lleva a desobedecer la Luz;
y aquello que lleva a obedecer la Luz es contrario a los deseos y viles afectos,
los cuales están en enemistad con la Luz y deben ser juzgados y condenados por ella.
Aquello que los lleva a despreciarla y a llamarla por algún nombre desdeñoso,
también es un enemigo para ella, y debe ser juzgado por ella.
A medida que la Luz llega a gobernar sobre estas
cosas en ustedes que son enemigas de ella,
ustedes conocerán que ella los guiará de manera contraria a su naturaleza corrupta;
y a medida que ustedes la sientan obrando en sus corazones,
llegarán a ser más sabios que esos maestros que la han llamado una luz natural.
Porque aquello que es natural guía de acuerdo a la naturaleza,
pero aquello que es espiritual guía de acuerdo al Espíritu;
del cual el apóstol dijo que es contrario a la carne y lucha en contra de ella.

Y así, por medio de su obediencia a la Luz,
esta objeción llegará a ser respondida mucho mejor de lo
que podrían haber hecho las palabras y los argumentos.
De la misma manera, si ustedes no se oponen a la Luz,
sino que se entregan a ser guiados por ella, ustedes llegarán a sentir su suficiencia,
y sabrán que ella es capaz de librarlos cuando son tentados,
como también juzgarlos cuando se han entregado al tentador.
Porque ustedes ya saben que tiene el poder de condenarlos cuando pecan en contra de ella,
pero definitivamente no pueden conocer su suficiencia para
darles paz y para justificarlos hasta que la obedezcan.

Entonces,
el camino simple para la respuesta de sus dudas acerca
del Espíritu de la Verdad en lo íntimo,
se encuentra al obedecerlo y entregarse a Él. Aquellos
que hacen el mal crecen en su odio hacia Él,
y Él los juzga.
Así como ellos se rehúsan a obedecer la Luz, la Luz también rehusará justificarlos, y,
por tanto, al caer bajo la justa condenación de la Luz, se aumenta su miedo hacia ella.

Pero ¡ay! esto sólo demuestra que ella es enviada por Dios,
porque hace la obra de Dios que es justicia.
"`El que justifica al impío, y el que condena al justo,
ambos son igualmente abominación a Jehová.`" Y así
es con Su testigo en sus propias consciencias,
que Dios ha puesto allí para dar testimonio para Él con respecto a todas sus acciones,
ya sean buenas o malas.
Y ustedes mismos, no importa quienes sean, grandes o pequeños, ricos o pobres,
profesantes o profanos, confesarán esto:
Que esta Luz nunca los ha condenado por aquello que era bueno,
ni ha dado testimonio en contra de ustedes por aquello de lo que ustedes no eran culpables.

Por lo tanto, todos ustedes,
que han sido sofocados y confundidos con dudas y preguntas acerca de la verdad, vengan,
escuchen el consejo de Dios en este tiempo,
pronunciado una vez más hacia ustedes de parte de
su Espíritu por uno de sus siervos fuera de ustedes,
y respondido por la medida de Su buen Espíritu dentro de ustedes,
el cual tiene la misma voz y clamor en ustedes,
por obediencia a lo que es manifestado de Dios dentro de ustedes.
Obedezcan a la Luz y verán diariamente más de ella,
hasta que despunte como la mañana en ustedes, y hasta que resplandezca,
hasta que el día es perfecto; sí,
un día de felicidad y gozo para sus pobres almas afligidas.

Levántense, ustedes que se sientan en dolor,
y ustedes que están clamando en secreto por causa de las
ataduras y cadenas que están todavía sobre ustedes.
Levántense, levántense, yo les digo en el nombre del Señor Dios de Sion,
quien se acerca a ustedes por medio de Su Espíritu vivificador, y escuchen Su voz,
quien dice al prisionero "`Salid`" y a los que están
derribados "`Levántense;`" y a los débiles:
"`Vístanse de fortaleza, síganme y obedézcanme.
Yo confundiré a sus oponentes y quebrantaré la fuerza de sus enemigos.
Como he hecho por Mi pueblo, quienes me obedecen y han abandonado todo para seguirme,
así haré por ustedes.
Y si ustedes caminan rectamente ante Mí, y guardan Mi pacto, como ellos han hecho,
ningún poder ni fuerza del enemigo, dentro o fuera,
serán demasiado fuertes para ustedes.`"

Y cuando el Señor se levanta así en sus almas y mueve a su Testigo puro,
y Su brazo se despierta en ustedes, y Su Luz pura despunta:
¡oh! ¡qué consuelo es para ustedes,
y cómo muchos de ustedes han visto sus vanas dudas despejadas,
y una convicción clara ha prevalecido en sus espíritus con respecto al camino de Dios!
En ese momento se decidieron seguir al Señor en Su camino puro de santidad,
que de esta manera fue abierto para ustedes en la Luz,
aunque significara la pérdida de todo y aunque tuvieran que cargar su parte del
gran oprobio que está sobre aquellos que lo aman más que a sus vidas.
Y en ese momento se sintió un gozo secreto en sus almas,
y la Semilla del reino que ha estado enterrada por
mucho tiempo comenzó a brotar en ustedes,
y en esta Semilla sus almas sintieron algunos toques de esa vida y gozo
celestiales que exceden todas las cosas que este mundo puede ofrecer.

Cada vez que ustedes lleguen a sentir este rocío refrescante sobre sus almas,
presten atención y esperen con simpleza en el sentir de él. Mantengan su mirada
en el gozo que ahora está puesto delante de ustedes en Cristo Jesús,
la Simiente, porque si ustedes dejan que sus mentes deambulen,
y que sus ojos vayan tras lo exterior,
habrá objetos en todas partes para alejarlos del amado de sus almas,
y para contaminar sus corazones y convertirlos en un lugar no apto para que Él resida,
que es santo y puro.
No morará, ni se deleitará en un templo contaminado, sino más bien se alejará,
como se alejó del Israel antiguo y de su templo, cuando fue contaminado y profanado.

Por otro lado,
cuando sus mentes son atrapadas por cualquiera de
las cosas corruptibles de este mundo cambiante,
pronto se despertará un deseo, anhelo y lujuria por el disfrute de estas cosas,
aunque son contrarias a la voluntad de Dios.
Entonces el razonador y consultor se levanta en ustedes y comienza a preguntar:
"`¿Acaso no puedo disfrutar al Señor y esto?
¿Acaso no puedo mantenerme en el camino de la verdad,
y aun así hacer esto y aquello que mi corazón desea?
Y aunque no esté perfectamente de acuerdo a la verdad que ha sido manifestada en mí,
aun así voy a satisfacer mi voluntad y deseo,
sólo una vez más.`" "`Eso no es gran cosa,`" dice el consultor;
"`y esto no es nada más que un asunto pequeño,
hay otros que hacen cosas más grandes que estas.`"

Estos razonamientos que entran en la mente,
afligen y contristan a ese tierno Espíritu bueno y justo que se movió en ustedes.
Traen un peso y una opresión sobre el Testigo puro en ustedes,
el cual se retira otra vez de ustedes,
y por tanto una noche viene sobre ustedes donde antes una luz se había levantado.
Porque donde la serpiente lleva a cualquiera a hacer
una pregunta acerca de obedecer la verdad,
se encontrará que ella está tan lista para formar la respuesta como para crear la pregunta,
pero su respuesta siempre viene con una libertad y persuasión para desobedecer,
como lo hizo con Eva al principio; y cuando la transgresión se ha consumado,
entonces la muerte entra en ustedes con su oscuro poder,
y múltiples penas penetran sus pobres almas.
Aunque el fruto era deseable para comer, sin embargo, ahora que ha sido consumido,
ustedes no pueden acercarse a la vida para comer de ella también, aunque la deseen,
sino que son sacados y mantenidos afuera por una espada encendida,
que se mueve en toda dirección en contra de ustedes.

Ahora se levantan en ustedes dudas y cuestionamientos de una naturaleza más alta.
Antes dudaban de la Verdad misma, si es que era la verdad o no, pero ahora,
habiéndola probado y habiendo sido convencidos por ella,
han dejado que sus mentes se alejen de ella tras otros amantes,
y sus oídos tras la voz de la adúltera, y así, por medio de su rebelión,
han causado que la Luz pura se aleje de ustedes.
Ahora ustedes desean poder ver otra vez lo que habían visto,
y sentir otra vez lo que habían sentido, pero dudan y temen que nunca más verán,
sentirán, ni disfrutarán algo similar otra vez.
Y ahora desean, oh,
si ustedes se hubieran mantenido bajo la cruz con respecto
a su propia voluntad y si se hubieran negado a sí mismos,
para no perder así la vista y el sentir del amado de sus almas.
Y ven, por la dolorosa experiencia, de donde se levantan las dudas, temores y penas,
a saber, al unirse con el enemigo,
que presenta razonamientos en contra de la obediencia a la Luz.

Ahora, por lo tanto, presten atención a aquello que queda en ustedes,
aunque la oscuridad y el dolor los rodeen.
Todavía hay algo que les da un sentido de su estado y condición,
y los hace conocer su pérdida y su carencia.
Oigan la voz de esto, y esto los humillará,
y los llevará hacia el verdadero quebrantamiento de corazón, y contrición de espíritu.
Y a medida que ustedes lleguen a conocer este estado de quebrantamiento,
entonces tendrán algo que ofrecer al Señor de Su propia hechura,
lo cual será mucho más aceptable para Él que una multitud de palabras,
acciones y deberes (así llamados).
Y a medida que ustedes, en verdadera bajeza de mente,
vengan ante el Señor y ofrezcan esta ofrenda,
Dios oirá en el cielo y responderá el clamor de sus almas pobres y necesitadas,
las cuales no pueden ser satisfechas sin Su presencia.
Sí, Él recordará sus misericordias antiguas, que nunca fallan, por amor a Su Semilla,
la cual todavía no ha sido manifestada en ustedes.
Y debido a la transgresión en la que ustedes han caído,
cuando Dios resplandezca otra vez, y dé a conocer Su poder,
ustedes deben esperar que esto sea en juicio,
para que Él consuma en ustedes aquello que los llevó hacia el pecado,
fuera de su ley pura, la cual es Luz; porque "`Sion será redimida por juicio.`"
(Isaías 1:27)

Por tanto,
tengan cuidado de no ofenderse por Su aparición. Tengan cuidado de limitar al Santo,
porque si Su aparición viene con más agudeza y amargura para la parte carnal, que antes,
que sea así es sólo lo justo.
Es el Señor, dejen que haga lo que le parece bien.
Él, ahora, ve más razón para hacerlo así que antes,
por causa de que ustedes han pecado mucho más en contra de Su bondad,
pero inclínense a sus juicios, soporten su indignación,
porque ustedes han pecado contra Él. (Miqueas 7:9).
A medida que ustedes cedan a sus justos juicios,
experimentarán Su venida en medio de ellos,
en la cual la misericordia es recordada y manifestada.
Por lo tanto, los apurados e impacientes,
que huyen del juicio tan pronto como comienza a aparecer un poco en ellos,
nunca encuentran verdadera liberación,
sino que obtienen alivio de otra manera que no perdura sino por un momento.

Pero aquellos que llegan a experimentar la obra completa
efectuada en la tierra de su alma,
y el piso de sus corazones completamente purificado,
también llegan a sentir la paz verdadera y duradera de sus almas inmortales.
Y aunque esto no se obtiene por medio de comodidad
y libertad para la mente carnal (que debe morir),
sin embargo, serán coronados los que perseveren hasta el fin; estos son los salvos,
como Cristo dijo,
Marcos 13:13. Estos experimentan la veracidad de las palabras del salmista,
"`Los que siembran con lágrimas,
con regocijo segarán. Irá andando y llorando el que lleva la preciosa semilla;
mas volverá a venir con regocijo, trayendo sus gavillas.`"
Y como Cristo dijo, "`todo aquel que deja casas, o hermanos, o hermanas, o padre,
o madre, o mujer, o hijos, o campos por causa de mi nombre,
recibirá cien veces más y heredará la vida eterna.`"

Dejar todo y negarse a sí mismo,
siempre han sido el camino hacia la vida y hacia la verdadera bendición,
y continúan siendo el camino hasta este día. Por lo tanto,
todos ustedes que han deambulado en sus propios caminos,
y aún no han aprendido a negarse a sí mismos de aquello
que es contrario al Testigo de Dios dentro de ustedes mismos,
sino que tienen deseos (y unos muy fuertes también) incluso
de guardar y sostener lo que la Luz reprueba en ustedes,
y sin embargo desean la vida y la paz,
y por lo tanto están en muchas dudas y aprietos con respecto a estas cosas,
para todos ustedes este es el consejo del Señor, y el clamor de Su Espíritu puro:
Salgan de la confusión babilónica de sus propios pensamientos,
y no toquen aquello que es impuro,
y el Señor los recibirá. Lo que Dios por Su Espíritu puro ha llamado impuro,
que ningún hombre presuma llamar limpio, ni se una a ello,
no sea que sea hallado luchando en contra de Dios,
y nutriendo y manteniendo vivo lo que Dios designó para morir y ser destruido.
Ustedes no pueden servir a dos maestros,
o tomar parte de la mesa del Señor y de la mesa de los demonios.

¡Oh! no alimenten ese nacimiento que tiene hambre de cosas impías,
y que se deleita en ellas, sino que lo que es para hambre, que muera de hambre;
y lo que es para la espada,
que la espada de dos filos que sale de la boca del Testigo fiel y verdadero, lo corte.
Apocalipsis 1:16,
3:14. Y entonces puedan ver a los gigantes en la tierra destruidos delante de ustedes,
por Uno que es poderoso para liberar y para sacarlos
de este Egipto espiritual con mano poderosa.
Pero no pueden llegar a experimentar esto excepto al seguirlo diligentemente;
y si ustedes ceden voluntariamente a su dulce atracción, cuando la sienten en su corazón,
hallarán que es eficaz y beneficiosa para sus almas.
Mientras más lo sigan a Él,
más sentirán Su bondad irrumpir sobre ustedes para darles ánimo,
y menos esperarán dudando de su amor y misericordia al llevarlos aún más adelante,
incluso hasta el fin, y hacia ese reposo que satisface sus almas.

Por lo tanto,
pongan a un lado todas las consultas que están en
contra de su obediencia al don de Dios en su corazón,
el cual reprueba el pecado en ustedes,
y que no da lugar a las vanas e innecesarias dudas acerca de ello.
Y tal como ustedes han sido condenados y juzgados al desobedecerlo,
ahora intenten y prueben si al tomar su cruz diaria y obedecerla en sus palabras y acciones,
y en todas las cosas, ustedes no encuentran el resultado de dulce paz y gozo.
Cuando encuentren que es así,
entonces no habrá más lugar para las dudas y los
razonamientos en contra de su obediencia al don;
pero a medida que cualquier pregunta o duda se levante en ustedes,
sentirán la respuesta de paz en ustedes mismos para su gran refrigerio.

De esta manera llegarán a experimentar la operación
eficaz de él diariamente en sus almas,
para obrar su cambio y traslado fuera de sí mismos hacia su propia naturaleza,
y así ustedes llegarán no sólo a conocer la Luz en ustedes,
sino que sabrán que están en la Luz, y que caminan allí con Dios en la comunión santa,
y en esta sienten que el Señor está cerca de ustedes en Su Luz,
y Su recompensa con Él. Porque un hombre puede saber
que la Luz está en él y aún así perecer,
porque Cristo dijo que esta es la condenación: que la luz ha venido, pero no es amada.
Pero ustedes, al amar la Luz, llegarán a caminar y a morar en ella.
Su ciudadanía estará en el cielo, como estaba la de los santos en el tiempo antiguo,
y experimentarán su comunión con el Padre y con el Hijo, así como ellos, quienes dijeron:
"`Si andamos en luz, como él está en luz,
tenemos comunión con Él,`" y si algunos dicen que tienen comunión con Él,
y aun así andan en tinieblas (que es lo que todos los pecadores hacen,
porque el pecado es la obra de las tinieblas), de ellos fue dicho que son mentirosos.

Aquellos que caminan en la luz, como Él está en luz,
experimentarán la sangre de Cristo que limpia y lava de todo pecado e injusticia;
y estos a medida que sienten esta obra realizada dentro de ellos,
son llevados a tal conocimiento de la sangre de Cristo
que no tienen posibilidad de dudar de ella,
ni tienen ocasión de preguntar dónde está, o qué es, ni cuál es su eficacia.
Porque al tener la obra y la experiencia de Su sangre en ellos,
esto resuelve todas las dudas que podrían surgir.

De la misma manera,
aquellos que llegan a experimentar la Luz como su guía en todas las cosas,
para sacarlos de la oscuridad, del pecado y de las imperfecciones,
y para llevarlos hacia la conducta inocente y sin mancha que corresponde a los santos,
y llegan a experimentar sus pasos dirigidos ante el Señor,
entonces estos ya no dudan ni cuestionan la posibilidad de alcanzar la
perfección. Porque estos ven que aquello que es perfecto ha venido,
y ellos, por la creencia que tienen de alcanzarlo,
están trabajando para conformarse a esa regla.
Estos lo buscan, no como los profesantes carnales del cristianismo,
que dicen que trabajan para conquistar sus pecados,
aunque mantienen la creencia de que nunca lo lograrán mientras vivan.
No, estos corren para alcanzar el premio, y estos tienen la verdadera esperanza en ellos,
la que los purifica así como Él es puro.
Porque Juan dijo, "`Todo aquel que tiene esta esperanza en Él, se purifica a sí mismo,
así como él también es puro,`" para que "`como Él es,
así nosotros seamos en este mundo.`"
Aquí la sustancia vendrá, y causará que las sombras se vayan,
y responderá todas sus dudas y preguntas mucho más
allá de lo que los argumentos pueden hacer.

Y de nuevo,
las muchas dudas y disputas que se han levantado con respecto a la resurrección,
serán silenciadas a medida que ustedes llegan a ser fieles en la cruz diaria,
que sí destruye y crucifica esa naturaleza en ustedes que ha resistido la verdad,
y que ha retenido a la Simiente en servidumbre.
A medida que eso llegue a morir y a ser enterrado por medio
del verdadero bautismo en la muerte de Cristo,
ustedes sentirán la Simiente pura brotar en ustedes,
y serán hechos partícipes de la nueva vida y la verdadera resurrección que está en Cristo.
Todos los que están en Él están en la resurrección y en la vida; porque Él dijo:
"`Yo soy la resurrección y la vida.
El que cree en mí, aunque esté muerto,
vivirá.`" Y todos los que viven para Dios en el espíritu de Su Hijo,
tienen parte en la primera resurrección,
y la segunda muerte no tiene potestad sobre ellos.

Estos llegan a experimentar la cosa tal como es en Jesús,
y también a sentir todas sus dudas al respecto respondidas;
porque aquel que conoce una muerte y una resurrección de esta manera - a saber,
estar muerto para el pecado y resucitado con Cristo en la nueva vida,
aun cuando todavía están en este tabernáculo terrenal,
antes de que este sea disuelto-- nunca cuestionará su comparecencia
ante el tribunal de Dios después de que su cuerpo sea disuelto.
Sí, este cree con gozo y alegría,
y tiene una esperanza ferviente en la resurrección de los muertos,
y tiene en este asunto sus expectativas en Dios,
que Él (de acuerdo con su promesa) los resucitará en el último día,
y dará a cada semilla su propio cuerpo, según Su voluntad.
La criatura no está preocupada con preguntas y dudas necias sobre esto,
como para inquirir qué tipo de cuerpo Dios va a darles,
sino que lo deja en manos del Señor con plena fe
de que Él los resucitará de acuerdo a las Escrituras.
Entonces aquí todas las dudas se van y son respondidas
con aquello que era antes de ellas,
a medida que esto llega a reinar en la criatura,
y de esta forma la muerte (la cual es la raíz y fundamento
de las dudas) llega a ser sorbida en la victoria de la vida.

A medida que ustedes sientan su parte en esta resurrección,
todas las dudas y los temores de su propia condición serán respondidos eficazmente,
que no pueden ser respondidos de otra manera excepto
por ese Espíritu de Dios que lucha con ustedes.
Cuando Él prevalece en ustedes, y ustedes llegan a someterse a Él,
testificará a favor de ustedes,
pero también les enseñará por la experiencia diaria (mucho para
su dolor) que hay un estado en el cual hay un peligro de caer.
Porque Cristo dijo,
"`Todo pámpano que en Mí no lleva fruto debe ser cortado;`" y además de esto
hay muchos ejemplos en las Escrituras de aquellos que se alejaron de la fe,
e hicieron un naufragio de ella, y volvieron como el perro a su vómito,
y como la puerca lavada a revolcarse en el cieno.
Sí, ustedes verán que, si permanecen, es por fe, y por tanto deben prestar atención,
para que puedan llegar a la corona, sello y seguridad,
y a un establecimiento en el reino, de donde ustedes no saldrán más,
sino que recibirán el deseo de sus almas.

Cuando ustedes lleguen a conocer este estado,
y a recibir la piedra blanca que tiene el nuevo nombre adentro,
entonces estarán sin ninguna duda o temor entregados a la voluntad de Dios,
para hacer y sufrir todas las cosas de acuerdo a Su bendita voluntad.
Este es el reposo verdadero y perfecto para sus almas, quienquiera que ustedes sean,
que ahora están esforzándose en el horno de hierro de sus propios pensamientos y dudas,
pero mientras más se entreguen a sí mismos a estos pensamientos y dudas,
más oscuros serán, e incluso más llenos de dudas,
porque ellos engendran y se multiplican el uno al otro.
Entre más razonen en contra de obedecer al Testigo de Dios en sus corazones,
menos capaces serán de obedecerlo.
La pequeña fortaleza que Dios les da, ustedes la cuestionan hasta anularla, y entonces,
cuando desean ser fuertes, se vuelven débiles, y cuando desean obedecer en alguna medida,
sus propios cuestionamientos se interponen y los estorban.
Y mientras más ustedes aumenten en conocimiento en este estado,
más aumentan en dolor y condenación,
tanto que a veces están a punto de desear nunca haber sabido tanta Verdad.
Y algunas veces desean saber más acerca de tal punto, o una doctrina particular,
o de la escritura, o del misterio,
y son propensos a pensar que porque ustedes todavía
son ignorantes de algunas cosas de la Verdad,
son más excusables si son desobedientes.

Pero ¡ay! pobre alma, considera esto: La manera de conocer más,
es ser obediente en lo poco que has recibido;
y entonces esa neblina y bruma de tu propia infidelidad
se desvanecerá ante el ojo de tu mente.
Esto es lo que mantiene las buenas cosas lejos de ti,
y que te hace andar diariamente con una carga sobre tus hombros,
y con una culpa sobre tu consciencia;
y que también evita que puedas venir ante el Señor con el rostro descubierto,
porque todavía estás cubierto con tus propias iniquidades.
En este estado no conoces ni el día de reposo, ni la luna nueva,
ni el día santo del Señor, sino que todo es labor, esfuerzo y fastidio de espíritu,
hasta que muchos llegan incluso a desear un fin a sus días,
y sin embargo temen que el fin sea peor.

¡Oh! cómo mi alma se compadece de ustedes cuya condición es como esta,
siento una gran solidaridad por sus dolores.
Desde las entrañas del más tierno amor soy llevado a extenderles una mano para ayudarlos,
como uno que ha obtenido misericordia para experimentar libertad,
para testificar del camino hacia ella, y tengo el testimonio de Dios en mi corazón,
para testificar de la venida del Salvador a las almas pobres y necesitadas,
para su alivio y consuelo.
El deseo de mi alma es que sus cadenas sean quebrantadas y que sus almas escapen.

Pero digo esto en el nombre del Señor a todos ustedes:
no hay otro camino para su libertad,
excepto entregarse en simple obediencia a ese Testigo fiel y verdadero de Dios,
que se agita y se mueve en ustedes en contra de sus pecados.
Por lo tanto, esperen sentir su mente y voluntad sujetadas a este,
para que puedan sentir que son los que "`se ofrecen
voluntariamente en el día de Su poder.`"
Cesen sus razonamientos en contra de la obediencia a la verdad, y de decir "`no puedo,
me falta poder;`" o "`cuando Dios me dé gracia, entonces obedeceré;`" etc.,
porque estos dichos son en vano.
Porque,
aunque es verdad que nadie puede obedecer al Señor
excepto por medio de su gracia y poder dados a ellos,
sin embargo,
Él ha hecho que Su gracia--aquella gracia que trae
salvación--se manifieste a todos los hombres,
como es dicho en Tito 2:11. Y esta gracia se ha manifestado a ustedes, y en ustedes,
a quienes escribo, y es una que reprende dentro de ustedes.
Ustedes deben volverse hacia aquello que los golpea,
y entonces se han vuelto a la gracia de Dios.

Esta es Su gracia,
la que lucha contra ustedes para guiarlos fuera del mal que ella reprueba en ustedes,
y de esta manera sacarlos del mundo que está en el mal,
hacia Dios de donde viene la gracia.
Porque cualquiera que se entregue a las atracciones
del buen Espíritu de Dios que se mueve en él,
y en obediencia a Él, se niega a sí mismo de su propia voluntad,
de malos deseos y placeres, a estos, no les falta poder,
sino más bien sienten cerca de ellos a Aquel que obra primero el querer,
y luego el hacer según su buena voluntad,
y así la gloria llega a ser sólo de Él. Entonces
ustedes conocerán el misterio de la cruz,
y cómo es el poder de Dios,
y la razón por la que todos los que la rechazan también
se quejan de que carecen de poder.
Por lo tanto, mientras que ustedes vivan en la cruz, viven en el poder,
y su obediencia es fácil, y todas las cosas les son posibles, por medio de ella.
Y mientras que ustedes estén muriendo diariamente a aquello que es corruptible,
sentirán más vida, gozo y placer en aquello que es eterno,
y sus deseos crecerán cada vez más fervientes por
un completo y perfecto disfrute de ello,
en la unidad pura del Espíritu.
Y conforme estos buenos deseos se hacen fuertes en ustedes,
se convierte en algo mucho más ligero separarse de todo lo que estorba,
aunque sean sus pecados preferidos, sus "`Dalilas`" y cosas preciosas; aun así,
todos deben irse por el amor que ustedes tienen por la Verdad.

Sólo aquellos que tienen este amor, y continúan en él,
son contados dignos de ser herederos del reino de Dios.
Porque si el Señor manifestara Su amor por ustedes,
mientras que algo fuera de Él es amado y abrazado,
ustedes prostituirían y abusarían de Su misericordia,
y se aferrarían a sus viejos amores, como el Israel de antaño.

Por lo tanto, no piensen que es extraño ser llevado a través de muchas pruebas,
para que en ellas ustedes puedan ser limpiados y
preparados como una novia para el verdadero esposo,
Cristo Jesús. Hay muchos que desean tener una relación con Él,
pero que no están preparados para Él, porque deben ser lavados primero, y adornados,
y tienen que quitarse las vestiduras viles primero,
y deben llegar a sentir el lino blanco puesto sobre ellos.
Mientras esta obra está en proceso ¡cuánta necesidad hay de paciencia y quietud de espíritu!
Cuánta necesidad de sujeción a las operaciones del Espíritu Santo en todas las cosas,
para que ustedes no pongan límites a aquello que los debe limitar en todas las cosas!
Y tampoco deben decir en sus corazones, "`Si mis pruebas fueran así,
o mis ejercicios fueran de esta o esta otra manera, yo los podría soportar.`"
Más bien, en todas las cosas sométanse voluntariamente a hacer y sufrir,
a ser probados y ejercitados,
como al Señor le agrade ordenar o permitir que ustedes sean probados.
En todos sus tratos digan con el buen hombre: "`Es el Señor,
que haga lo que bien le parezca.`"

Cualquiera que se dé a Él, aunque Él los mate, aun así,
ellos vivirán. Aunque Él los hiera, aun así, Él los sanará otra vez.
Por lo tanto, aprendan paciencia y quietud de mente, porque por mucho que se afanen,
ustedes no pueden añadir nada a esta obra.
Recuerden al Israel antiguo,
quienes fueron ordenados a estar quietos y ver la
salvación de Dios en sus pruebas más grandes,
y ellos son una figura para ustedes.
Ahora, en la Luz, lean esta figura,
y esperen la sustancia--la verdadera Semilla--para
que ella traiga paz y reposo a sus almas inmortales,
y establezca la justicia en la tierra de su corazón. Por esto me esfuerzo,
en nombre de todas las almas angustiadas y afligidas en todas partes,
para quienes yo soy un amigo y uno que les desea el bien,
como uno que conoce sus pruebas, aprietos, dudas y aflicciones.

Y también, por medio del abundante amor de Dios en Cristo Jesús,
yo testifico de la vida que liberta, contesta y satisface,
hecha manifiesta y revelada en su propia Luz eterna, que ilumina a todo hombre.
En un verdadero deseo de que todos ustedes conozcan lo mismo,
y en cumplimiento de mi deber hacia Dios y mi generación,
he enviado esta palabra de consejo y exhortación, y permanezco en mi reposo con el Señor,
siendo así completamente absuelto de la sangre de todos los hombres,
ya sea que la reciban o la resistan.
Y aunque estoy en cadenas por causa del evangelio,
soy un hombre libre en el Señor esperando en paciencia
y completa seguridad por la redención plena de Sion.

Conocido por el nombre de,

Stephen Crisp

Desde la Cárcel de Ipswich County, el Tercer mes de 1668.
