== Un Camino Simple / Abierto para los de Corazón Sencillo

[.heading-continuation-blurb]
Para responder a las dudas y objeciones que se levantan
en contra de la luz y verdad de Cristo en lo íntimo;
a causa de las cuales muchos se han desviado del camino de la obediencia,
y así han perdido la paz que Dios ofrece a sus almas anhelantes.

[.salutation]
Amigos y pueblo,

Siento un profundo ejercicio en mi espíritu por muchos que han llegado
a sentir algo bueno despertándose y moviéndose en sus corazones,
llevándolos a considerar seriamente el curso de sus vidas
y la verdadera condición interna de sus almas inmortales.

En los momentos en que ustedes han comenzado a volver
sus mentes a esta cosa buena que se ha despertado en ustedes,
muchas dudas y objeciones se han levantado en sus corazones, no sea que fueran desviados,
engañados o descarriados; o no sea que esta cosa,
que contendía internamente contra ustedes,
los llevara al camino erróneo de los Cuáqueros, como los maestros del mundo lo llaman.
Los Cuáqueros hablan y escriben,
y dan testimonio constantemente de algo (el Espíritu de la Verdad) que está en el hombre,
que lo llama a arrepentirse y a volverse al Señor. Pero debido
a que han escuchado y pensado cosas malas de este pueblo,
por la misma razón, son propensos a pensar mal de eso que obra en sus propios pechos,
lo cual tiene como fin sacarlos del pecado y de la iniquidad.
Así son tentados a despreciarlo, y a buscar un nombre con que criticarlo y llamarlo,
de los que los ministros del anticristo tienen muchos que ofrecerles;
como una luz natural, un don común del Espíritu, pero no un don que salva;
la convicción de la conciencia natural, obras de la ley; sí,
y muchos lo llaman una obra del diablo que perturba al alma de su paz, y algunos,
una luz diabólica, etc.

Y así,
cuando ustedes son llevados a despreciar ese buen Espíritu que contiende contra ustedes
(utilizando alguno de estos nombres) encuentran alivio nuevamente por un corto tiempo,
y se toman libertad de actuar en contra de Él,
y de hacer y decir lo que este Espíritu condena en lo secreto.
Pero luego este Espíritu se vuelve a levantar, y quebranta su paz,
y trae tribulación y angustia sobre sus almas.
Entonces se levantan muchas dudas por un lado y muchas dudas por el otro,
y sus pobres almas se ven acosadas y rodeadas de dudas, temores y desconfianza.

En algunos momentos temen estar resistiéndose a
la Verdad y por ende causándose su propia destrucción;
y en otros momentos temen que sea una mentira, y que serán engañados.
Además de esto,
encuentran a muchos eruditos y sabios del mundo que les
dicen que no hay nada bueno dentro de ustedes.

Aquí ustedes están en gran angustia,
luchando y sufriendo bajo muchos pensamientos dolorosos,
y muchos razonamientos confusos se levantan en sus mentes.
La carne ahora batalla fuertemente contra lo que viene a perturbarla,
y el Espíritu batalla fuertemente contra lo que lo resiste y se rebela.
Estos dos se oponen entre sí, y estas dos cosas contrarias están ambas en ustedes;
y ustedes, pobres criaturas, deben sentir la lucha entre ambos; y debido a sus tinieblas,
dudas, y temores,
es difícil saber (por lo menos con certeza) cuál de los dos es el correcto.
En este estado y condición ¿cuán aceptable sería un mensajero, muy escogido,
que les mostrara lo que puede librar sus almas de descender al sepulcro,
y salvar sus vidas del destructor?
(Job 33:23-24). Y en verdad muchos en estos días están en esta difícil condición;
por cuyo bien muchas veces he sido llevado a un profundo ejercicio, de día y de noche;
y mi clamor a Dios es que Su poder glorioso se levante más y más para
que abra esas puertas que están cerradas y selladas sobre éstos,
y saque a los espíritus encarcelados fuera de la prisión,
y fuera de la esclavitud de este Egipto espiritual,
donde nuestro Señor fue y es crucificado espiritualmente;
que Él disipe las nubes de tinieblas, en las que se levantan los temores,
las dudas y los razonamientos;
y que Él despeje el camino en todos ellos para que Su Luz resplandezca de las tinieblas,
en la cual se levanta la respuesta a todas esas dudas y preguntas.

Y por el mismo Espíritu que contiende con ustedes, soy movido a enviarles esto a todos,
como una palabra de exhortación y consejo, en el nombre y temor del Señor Dios,
por la cual todos los que la reciban de manera correcta,
y la usen y la prueben verdaderamente, hallarán ayuda y beneficio,
y experimentarán la boca del interrogador cerrada,
y la recompensa de paz dando testimonio a sus almas inmortales,
en el debido tiempo del Señor.

Por lo tanto, consideren esto: todo don bueno y perfecto viene de arriba,
del Padre de las luces y de los espíritus, el cual no quiere la muerte del pecador,
sino más bien que se vuelva y viva.
Por lo tanto,
por Su infinito amor y Su gran misericordia para con los hijos de los hombres,
Él ha preparado un camino para acercarse a ellos,
aun cuando ellos todavía están en sus pecados,
lo cual Él hace únicamente por medio de Jesucristo, el Mediador del nuevo pacto,
a quien Él ha dado gratuitamente para que sea una luz para el mundo oscuro,
y para que alumbre a todo hombre que viene al mundo, Juan 1:9.^
footnote:[Reina Valera de Gómez]
Todos ustedes están incluidos aquí, quienesquiera que sean;
ustedes han sido alumbrados por Cristo, aunque todavía sean tinieblas en sí mismos,
como los efesios una vez lo fueron.
Aún así, la luz resplandece en sus tinieblas,
o de lo contrario no habría dos naturalezas o semillas contrarias
obrando en sus corazones como lo están ahora;
y esta luz con la que son iluminados, es la vida de Jesús, Juan 1:4,
la cual Él ha dado en rescate por el hombre.
Esto no es algo natural,^
footnote:[Es decir, no forma parte del hombre o de la mente natural.]
como algunos tontamente lo imaginan: porque si fuera algo natural,
no podría darse para rescatar al hombre del pecado.

Sugerir que tanto el pecado como eso que lo reprueba son naturales,
es contrario a la enseñanza del apóstol,
quien dijo que las dos cosas que luchan en la criatura son contrarias;
y llamó a una carne, o natural; y al otra Espíritu, o espiritual.
Cristo Jesús llamó "`Espíritu de Verdad`" a eso que debía reprender al mundo de pecado;
pero el anticristo y sus ministros lo llaman natural, o una luz insuficiente, etc.
Pero sepan esto, ustedes que están indagando,
que eso dentro de ustedes que pone en evidencia las cosas que son reprobables,
es la luz con la cual Cristo los ha alumbrado,
como dijo el apóstol de Cristo en su epístola a los Efesios, capítulo 5 versículo 13,
"`Pero todas las cosas que son reprobadas, son hechas manifiestas por la luz,
porque lo que manifiesta todo, es la luz.`"^
footnote:[Reina Valera de Gómez]
Eso que los lleva a hacer o decir cosas por las que ustedes son reprobados secretamente
en sus propias conciencias es las tinieblas y el enemigo de la paz de sus almas,
y cualquiera que ande en estas tinieblas, no sabe a dónde va.
Estas tinieblas les ministran un tipo de paz,
de placer y de deleite a sus mentes carnales por un tiempo; sin embargo la otra, a saber,
la luz, la que reprueba, tiene poder para quitarles la paz otra vez, para juzgarlos,
y para hacer que aquello que era dulce para ustedes se vuelva amargo; y ni las tinieblas,
ni las concupiscencias, ni la vanidad de sus mentes puede librarlos de este golpe.

Ahora, para que puedan determinar qué hacer en este estado, consideren,
ustedes que han tenido estas luchas en su interior con respecto a la luz en sus conciencias,
si es verdadera o no, o si la van recibir o no,
y están considerando en sus corazones qué es lo mejor que pueden hacer,
si continuar endurecidos contra ella, o someterse a ella: Yo les digo, consideren,
si ustedes se rebelan contra ella, nunca sabrán a dónde los llevaría;
como fue dicho en el tiempo antiguo, Job 24:13, "`Los que se rebelan a la luz,
no conocen sus caminos.`"

De modo que, si escogen el camino de la rebelión,
eso solo incrementará su ignorancia del camino al que la luz guía,
y hará que ella sea más terrible para ustedes cada vez que aparezca en sus corazones,
hasta que lleguen a este estado del que se habló en Job 24:17,
que "`la mañana será como sombra de muerte.`"
Mientras más se rebelen contra la luz, más oscuros se volverán diariamente,
y por lo tanto menos capaces serán de llegar a una conclusión
correcta en esas cosas confusas que llenan sus mentes,
sino que a medida que las tinieblas se incrementen en ustedes,
el poder de ellas los atará como con una cadena,
y ahogará todo buen deseo en sus corazones.

Y así, por ser rebeldes a la luz, algunos hombres dejan de sentirla y experimentarla,
y llegan a "`perder toda sensibilidad`"^
footnote:[Efesios 4:19]
y a ser ajenos a ella, aunque ella esté dentro de ellos;
porque cuando el hombre se acostumbra a pecar, deja de sentir el pecado como una carga.

Pero les escribo a ustedes que todavía no han llegado a este estado de dureza de corazón,
sino que son llevados diariamente a un sentido de la carga del pecado,
y están listos para decir,
que si tan solo estuvieran seguros de que eso que les muestra
sus pecados es la Verdad y el Camino de Dios,
lo seguirían, lo amarían y lo recibirían;
pero se mantienen distantes debido a las dudas y a los razonamientos.
De cierto les digo, que antes de que estas dudas puedan ser resueltas,
ustedes deben _probar_ esto, así como (para su propio dolor) han probado lo otro,
antes de que puedan ser realmente informados;
porque los argumentos no tendrán suficiente efecto en este caso.
Por lo tanto,
traten y prueben lo que esta luz puede hacer por ustedes cuando la obedecen,
sabiendo ya que ella tiene poder para condenarlos,
y para quebrar su paz cuando la desobedecen.

¿Por qué querrían estar siempre encerrados en la incredulidad y en las dudas,
las cuales les impiden probar la luz, de la misma manera que han probado las tinieblas,
para que así puedan cosechar el fruto de ella para salvación,
como han cosechado el fruto de las tinieblas para condenación? ¡Oh, queridos amigos!
Consideren esto: no pueden obedecer a esta luz de Cristo Jesús en sus conciencias,
si no toman una cruz cada día para sus propias voluntades, deseos y afectos,
porque la luz es contraria a estas cosas.

Aquello que los lleva a obedecer sus deseos, también los lleva a desobedecer la luz;
y aquello que los lleva a obedecer la luz, se opone a los deseos y a los afectos viles,
que están en enemistad contra la luz, y deben ser juzgados y condenados por ella.
Eso que los lleva a menospreciarla, y a llamarla con algún nombre escarnecedor,
es también un enemigo de ella, y debe ser juzgado por ella.

A medida que la luz llegue a tener dominio sobre
estas cosas en ustedes que son enemigas de ella,
entenderán que ella los guiará de manera contraria a su naturaleza corrupta;
y a medida que la sientan obrando en sus corazones,
llegarán a ser más sabios que esos maestros que la han llamado una luz natural.
Porque lo que es natural guía según lo natural,
pero lo que es espiritual guía según el Espíritu,
lo cual el apóstol dijo que era contrario a la carne y que batallaba contra ella.

Y así, al obedecer la luz,
esta objeción llegará a ser respondida mucho mejor de lo
que podrían haberlo hecho las palabras y los argumentos.
De la misma manera, si ustedes no se oponen a la luz,
sino que se entregan a ser guiados por ella, llegarán a sentir su suficiencia,
y sabrán que ella es capaz de librarlos cuando sean tentados,
como también de juzgarlos cuando hayan cedido al tentador.
Porque ustedes ya conocen que tiene poder para condenarlos cuando pecan contra ella,
pero no pueden conocer verdaderamente su suficiencia
para dar paz y para justificar hasta que la obedezcan.

De modo que,
el camino simple para responder sus dudas acerca del Espíritu de la Verdad en su interior,
_es obedecerlo y entregarse a Él._
Los que hacen el mal crecen en su odio contra Él, y Él los juzga.
Así como ellos se rehúsan a obedecer la luz, también la luz se rehusará a justificarlos,
y, por tanto, quedando bajo la justa condenación de ella, a causa de la transgresión,
comienzan a tenerle miedo.
Pero ¡ay! esto sólo demuestra que ha sido enviada por Dios, porque hace la obra de Dios,
la cual es justicia.
Porque "`justificar al malvado y condenar al justo es igual de repugnante para el Señor.`"^
footnote:[Proverbios 17:15 Reina Valera Contemporánea]
Y también lo es para Su testigo en sus propias conciencias,
el cual Dios ha puesto allí para que lleve Su testimonio con respecto a todas sus acciones,
ya sean buenas o malas.
Y ustedes mismos, quienesquiera que sean, grandes o pequeños, ricos o pobres,
profesantes o profanos, confesarán lo siguiente:
que esta luz nunca los ha condenado por eso que era bueno,
ni ha dado testimonio contra ustedes por eso de lo que no eran culpables.

Por lo tanto, todos ustedes,
que han estado angustiados y fatigados con dudas y preguntas acerca de la Verdad, vengan,
escuchen el consejo de Dios en este tiempo,
anunciado una vez más externamente a ustedes desde Su Espíritu, por uno de Sus siervos,
y atestiguado internamente por la medida de Su buen Espíritu en sus almas,
que tiene la misma voz y clamor en ustedes por obediencia
a lo que es manifestado de Dios en sus corazones.
Obedezcan a la luz, y verán diariamente más de ella,
hasta que despunte como la mañana en ustedes,
y vaya en aumento hasta que el día sea perfecto; sí,
un día de alegría y regocijo para sus pobres almas afligidas.

Levántense, ustedes que se sientan en dolor,
y ustedes que están clamando en secreto por causa de las
ataduras y cadenas que todavía están sobre ustedes.
Levántense, levántense, les digo en el nombre del Señor Dios de Sión,
quien se acerca a ustedes por medio de Su Espíritu vivificador, y escuchen Su voz,
que dice al prisionero "`Sal;`" y a los que están abatidos "`Levántense;`" y a los débiles:
"`Vístanse de fortaleza, síganme y obedézcanme.
Yo confundiré a sus oponentes y quebrantaré la fuerza de sus enemigos.
Así como he hecho por Mi pueblo, que ha dejado todo para seguirme, y me obedece,
así haré por ustedes.
Y si caminan rectamente delante de Mí, y guardan Mi pacto, como Mi pueblo lo ha hecho,
ningún poder ni fuerza del enemigo interno o externo,
será demasiado fuerte para ustedes.`"

Y cuando el Señor se ha levantado así en sus almas y ha movido a Su testigo puro,
y Su brazo se ha despertado en ustedes, y Su Luz pura ha salido; ¡oh,
qué consuelo ha sido para ustedes, y cómo muchos han visto sus dudas vanas despejadas,
de modo que ha prevalecido una convicción clara en
sus espíritus con respecto al camino de Dios!
En ese momento empezaron a determinarse a seguir al Señor en Su camino puro de santidad,
que de este modo les había sido revelado en la luz,
aunque significara la pérdida de todo,
y aunque que tuvieran que llevar su parte del gran oprobio que
yace sobre todos los que aman al Señor más que a sus vidas.
Y en ese momento sintieron un gozo secreto en sus almas,
y la Semilla del reino que había estado enterrada por mucho tiempo,
comenzó a brotar en ustedes,
en cuya Semilla sus almas sintieron algunos toques de esa vida y gozo celestiales,
que en aquel tiempo excedieron todas las cosas que este mundo podía ofrecer.

Cada vez que sientan este rocío refrescante sobre sus almas,
préstenle atención y esperen con simpleza en el sentido del mismo.
Mantengan sus ojos puestos en el gozo que ahora es
puesto delante de ustedes en Cristo Jesús,
la Simiente, porque si dejan que sus mentes vaguen,
y que sus ojos se vuelvan a lo externo,
habrá objetos en todas partes que los alejarán del Amado de sus almas,
y contaminarán sus corazones y los convertirán en un lugar
inadecuado para la morada de Aquel que es santo y puro.
Él no habitará, ni se deleitará en un templo contaminado, sino que se apartará,
como se apartó del Israel antiguo y de su templo, cuando fue contaminado y profanado.

Además,
cuando cualquier cosa corruptible de este mundo cambiante se apodere de sus mentes,
pronto se despertará un deseo, anhelo y codicia por disfrutarla,
aunque sean contrarias a la voluntad de Dios.
Luego, eso que razona y consulta se levanta en ustedes y comienza a preguntar:
"`¿No puedo disfrutar del Señor y también de esto?
¿No puedo mantenerme en el camino de la Verdad,
y aun así hacer esto o aquello que mi corazón desea?
Y aunque no esté perfectamente de acuerdo con la verdad que ha sido manifestada en mí,
aun así voy a satisfacer mi voluntad, mi codicia, mi deseo, sólo esta vez.
Y esto no es gran cosa,`" dice el razonador; "`es sólo algo pequeño,
y hay otros que hacen cosas más grandes que estas.`"

Razonamientos como estos entran a la mente,
y afligen y contristan a ese Espíritu tierno, bueno y justo que se movió en ustedes.
Estos producen un peso y una opresión sobre el Testigo puro en ustedes,
el cual se aparta nuevamente de ustedes,
y por tanto viene sobre ustedes una noche donde antes se había levantado una luz.
Porque donde sea que la serpiente consiga llevar
a alguien a poner en duda la obediencia a la verdad,
allí ella se encontrará tan lista para ofrecer una
respuesta como lo estuvo para introducir la duda.
Pero su respuesta siempre vendrá con libertad carnal,
y con una persuasión para desobedecer, como lo hizo con Eva al principio.
Y cuando el pecado es consumado, la muerte entra en ustedes con su oscuro poder,
y múltiples dolores traspasan sus pobres almas.

Aunque el fruto era codiciable, sin embargo, ahora que ha sido consumido,
no pueden acercarse a la vida para comer de ella también, aunque lo deseen;
sino que son echados y mantenidos afuera por una espada encendida,
que se mueve en toda dirección contra ustedes.

Ahora hay un fundamento puesto en ustedes para el surgimiento
de dudas y cuestionamientos de una naturaleza peor que la anterior.
Antes dudaban de la Verdad misma, si ella era la verdad o no; pero ahora,
habiéndola probado y habiendo sido convencidos por ella,
han dejado que sus mentes se alejen de ella y se vuelvan a lo externo,
en pos de otros amantes, y sus oídos se han vuelto a la voz de la adúltera,
haciendo que la luz pura se aparte de ustedes por su rebelión.

Ahora desean ver nuevamente lo que habían visto,
y sentir otra vez lo que habían sentido, pero dudan y temen que jamás verán, ni sentirán,
ni disfrutarán algo similar otra vez.

Y ahora claman,
"`Ojalá nos hubiéramos mantenido en la cruz contra
nuestra propia voluntad y negado a nosotros mismos,
para no haber perdido de esta manera la perspectiva
y el sentido del Amado de nuestras almas!`"
Y entienden por triste experiencia, de dónde se levantan las dudas,
los temores y las aflicciones, a saber,
de haberse unido al enemigo que les presenta razonamientos
en contra de su obediencia a la luz.

Ahora, por lo tanto, presten atención a eso que queda en ustedes,
aunque las tinieblas y el dolor los rodeen.
Todavía hay algo que queda, algo que les da un sentido de su estado y condición,
y los hace conocer su pérdida y su necesidad.
Escuchen la voz de esto, y los humillará,
y los llevará a un verdadero quebrantamiento de corazón y contrición de espíritu.
Y a medida que ustedes experimenten este estado de quebrantamiento,
tendrán algo que ofrecerle al Señor que es de Su propia preparación,
lo cual será mucho más aceptable para Él que una multitud de palabras,
acciones y deberes (así llamados).
Y a medida que ustedes, con verdadera humildad,
vengan ante el Señor y ofrezcan esta ofrenda,
Dios oirá en los cielos y responderá el clamor de las almas pobres
y menesterosas que no pueden ser satisfechas sin Su presencia.
Sí, Él se acordará de Sus antiguas misericordias, que nunca se acaban,
por amor a Su Semilla, la cual todavía no ha brotado en ustedes.
Y cuando Dios resplandezca otra vez en sus corazones, y revele Su poder,
deben esperar que lo haga en juicio, a causa de la transgresión en la que han caído,
para que Él consuma eso en ustedes que los llevó al pecado, y los alejó de Su ley pura,
que es luz; porque "`Sion es redimida con juicio.`"^
footnote:[Isaías 1:27 LBLA]

Por tanto,
tengan cuidado de no escandalizarse en Su aparición. Tengan cuidado de limitar al Santo,
porque si Su aparición viene con más agudeza y amargura que antes para la parte carnal,
es solo lo justo que sea así. El Señor es; que haga lo que bien le parezca.^
footnote:[1 Samuel 3:18]
Él ahora ve más motivos que antes para actuar así,
debido a que han pecado mucho más contra Su bondad.
Pero sométanse a Sus juicios, soporten Su ira, porque han pecado contra Él,
Miqueas 7:9. Y a medida que se entreguen a Sus justos juicios,
experimentarán Su venida en medio de ellos,
en la cual se recuerda y se manifiesta la misericordia.
Por lo tanto, los apurados e impacientes,
que huyen del juicio tan pronto como comienza a aparecer un poco en ellos,
nunca experimentarán una verdadera liberación, sino que consiguen alivio de otra manera,
el cual dura sólo por un momento.

Pero los que llegan a experimentar la obra completa realizada en su tierra,
y la era totalmente purificada,
también experimentarán la paz verdadera y duradera de sus almas inmortales.
Y aunque esto no se obtiene con alivio y libertad
para la mente carnal (la cual debe morir),
sin embargo, los que perseveren hasta el fin recibirán la corona;
estos son los que serán salvos,
como Cristo dijo en Marcos 13:13. Estos se hallarán volviendo con gavillas,
como dijo el profeta en Salmos 126:5-6: "`Los que sembraron con lágrimas,
con regocijo segarán. Irá andando y llorando el que lleva la preciosa semilla;
más volverá a venir con regocijo, trayendo sus gavillas.`"
Y como Cristo dijo: "`Cualquiera que haya dejado casas, o hermanos, o hermanas, o padre,
o madre, o mujer, o hijos, o tierras, por mi nombre, recibirá cien veces más,
y heredará la vida eterna.`"^
footnote:[Mateo 19:29]

Dejar todo y negarse a sí mismo siempre ha sido
el camino a la vida y a la verdadera bendición,
y continúa siendo el camino hasta este día. Por lo tanto,
todos ustedes que han andado errantes en sus propios caminos,
y aún no han aprendido a negarse a sí mismos de aquello
que es contrario al testigo de Dios en sus corazones,
sino que tienen deseos (y unos muy fuertes también)
de mantener y retener lo que la luz reprueba en ustedes,
y sin embargo tienen deseos de alcanzar la vida y la paz también,
y por lo tanto están en muchas dudas y aprietos con respecto a estas cosas;
para todos ustedes, este es el consejo del Señor y el clamor de Su Espíritu puro:
Salgan de la confusión babilónica de sus propios pensamientos, y no toquen lo inmundo,
y el Señor los recibirá.^
footnote:[2 Corintios 6:17; Isaías 52:11]
Lo que Dios por Su Espíritu puro ha llamado inmundo,
que ningún hombre presuma llamarlo limpio, ni se una a ello,
no sea que sea hallado luchando contra Dios,
y nutriendo y manteniendo vivo lo que Dios ha sentenciado
a muerte y destrucción. Ustedes no pueden servir a dos señores,
ni participar de la mesa del Señor, y de la mesa de los demonios.

¡Oh, no alimenten ese nacimiento que tiene hambre de cosas malas,
y que se deleita en ellas!
Más bien, lo que ha sido sentenciado a morir de hambre, que muera de hambre;
y lo que a la espada,
que lo corte la espada de dos filos que sale de la boca del Testigo fiel y verdadero,
Apocalipsis 1:16 y 3:14. De modo que puedan ver a los gigantes en la tierra
heridos delante de ustedes por Aquel que es poderoso para liberarlos,
y para sacarlos de este Egipto espiritual con mano fuerte.
Ustedes no podrán experimentar esto, excepto al seguir al Señor diligentemente;
y si se entregan voluntariamente a Sus dulces invitaciones
e inclinaciones cuando las sientan en su corazón,
hallarán que son eficaces y provechosas para sus almas.
Y cuanto más sigan al Señor,
más sentirán Su bondad irrumpiendo sobre ustedes para darles ánimo,
y menos dudarán de Su amor y misericordia al llevarlos aún más lejos,
incluso hasta el fin, a saber, a ese reposo que satisfará sus almas.

Por lo tanto,
dejen de lado todas las dudas y razonamientos que van en
contra de su obediencia al don de Dios en su corazón,
el cual reprueba el pecado en ustedes y no le da lugar a
las dudas vanas e innecesarias respecto a ella.
Y tal como ustedes han sido condenados y juzgados por su desobediencia a este don,
ahora intenten y prueben si tomando su cruz diaria,
y obedeciéndolo en sus palabras y acciones, y en todas las cosas,
no encontrarán la recompensa de dulce paz y gozo.
Y cuando descubras que es así,
entonces ya no habrá más lugar para las dudas y los razonamientos contra su obediencia;
sino que,
a medida que cualquier pregunta o duda se levante internamente
(o sea puesta en su camino por alguien externamente),
sentirán la recompensa de paz en sus propios corazones para su gran refrigerio.
De esta manera,
llegarán a experimentar diariamente en sus almas la operación eficaz de este don,
obrando su transformación,
y trasladándolos fuera de sí mismos e introduciéndolos en Su propia naturaleza.
Y así llegarán a saber no sólo que la luz está en ustedes,
sino también que ustedes están en la luz,
y que andan en ella con Dios en la comunión santa,
en la que sienten que el Señor está cerca de ustedes en Su luz,
y que Su recompensa está con Él. Porque un hombre
puede saber que la luz está en él y aún así perecer,
porque Cristo dijo que ésta es la condenación: que la luz ha venido, pero no es amada.
Pero ustedes, al amar la luz, llegarán a caminar y a morar en ella.
Así su ciudadanía estará en los cielos, como la de los santos en el tiempo antiguo,
y experimentarán una comunión con el Padre y con el Hijo, como la de ellos que dijeron:
"`Si andamos en luz, como Él está en luz, tenemos comunión con Él,`"^
footnote:[1 Juan 1:7]
y si algunos decían que tenían comunión con Él,
y sin embargo andaban en tinieblas (que es lo que todos los pecadores hacen,
porque el pecado es la obra de las tinieblas), los tales se consideraban mentirosos.

Los que anden en luz, como Él está en luz,
experimentarán la sangre de Cristo que limpia y lava de todo pecado y maldad.
Y a medida que sientan esta obra realizándose en ellos,
serán llevados a tal conocimiento de la sangre de Cristo, que no podrán dudar de ella,
ni tendrán ninguna ocasión de preguntar dónde está, qué es, o cuál es su eficacia.
Porque al tener la obra y la experiencia de Su sangre en ellos,
esto rápidamente resolverá todas las dudas que pudieran surgir.

De la misma manera,
los que llegan a experimentar la luz en todas las cosas como su guía,
que viene a sacarlos de las tinieblas, del pecado y de la imperfección,
y a llevarlos a una conducta inocente e irreprensible (como corresponde
a los santos) y por lo tanto sienten que sus pasos son dirigidos
por el Señor--éstos han puesto fin a toda duda y razonamiento respecto
a la perfección. Porque éstos ven que lo perfecto ha venido,
y ellos, por la creencia que tienen de alcanzarlo,
están esforzándose por conformarse a su regla.
Estos lo buscan, no como los profesantes carnales del cristianismo,
que dicen que se esfuerzan por vencer sus pecados,
y al mismo tiempo mantienen la creencia de que nunca lo lograrán mientras vivan.
No, éstos corren para obtener el premio, y tienen la verdadera esperanza en ellos,
que los purifica así como Él es puro.
Porque Juan escribió, "`Todo aquel que tiene esta esperanza en Él,
se purifica a sí mismo, así como Él también es puro,`"^
footnote:[1 Juan 3:3]
para que "`como Él es, así nosotros seamos en este mundo.`"^
footnote:[1 Juan 4:17]
Aquí la sustancia vendrá, y hará que las sombras se vayan,
y responderá todas sus dudas y preguntas de una forma
muy superior a lo que los argumentos pueden hacer.

Y de nuevo,
las muchas dudas y razonamientos que se han levantado con respecto a la resurrección,
serán silenciadas a medida que ustedes sean fieles en la cruz diaria que
mata y crucifica esa naturaleza en ustedes que ha resistido la Verdad,
y ha mantenido el alma en esclavitud.
A medida que esta naturaleza muere,
y es enterrada por el verdadero bautismo en la muerte de Cristo,
sentirán la Semilla pura brotar en sus corazones,
y serán hechos partícipes de la nueva vida y de la verdadera resurrección,
la cual es Cristo.
Todos los que están en Él, están en la resurrección, y en la vida; porque Él dijo:
"`Yo soy la resurrección y la vida; el que cree en mí, aunque esté muerto, vivirá.`"^
footnote:[Juan 11:25]
Y todos los que viven para Dios, en el Espíritu de Su Hijo,
tienen parte en la primera resurrección; la segunda muerte no tiene potestad sobre ellos.

Estos llegan a experimentar la sustancia conforme está en Jesús,
y todas sus dudas respecto a esto son respondidas también;
porque aquellos que experimentan una muerte y una
resurrección de acuerdo a esta manera--a saber,
estar muerto al pecado y haber resucitado con Cristo en vida nueva,
aun cuando todavía están en este tabernáculo terrenal,
antes de deshacerse--nunca dudarán de su comparecencia ante
el tribunal de Dios después de la muerte del cuerpo.
Sí, estas personas creen con gozo y alegría,
y tienen una esperanza ferviente en la resurrección de los muertos,
y sus expectativas con respecto a este asunto están puestas en Dios,
de que Él (según Su promesa) los resucitará en el día postrero,
y dará a cada semilla su propio cuerpo, como Él quiera.
Estas personas no se preocupan por preguntas y dudas tan necias,
como para ponerse a investigar qué tipo de cuerpo Dios les dará,
sino que lo dejan en manos del Señor con plena fe
de que Él los resucitará de acuerdo a las Escrituras.
De modo que aquí todas las dudas se irán,
y serán respondidas por eso que era antes de ellas,
a medida que esto reine en la criatura;
y de esta forma la muerte (que es la raíz y fundamento
de las dudas) será sorbida en la victoria de la vida.

A medida que sientan su parte en esta resurrección,
todas las dudas y temores referentes a su propia condición serán respondidos eficazmente,
los cuales no podrían ser respondidos de otra manera,
salvo por ese buen Espíritu de Dios que contiende con ustedes.
Cuando Él prevalece en ustedes, y ustedes se someten a Él,
entonces da testimonio a favor de ustedes.
Pero también les enseñará por experiencia diaria (para su gran
dolor) que existe un estado en el que hay peligro de caer.
Porque Cristo dijo: "`Todo pámpano que en Mí no lleva fruto, será quitado;`"^
footnote:[Juan 15:2]
y además de esto hay muchos ejemplos en las Escrituras
de personas que apostataron de la fe,
y naufragaron en cuanto a ella, y se volvieron como el perro a su vómito,
y como la puerca lavada al cieno.
Sí, ustedes verán que si están firmes) es por la fe,
y por tanto deben andar con cuidado para que puedan llegar a la corona,
al sello y a la plena certidumbre, y a un establecimiento en el reino,
de donde nunca más saldrán, sino que recibirán el deseo de sus almas.

Cuando lleguen a experimentar este estado,
y a recibir la piedrecita blanca que tiene escrito en su interior un nombre nuevo,
entonces estarán entregados a la voluntad de Dios sin ninguna duda o temor,
dispuestos a hacer y sufrir todas las cosas de acuerdo a Su bendita voluntad.
Y es aquí donde se encuentra el reposo verdadero y perfecto de sus almas,
quienesquiera que sean ustedes que ahora se encuentran luchando y sufriendo
en el horno de hierro de sus propios pensamientos y dudas.
Pero mientras más se entreguen a estos pensamientos y dudas, más oscuros se volverán,
y aún más llenos de dudas estarán,
pues estos se engendran y se multiplican unos con otros.
Cuanto más razonen contra su deber de obedecer al testigo de Dios en sus corazones,
menos capaces serán de obedecerlo.
La pequeña fuerza que Dios les da, se desvanece cuando se ponen a razonar, y luego,
cuando desean ser fuertes, se vuelven débiles, y cuando desean obedecer en alguna medida,
sus propios razonamientos se interponen y se los impide.
Y mientras más aumente su conocimiento en este estado,
más aumentará su dolor y condenación,
de modo que a veces estarán a punto de desear nunca haber conocido tanta Verdad.
Y algunas veces desearían saber más acerca de tal punto, o de una doctrina en particular,
o de una escritura, o de un misterio,
y son propensos a pensar que porque todavía no comprenden
algunas cosas relacionadas a la Verdad,
son por lo tanto más excusables si son desobedientes.

Pero ¡ay! pobres almas, consideren esto: el camino para conocer más,
es que sean obedientes a lo poco que han recibido;
y entonces esa neblina y oscuridad causada por su propia
infidelidad se desvanecerá ante los ojos de su entendimiento.
Esto es lo que los priva de las cosas buenas,
y lo que los hace andar diariamente con una carga sobre sus hombros,
y con una culpa sobre sus conciencias;
y también es lo que les impide que se presenten delante del Señor a cara descubierta,
porque todavía están cubiertos con sus propias iniquidades.
En este estado no experimentan ni el día de reposo, ni la luna nueva,
ni el día santo del Señor, sino que todo es labor, esfuerzo y agotamiento de espíritu,
hasta que muchos llegan incluso a desear el fin de sus días,
y sin embargo tienen gran temor de que el fin sea aún peor.

¡Oh,
cómo mi alma se compadece de ustedes que están en
está condición! He pasado por estos mismos dolores,
y por eso siento gran compasión por ustedes.
Me siento movido en mucho amor a extenderles una mano para ayudarlos,
como uno que ha obtenido misericordia para experimentar libertad,
y para dar testimonio del camino a ella.
Y tengo el testimonio de Dios en mi corazón,
que me lleva a testificar de la venida del Salvador a las almas pobres y necesitadas,
para traerles alivio y consuelo.
El deseo de mi alma es que sus cadenas sean quebrantadas, y que sus almas escapen.

Pero les digo esto en el nombre del Señor a todos ustedes:
no hay otro camino para obtener su libertad,
excepto entregándose en plena obediencia a ese Testigo fiel y verdadero de Dios,
que se agita y se mueve en ustedes contra sus pecados.
Por lo tanto,
esperen hasta que sientan que su mente y voluntad se sujetan a este Testigo,
para que se encuentren dispuestos a ofrecerse voluntariamente en este día de Su poder.^
footnote:[Salmos 110:3]
Dejen de razonar contra la obediencia a la Verdad, y de decir "`no puedo,
me falta poder;`" o "`cuando Dios me dé gracia, entonces obedeceré;`" etc.,
porque estos dichos son en vano.
Pues aunque es cierto que nadie puede obedecer al Señor
salvo por medio de la gracia y poder que Dios le haya dado,
sin embargo,
Él ha hecho que Su gracia--esa "`gracia que trae
salvación`"--se manifieste a todos los hombres,
como es dicho en Tito 2:11. Y esta gracia se ha manifestado a ustedes, y en ustedes,
a quienes escribo, y es eso que los reprende en sus corazones.
Ustedes, por lo tanto, deben volverse a lo que los golpea,
y entonces se habrán vuelto a la gracia de Dios.

Es Su gracia la que contiende contra ustedes con el fin
de guiarlos fuera del mal que ella reprueba en sus corazones,
y, por lo tanto, fuera del mundo que yace en maldad, a Dios de quien ella viene.
Porque cualquiera que se entregue a las invitaciones e inclinaciones
del buen Espíritu de Dios que se mueve en él,
y en obediencia a Él se niegue a sí mismo su propia voluntad,
y sus malos deseos y placeres, a este no le faltará poder,
sino que más bien sentirá cerca de él a Aquel que produce primero el querer,
y luego el hacer, por Su buena voluntad,
y así la gloria llega a ser sólo de Él. Entonces
ustedes conocerán el misterio de la cruz,
y cómo es el poder de Dios,
y la razón por la que los que la rechazan se quejan de que carecen de poder.
Por lo tanto, mientras ustedes vivan en la cruz, vivirán en el poder,
a través del cual les será fácil obedecer, y todas las cosas les serán posibles.
Y mientras estén muriendo diariamente a eso que es corruptible, sentirán más vida,
gozo y placer en eso que es eterno,
y sus deseos crecerán más y más fervientes tras el disfrute pleno y perfecto de ello,
en la pura unidad del Espíritu.
Y conforme estos buenos deseos se vayan haciendo fuertes en ustedes,
les resultará cada vez más fácil separarse de lo que los estorba,
aunque sean sus pecados más amados, sus "`Dalilas`" y sus cosas preciadas; aun así,
todo debe irse por el amor que le tienen a la Verdad.

Sólo los que tienen este amor por la Verdad, y continúan en él,
son considerados dignos de ser herederos del reino de Dios.
Porque mientras cualquier cosa sea abrazada y amada fuera del Señor,
cuando Él les manifieste Su amor para con ustedes, ustedes fornicarán,
y abusarán de Sus misericordias, y se aferrarán a sus antiguos amantes,
como lo hizo Israel en la antigüedad.

Por lo tanto, no se sorprendan cuando sean afligidos por diversas pruebas,
para que así sean purificados y preparados como una novia para Cristo Jesús,
el verdadero esposo.
Hay muchos que desean tener una relación con Él, pero que no están preparados para Él,
porque primero deben ser lavados y adornados,
y despojarse de la vestidura vil y revestirse de lino limpio y resplandeciente.
Mientras esta obra está en proceso ¡cuánta necesidad hay de paciencia y quietud de espíritu!
¡Cuánta necesidad de sujeción a las operaciones del Espíritu Santo en todas las cosas,
para que no le estén poniendo límites a Aquel que
debe limitarlos a ustedes en todas las cosas!
Y tampoco deben decir en sus corazones: "`¡Si mis pruebas fueran así,
o mis ejercicios fueran de esta u otra manera, yo los podría soportar!`"
Más bien,
sométanse en todas las cosas con disposición a hacer y sufrir lo que al Señor le parezca,
a ser tratados y ejercitados como a Él Señor quiera ordenar o permitir.
En todos sus tratos digan con el buen hombre: "`El Señor es;
que haga lo que bien le parezca.`"^
footnote:[1 Samuel 3:18 LBLA]

Quienes se entreguen a Él de esta manera, aunque Él los mate,
vivirán. Aunque Él los hiera, aun así, Él los curará otra vez.
Por lo tanto, aprendan paciencia y quietud de mente, porque no podrán,
por mucho que se afanen, añadir nada a esta obra.
Recuerden al Israel antiguo,
a quienes se les mandó a estar quietos y ver la salvación
de Dios en sus pruebas más grandes,
y ellos son una figura para ustedes.
Lean en la luz esta figura,
y esperen la sustancia--la verdadera Semilla--para
que ella produzca paz y reposo para sus almas inmortales,
y establezca la justicia en la tierra de su corazón.
Es por esto que sufro dolores de parto,
por el bienestar de todas las almas angustiadas y afligidas en todas partes,
para quienes soy un amigo que les desea el bien, uno que ha experimentado sus pruebas,
aprietos, dudas y aflicciones.
Y también, por el abundante amor de Dios en Cristo Jesús,
he experimentado la vida que liberta, responde y satisface,
ahora manifestada y revelada en su propia luz eterna, que alumbra a todo hombre.

Con el verdadero deseo de que todos ustedes experimenten lo mismo,
y en cumplimiento de mi deber para con Dios y mi generación,
he enviado esta palabra de consejo y exhortación, y permanezco en mi reposo con el Señor,
quedando así libre de la sangre de todos los hombres,
ya sea que escuchen o dejen de escuchar.
Y aunque estoy en cadenas por causa del evangelio, soy un hombre libre en el Señor,
que espera con paciencia y plena certidumbre la redención completa de Sion.

[.signed-section-closing]
Conocido por el nombre de,

[.signed-section-signature]
Stephen Crisp

[.signed-section-context-close]
Desde la Cárcel de Ipswich County, el Tercer mes de 1668.
