== Selección del Diario de Stephen Crisp

¡Oh, todos ustedes santos y todos ustedes habitantes de la tierra,
que el nombre de Jehová sea famoso entre ustedes,
porque no hay Dios como Él! ¡Qué Sus misericordias y juicios
sean recordados y registrados de generación en generación,
pues Su bondad es infinita y Su amorosa generosidad inefable!
Y aunque ningún hombre puede relatar plenamente Su amorosa generosidad extendida a él,
aun así, que todos los hombres testifiquen de Su bondad y declaren Sus misericordias,
mediante las cuales Él está atrayendo a los hijos de los hombres a Sí mismo,
y ganando y reuniendo los esparcidos en el verdadero reposo.
Por tanto, bien dijo David: "`Traeré, pues,
a la memoria los años de la diestra del Altísimo.
Me acordaré de las obras de Jehová; sí, haré yo memoria de tus maravillas antiguas.
Meditaré en todas tus obras, y hablaré de tus hechos.`"
(Salmos 77:10-12). ¿Quién puede sentir Su bondad y participar
de Su amor y no ser constreñido a testificar de Él?

En el dulce recuerdo de Sus múltiples e innumerables misericordias, me siento abrumado.
Pues toda mi vida ha sido una serie continua de misericordia y bondad,
y en toda ella Él ha sido mi soporte.
Cuando no Lo conocía, Él estaba cerca de mí, sí; cuando me rebelaba contra Él,
Él no cesaba de ser misericordioso.
Su pacto descansaba en Su Semilla Cristo, y por Su causa Él me perdonaba.
Su longanimidad y paciencia estaban extendidas hacia mí o habría
sido cortado en los días de mi resistencia a Él. Pero sí,
yo bien puedo decir, que Él es un Dios clemente y misericordioso, magnánimo,
paciente y lleno de compasión. ¡Qué Su nombre sea
proclamado hasta los confines de la tierra,
y que los oídos de los impíos sean abiertos para que oigan el sonido de Su alabanza!

Ciertamente el Señor ha tenido un ojo de tierna compasión
hacia mí desde el día que me formó,
y me ha designado para Su alabanza y para que testifique de Su bondad.
Porque desde que puedo recordar y desde que soy capaz de entender,
Él me hizo comprender que había algo en mí que no consentía ningún mal,
algo que permanecía en mi alma como un Testigo contra todo mal.
Este me mostraba que yo no debía mentir, ni robar, ni ser terco ni desobediente,
sino que debía comportarme con mansedumbre y tranquilidad,
y además colocó la verdad delante de mí como algo mejor que la falsedad.
Este mismo Testigo, incluso en los días de mi infancia,
me ministraba paz y denuedo cuando yo escuchaba Su consejo.
Sin embargo,
había una naturaleza y semilla contrarias en mí que eran de este mundo y no de Dios.
Encontré que esa naturaleza se inclinaba hacia el mal,
y hacia el camino y la manera de este mundo malo, agradando la mente carnal,
y comenzó a abrirse en mí un ojo que veía lo que era aceptable para el hombre,
en lugar de lo que era agradable para Dios.

Como este ojo era fortalecido a diario por varios objetos y ejemplos de vanidad,
un deleite brotó en mí hacia lo que era malo y mis sentidos se ejercitaron con vanidad,
por lo que la Semilla pura era oprimida y afligida día tras día,
y comenzó a clamar contra mí. La condenación comenzó a ser agitada en mí,
entró miedo donde antes no había miedo y se perdió la inocencia pura.
Luego, cuando en algún momento yo hacía o hablaba algún mal,
la Luz divina o Semilla pura en mí me lo manifestaba,
y me mostraba que yo no debía haberlo hecho.
Yo sentía condenación y no sabía cómo escapar de ella.
Entonces el espíritu maligno que conduce a la transgresión,
estaba listo para ayudar en ese tiempo de necesidad.
A veces agitaba en mí algo sutil para que alegara una razón por lo que había hecho,
o alegara una provocación, o una buena intención, o bien,
para que negara o al menos mitigara la maldad de mi acto,
y de esa manera detener la boca del Testigo de Dios,
y viera si podía escapar de Su condenación y procurar mi propia paz.

¡Pero, ay, esa era una ayuda miserable!
Pues la luz a menudo brillaba a través de todas esas pretensiones y silenciaba mis razonamientos.
Cuando yo no era más que un niño, ella me mostró,
en un entendimiento puro procedente de Dios, que no hay una buena razón para el mal,
fueran cuales fueran las provocaciones, tentaciones y ejemplos.
Por tanto, con frecuencia era despojado de todos mi razonamientos y cubiertas,
pero luego, aprendía otra manera de aliviarme del juicio.

Cuando era muy pequeño, de unos siete u ocho años,
cada vez que el juicio me alcanzaba por mi maldad,
yo aceptaba que era verdadero y correcto, y por tanto,
concluía que debía hacer algo para agradar a Dios de nuevo.
Así fue como aprendí a orar y a llorar en secreto,
y hacer pacto con Dios de que sería más vigilante,
y por un tiempo me sentía aliviado de mi peso.
Sin embargo, esto también era acompañado de muchas dudas y cuestionamientos,
en cuanto a si mis maldades eran efectivamente borradas,
especialmente cuando veía que yo rápidamente era alcanzado por el mismo espíritu del mal,
y llevado de nuevo a los mismos malos pensamientos, palabras o actos.
Pues el Testigo de Dios en mí clamaba incluso entonces,
que toda mi mente se entregara al Señor, y que yo Le sirviera con cada pensamiento,
palabra y obra.
Yo en ese momento no sabía que ese Testigo puro era de Dios, pero lo que sí sabía era,
que carecía de poder para responder a Sus exigencias
en mí que testificaban contra el mal.
Y por eso estaba triste día y noche.

Cuanto tenía unos nueve o diez años,
busqué el poder de Dios con gran diligencia y sinceridad,
con fuertes clamores y lágrimas.
Si yo hubiera poseído el mundo entero,
lo habría regalado con tal de saber cómo obtener poder sobre mis corrupciones.
Y cuando veía el descuido de otros niños y su impureza,
y que ellos no pensaban en Dios (hasta dónde podía discernir),
ni consideraban Sus reprensiones,
aunque eran mucho más malvados que yo en su hablar y actuar: "`¡Señor,`" pensaba yo,
"`¿qué será de estos?
...viendo cuán pesada es la mano que está sobre mí,
y que no puedo encontrar ni la paz ni la seguridad de Tu amor!`"

Entonces el enemigo me tentaba a descansar y a estar tranquilo,
insistiendo en que las cosas estaban mejor en mí que en otros.
Y de hecho,
mi mente deseaba fuertemente crear una paz falsa para mí.
Pero el Testigo puro me seguía y no me dejaba solo,
persiguiéndome noche y día. Él rompía mi paz más rápido de lo que yo podía hacerla,
pues mi mente estaba en mis propias obras y no podía ver
más allá de mí. Yo oía hablar de un Cristo y Salvador,
pero yo realmente no lo conocía.

En ese tiempo yo prestaba mi oído a los muchos discursos y disputas de los tiempos,
y a través de ellas muchas ideas fueron dejadas en mi mente.
A veces escuchaba a los hombres argumentar que Dios no ve pecado en Su pueblo.
"`Entonces,`" decía yo, "`estoy seguro de que no soy uno de ellos,
porque Él claramente hace notar todas mis transgresiones.`"
En otros momentos escuchaba a los hombres hablar de la elección
y condenación de las personas antes de que el tiempo comenzara.
Yo consideraba esto con diligencia y pensaba,
que si eso era así y podía encontrar señales y marcas de haber sido un alma elegida,
eso me traería paz y no sería tan zarandeado como lo había sido.

Llegué a ser un muy diligente oyente y seguidor de
los mejores ministros (como eran reconocidos),
e iba con tanta diligencia y alegría a leer y oír los sermones,
como los otros niños iban a su juego y deportes.
Y cuando escuchaba a alguno hablar acerca del punto de la elección,
y la manera en que un hombre podía saber si era elegido,
pues (en su sabiduría oscura) ellos a menudo daban señales
de lo que era un verdadero creyente y un alma elegida,
entonces yo me probaba con la medida de ellos y me pesaba en su balanza.
Al hacerlo, algunas veces lograba reunir un poquito de paz para mí mismo,
por encontrar en mí cosas como las que ellos describían como señales,
tales como un deseo contra el pecado, aborrecimiento de mí mismo por el pecado,
amor por los que eran considerados las mejores personas,
el anhelo de ser librado del pecado, etc.

¡Pero ay, aquí todavía estaba lo ciego guiando a mi pobre alma ciega!
Esta no era la balanza del santuario, por tanto,
cuando yo lograba un poquito de paz y quietud, y deseaba sostenerla,
¡desgraciadamente pronto era hecha añicos y quebrada otra vez!
Porque cuando el Testigo puro de Dios se levantaba en mí,
por el que yo era pesado en la verdadera balanza, ¡hallaba que era demasiado liviano!
Y entonces, una angustia volvía a ser encendida en mí y un clamor empezaba a salir:
"`¡Oh, adónde iré y qué haré para poder llegar a una condición estable,
antes de irme de aquí y no ser visto más!`"

En esta infeliz condición el pensamiento de muerte producía
un temor tanto sobre el alma como sobre el cuerpo.
En realidad, a menudo se apoderaban de mí estremecimientos y horrores,
al temer que yo hubiera sido separado como una vasija de ira, y que por eso,
debía llevar el hervor de fuego de Dios para siempre.
¡Oh, esa palabra __siempre__ con frecuencia me parecía terrible,
pero no sabía cómo evitar esto!

En este momento empecé a percibir más claramente
mi propia insuficiencia y falta de poder,
pues vi que no estaba en mis manos evitar el pecado.
Yo sabía que la paga del pecado es muerte, por lo que llegué a una gran crisis;
a veces pensaba que era mejor abandonar la búsqueda, y otras, que si tenía que perecer,
mejor perecía buscando.
Cuando era así, lo bueno obtenía la ventaja por un tiempo, y entonces buscaba,
oraba y gemía diligentemente,
y con frecuencia encontraba los más recónditos campos e inusuales parajes,
y ahí derramaba mis quejas al Señor.

Cuando tenía cerca de doce años mi clamor general y constante era por poder,
mediante el cual yo pudiera vencer las corrupciones.
Y aunque yo oía a los maestros de aquellos tiempos
decir a diario que nadie podía vivir sin pecado,
y que la doctrina de la perfección era considerada un error peligroso,
eso no disminuía mi clamor (aunque ciertamente debilitaba mi creencia de obtenerlo,
y hacía que a mis oraciones les faltara fe y no tuvieran éxito).
Pues yo sabía que sin el poder de Dios perecería, dijeran lo que dijeran ellos,
y que yo no podía considerarme salvo,
mientras siguiera siendo cautivo de la naturaleza corrupta y rebelde.
Yo recordaba las palabras de Cristo: "`Todo aquel que hace pecado,
esclavo es del pecado,`" y de hecho, yo sabía que lo era.

En este horno de hierro yo me afanaba y me esforzaba arduamente,
y nadie sabía de mis tristezas y gemidos, que a veces eran casi intolerables.
De hecho, a menudo deseaba no haber nacido,
o que mi fin fuera como el de las bestias del campo,
pues yo las consideraba felices por no tener una lucha tan amarga como la que yo tenía,
ni teníannque soportar lo que temía que sería mi
porción en el más allá. Yo veía mi miseria claramente,
pero no veía la manera de escapar de ella.

Entonces pensé que sería mejor no guardar mi miseria para mí mismo,
sino descubrirla a algunos que fueran capaces de ayudarme.
Pero en verdad puedo decir, que encontré que todos ellos eran míseros consoladores,
pues me aconsejaron que aplicara las promesas de
Dios por fe y que extrajera consuelo de las Escrituras.
Me hablaron de la condición mencionada por el apóstol en el capítulo siete de Romanos,
y me dijeron que había sido así con él,
a pesar de que había sido un siervo de Jesucristo.
Por tanto,
ellos me ofrecieron esta y otras engañosas cubiertas (con las que ellos también se cubrían),
sin considerar que el apóstol había llamado a esto, un estado miserable y esclavo,
como bien yo habría podido llamar al mío. Pero estas cosas
no encontraron más que un pequeño lugar en mí,
pues mi herida permanecía sin sanar, y Aquel que me había herido y era capaz de curarme,
estaba cerca de mí, pero yo no Lo conocía.

Yo iba a tientas en esa oscura y sombría noche de tinieblas,
buscando a los vivos entre los muertos, como muchos otros hacían,
pero estaba tan oscuro que no podíamos vernos.
En cuanto a los sacerdotes y profesantes de esos tiempos,
la mayoría se jactaba de sus experiencias y celo, de su seguridad del amor de Dios,
y de cuánto consuelo disfrutaban por la meditación
en los sufrimientos de Cristo por sus pecados, etc.
"`¡Ay,`" pensé, "`yo puedo creer en estas cosas así como ellos,
pero mi herida permanece fresca, y veo que soy como uno de los crucificadores,
en tanto viva en el pecado por el que Él murió!`"

Mi alma anhelaba algún otro tipo de conocimiento de Él,
además del que podía ser conseguido mediante la lectura,
porque yo veía que tanto los peores como los mejores podían alcanzar tal conocimiento.
Por tanto, no me atrevía a apoyarme en los sacerdotes como había hecho antes,
y empecé a distanciarme un tanto más de ellos en mi mente
(aunque en ese momento no los dejé completamente).
Luego comencé a buscar las reuniones de los llamados Separatistas,
para oír sus llamados '`hombres dotados`',
cuya doctrina saboreaba más celo y fervor que la de la mayoría de los sacerdotes.
Estos no me parecían tan codiciosos por obtener ganancia por la predicación,
aunque entonces, no podía ver cómo codiciaban la grandeza y el aplauso de los hombres.
Yo con frecuencia me sentía afectado con sus predicaciones,
pero la anterior atadura aún estaba sobre mí (y ellos todavía la fortalecían), a saber,
el pensamiento de que si yo no había sido elegido, no podía ser salvado,
y nadie me podía decir a mi satisfacción, cómo podría saberlo.
El temor de esto muchas veces arruinaba mi alivio.

Luego comencé a darme cuenta del andar libertino de estos Separatistas, sí,
incluso de los maestros entre ellos.
Vi que ellos no habían sido redimidos aún de las bromas tontas, de las palabras ociosas,
de la ira y pasión que a veces estallaban entre hermanos, y que resultaban en rupturas,
cismas y deterioro de sus iglesias,
las que ellos a menudo construían y derribaban con sus propias manos.
También vi cuán inconsistentes eran, a veces dejaban entrar una doctrina, a veces otra,
y a veces eran arrastrados por varios vientos,
pero nunca oí una palabra de cómo podría obtener poder sobre el pecado.
Yo tenía poder sobre algunos pecados y lujurias, pero no sobre todo,
y nada más me satisfaría.

Cuando estaba cerca de los diecisiete o dieciocho años de edad,
comencé a buscar todavía más,
y al escuchar de un pueblo que exponía la muerte
de Cristo como algo disponible para todos los hombres,
fui a oírlos.
Después de un tiempo llegué a ver que entre ellos había más luz,
y un entendimiento más claro de las Escrituras.
Fue así como empecé a familiarizarme con ellos y a frecuentar sus reuniones,
y poco a poco fui establecido en la creencia de que había un amado Hijo de esperanza,
y un camino de salvación preparado para todas las personas,
y que nadie estaba excluido por decreto eterno (por nombre o persona),
sino únicamente por incredulidad y desobediencia.

Esto me ministró consuelo por un tiempo, y yo decidí creer,
tener fe en Cristo y considerarme creyente, pero hallé que era una obra difícil,
es decir, demasiado difícil para mí,
aunque muchas veces clamaba en voz alta buscando ser ayudado en mi incredulidad.
Cuando veía que el pecado prevalecía sobre mí decía: "`¡Ay,
dónde está esa fe que purifica el corazón y da victoria?
La mía no es así!`" Entonces el Testigo puro de Dios
se levantaba y testificaba contra mí por mi pecado,
y cuánto más se ampliaba mi entendimiento, más agudo era mi juicio.
En realidad,
se hizo tan penetrante que no sabía cómo soportarlo
tan bien como lo había hecho en mi infancia.
La naturaleza áspera y rebelde ya había crecido fuerte,
y yo al estar en la flor y fuerza de mi juventud,
y viendo cómo otros gastaban el tiempo en placeres y vanidades,
una lujuria secreta y un deseo oculto se encendieron en mí,
por participar en la copa de ellos.

Por un tiempo me deleité en el ingenio e inventos de los
hombre de épocas anteriores que encontré en libros.
Estaba dedicado a la lectura,
y reuní muchos dichos y frases de filósofos sabios y de eruditos,
y en parte obtuve el conocimiento de muchas edades que me precedieron.
Yo pensaba que estas cosas eran como un adorno que me hacían
apto para el discurso y la compañía de los hombres sabios.
Pero ¡ay!, todo esto creció mientras mi yo permanecía sin crucificar,
y todo lo que obtuve no fue sino sacrificado y ofrecido
para la obtención de una reputación propia,
la cual debía ser enyugada por la cruz.
No obstante, todo esto sirvió para alimentar por un tiempo, mi incansable,
escrutadora e inquisidora alma.
Me topé con muchas cosas que parecían darle vida a mi alma,
y comencé a elogiarme a mí mismo por no haber malgastado mi tiempo.

En ese entonces hallé en mí dos cosas que me atraían:
Sentía una fuerte atracción y tentación hacia el mundo,
para que me entregara totalmente a los placeres, deleites y vanidades de este.
Y sentía una fuerte atracción hacia la piedad, vigilancia y seriedad.
Y yo (¡pobre hombre!) no sabía qué hacer con respecto a la religión. En realidad
yo sentía una inclinación religiosa en mí como la que había tenido desde la niñez,
y habría estado muy contento de haber asumido alguna forma de profesión cristiana,
pero estaba muy desanimado,
pues no encontraba ninguna que ofreciera lo que yo necesitaba,
ya fuera en su vida o doctrina, esto es: Poder sobre la corrupción;
sin el cual yo sabía que toda religión sería en vano,
y no respondería al propósito por el que yo la tomaría.

Por tanto, desistí de asumir cualquier forma particular de adoración,
y continué en el agreste campo de este mundo, vagando arriba y abajo,
a veces con un tipo de profesantes y a veces con otro.
Yo hacía una inspección cuidadosa de las vidas y doctrinas de todo tipo,
aunque debo confesar, que había dejado mi propio jardín sin labrar,
al punto que lo cubrió mucha maleza fastidiosa.

Comencé a perder la ternura de consciencia que había tenido,
y comencé a sentir placer en la compañía de los impíos.
En muchas cosas llegué a ser como ellos,
cautivado más que nunca por la risa y diversión. A menudo
cantaba cuando tenía motivos para dar alaridos y llorar,
y caía en juegos y pasatiempos, y presumía de la misericordia de Dios.
Yo tenía la secreta creencia de que Dios un día manifestaría
Su poder y me sacaría de ese estado.
Por tanto, con frecuencia me aterrorizaba correr muy adentro en la maldad,
como algunos otros hacían, y fui guardado de muchos males graves,
con los que sí se tropezaron mis compañeros.
En esto fue manifestaba la infinita bondad del Señor, la cual,
cuando llegué a ver con mi ojo verdadero, me rompió el corazón. ¡Sí,
mi corazón y mi alma alaban al Señor por Su misericordia,
quien me guardó cuando no lo conocía! Y a pesar de que las
provocaciones y tentaciones que me acompañaban eran muchas,
fui preservado fuera de muchas abominaciones.
De hecho, debo decir y admitir (como el Señor le dijo a Abimelec),
que fue el Señor el que me guardó.

Este rumbo de vida se prolongó por un tiempo, cerca de dos o tres años,
hasta que me invadió un cansancio.
Muchas veces en medio de mi risa y ligereza, la mano del Señor se hacía pesada sobre mí,
Su justo juicio se encendía en mí y le ponía un alto a mi camino.
Entonces yo me lamentaba en secreto y a veces,
me quejaba con otros de mi doloroso cautiverio y esclavitud al pecado.
A menudo discutía y les preguntaba a los que eran considerados cristianos experimentados,
cómo podían ser alcanzadas la paz y la seguridad.
Algunos decían que mediante la lectura y aplicación de las promesas,
pero yo había intentado esta forma tan a menudo y por tanto tiempo,
que en ese momento no tuvo ningún efecto y vi que estaba en un estado diferente,
al estado al que se le habían hecho las promesas.
Otros decían que la única forma era siendo obediente
a los mandamientos y ordenanzas de Jesucristo,
y conformarse a los santos antiguos, caminando en el orden y comunión de la iglesia.
Aquí, decían ellos,
cada persona tenía la fuerza de muchos y toda la
iglesia estaba obligada a velar por cada miembro.

Escuché a estos consejeros y estuve dispuesto a hacer cualquier cosa,
con tal de encontrar el poder.
Así que tomé la ordenanza (como ellos lo llamaban) del bautismo en agua,
con la expectativa de haber encontrado más poder que antes.
Mi voluntad obró fuertemente para frenar y someter
la parte liviana y la naturaleza pecaminosa,
y por un tiempo me esforcé para mantenerme en un mejor estado que antes.
No obstante,
no sentía la virtud que podía santificarme y lavarme
en verdad (pues mi mente vagaba ampliamente),
y lo que me guardaba no era la operación del amor puro de Dios en mi corazón,
ni el predominio de Su gracia en mí,
sino la consideración de la reputación de mi religión y el temor
de que pareciera que había corrido y actuado en vano.

Estas cosas duraron por un tiempo,
antes de que la tentación creciera demasiado fuerte para mi voluntad,
y el diablo entrara en su propio terreno y prevaleciera sobre mí. De hecho,
él me llevó cautivo al pecado y al mal, y me arrastró de nuevo a vanas compañías,
deportes, placeres estériles y pasatiempos.
Entonces, claramente vi que aún carecía de lo que me había faltado antes,
y que sólo había asido una sombra y cogido nada más que viento.
Vi que mi bautismo fue incluso inferior al de Juan,
quien efectivamente bautizó con el bautismo de arrepentimiento
que preparó el camino del Señor y enderezó Su senda.
Pero el mío falló en hacer incluso eso, por tanto,
quedó aún más cortó que el bautismo de Cristo,
quien bautiza con el fuego que quema todo lo que
es ofensivo a Dios y aflige a Su Santo Espíritu,
y llena de un Espíritu que no se deleita en nada que sea corrupto.

Vi que este bautismo era deficiente, y por lo tanto,
una insatisfacción comenzó a crecer más en mí, tanto de mí mismo como de mi camino.
Entonces, les testificaba a los (así llamados) ancianos de la iglesia,
que Dios revocaría en breve toda nuestras adoraciones y
religiones (que descansaban en cosas externas y carnales),
y daría a conocer un camino por encima de todas ellas, el cual permanecería para siempre.
Cuando ellos me preguntaban cual sería ese camino yo confesaba que no lo sabía,
pero que esperaba ver cuál sería.

En aquellos días muchos se ocupaban de hablar y conversar
acerca de un pueblo llamado Cuáqueros.
Yo escuchaba sus conversaciones con gran atención, pero no oía nada bueno de ellos,
solo cosas perjudiciales y muchas mentiras perversas.
Pero noté lo siguiente:
Que ellos padecían pacientemente bajo muchas burlas crueles y sufrimientos dolorosos.
Yo auguraba que cuando el camino de Dios fuera manifestado,
seguramente sería odiado y perseguido,
y pensaba que una vez que yo supiera que era verdad,
nada me disuadiría ni me asustaría de reconocerlo,
ni de caminar en él. Pero al oír que ellos sostenían
la posibilidad de la perfección en esta vida,
supe que esto era algo con lo que la sabiduría de la serpiente antigua en mí no se uniría.
Yo razonaba fuertemente contra esta doctrina en esa sabiduría oscura y caída,
en la que muchos todavía luchan por el pecado hoy.
Ahora sé que estos no son mejores que las huestes de Magog,
que luchan contra el Cordero y Su inocente vida diciendo en sus corazones:
"`Gobierna en el cielo si Tú quieres, pero en la tierra no tendrás lugar.
No, ni un alma sobre la cual llevar dominio ni soberanía.`" (Compadezco a
los miles que están peleando las batallas del diablo en este asunto,
pero habiendo trabajado fielmente con ellos en mi generación,
ahora dejo a los que son testarudos y obstinados opositores.)

En esta misma sabiduría caída razoné contra la verdad en
diversas formas (demasiadas para especificarlas ahora),
es decir, mientras estaba en la muerte y en el camino de destrucción. Sin embargo,
todavía no había visto un mensajero de esta verdad, y anhelaba mucho ver a uno.
Deseaba noche y día que nuestros territorios fueran visitados por ellos,
como había oído que otros habían sido visitados.
Por fin, hacia el mes cuarto de 1655, el Señor envió a nuestro pueblo llamado Colchester,
a Su siervo fiel y mensajero de Su evangelio eterno, James Parnell.
En el vigésimo séptimo año de mi edad,
este joven vino en el nombre y poder del Dios Altísimo,
en el que volvió a muchos a la justicia, tanto aquí como en otros condados antes,
algunos de los cuales permanecen y muchos otros han muerto.

Cuando vi a este hombre pensé en hacerle frente, porque no era más que un jovencito,
y yo no conocía el poder o Espíritu que estaba en él. Comencé
a hacer preguntas y a buscar una discusión con él,
pero rápidamente sentí que el Espíritu de buen juicio estaba en él,
pues el Testigo de Dios se levantó en mi interior y testificó Su juicio,
e indicó que yo debía reconocerlo como justo y verdadero.
En el mismo día y hora testifiqué,
que todas nuestras varas de profesión cristiana serían devoradas por la
vara de él (aludiendo a la vara de Moisés y a los magos de Egipto),
lo cual ya sucede, y ciertamente se cumplirá. Más tarde, ese mismo día,
fui a una reunión y lo oí declarar el evangelio eterno
en el nombre y autoridad del Señor,
el cual no pude resistir con toda mi sabiduría y conocimiento; más bien,
era constreñido a reconocer y a confesar la verdad.

[.asterism]
'''

[.inline]
=== Nota del Editor

+++[+++Se dice de James Parnell que "`era joven,
pequeño de estatura y de pobre apariencia,`" pero miles fueron
obligados a confesar que
"`hablaba como quien tiene autoridad, y no como los escribas.`"
Él fue convencido de la verdad cuando sólo tenía catorce años,
y se convirtió en un poderoso predicador y promotor del evangelio
a los dieciséis. Tras un debate con un sacerdote prominente,
Parnell fue arrestado bajo los falsos cargos de ser "`una persona
ociosa y desordenada,`" y encarcelado en el Castillo de Colchester.
Ahí fue confinado a un pequeño hueco en la gruesa pared del castillo,
a doce pies de altura del suelo.
Murió por enfermedad y malos tratos, después de diez meses de encarcelamiento,
a la temprana edad de diecinueve años. La siguiente
carta de James Parnell fue dirigida a Stephen Crisp,
probablemente poco tiempo después del primer encuentro
entre ellos y el convencimiento de Crisp.

[.embedded-content-document.letter]
--

[.salutation]
Amigo,

Permanece y mantén tu mente hacia lo que te deja
ver que tus enemigos están en tu propia casa.
Tu imaginación es un enemigo, tu sabiduría es un enemigo;
eso que ha sido precioso para ti, ahora es tu mayor enemigo.
Por esa razón, debes sacrificar lo que has llamado precioso y entregarlo a la muerte,
para que el Justo pueda levantarse para vida,
y la Semilla justa germinar para reinar en ti y ser tu Cabeza.
De esta manera la cabeza de la serpiente será herida.
En tu medida,
llegarás a entender esto mientras mores humilde en la Luz que manifiesta tu condición,
"`porque la luz es lo que manifiesta todo.`"
(Efesios 5:13)

Deja que se mantenga abierto el ojo que el dios de
este mundo ciega en los hijos del mundo.
Porque por medio de este ojo los hijos de la luz pueden ver a su enemigo, y conocer,
resistir y negar al tentador.
Establece una constante vigilancia con ese ojo,
y no permitas que el ojo necio salga a deambular,
el cual arrastra a la mente errante en pos de objetos visibles.
Más bien, permanece firme en la guerra, sin darle lugar al enemigo o a sus ilusiones,
y conténtate con ser un necio, para que todos los pensamientos egoístas sean juzgados.
Entonces recibirás sabiduría de Aquel que la da generosamente y sin reproche,
para discernir y conocer las estratagemas del enemigo.
Pero tienes que saber, que es en la muerte a tu propia voluntad y a tu mente apresurada,
que el don de Dios es recibido.
Por eso es dicho: "`el que creyere, no se apresure.`"
(Isaías 28:16)

Por tanto, no te canses del yugo de la cruz, porque en la fe '`el yugo es fácil`',
la naturaleza impaciente es crucificada y la paciencia tiene su obra perfecta.
Así que permanece en la medida de Luz que ejercita tu mente hacia Dios.
No aspires nada,
sino deja que tus pensamientos sean juzgados y que el poder de Dios obre,
para que Él sea visto como el todo.
Sólo por este principio debes ser conducido y actuar,
manteniendo en la cruz la parte carnal y negando el yo,
tanto en lo particular como en lo general.
No consideres quien sea disgustado, en tanto Dios sea complacido,
porque así no le das ninguna oportunidad de ofensa a nadie.
Y aunque hay enemistad en el mundo,
en tanto esto te lleve a caminar en fidelidad para con Dios,
también te lleva a caminar con una consciencia libre de ofensa para con los hombres.
Por tanto,
mantén tu mente en la Luz y no te apresures a saber algo más allá de tu medida,
porque así fue como Eva perdió su paraíso. Más bien,
permanece humilde en la voluntad de Dios y espera en Su enseñanza,
para que Él sea tu Cabeza,
y encontrarás el camino de paz y habitarás en unidad con los fieles.
Y aunque seas odiado por el mundo, con todo, en Dios tendrás paz y bienestar.

[.signed-section-signature]
James Parnell

--

Después de la muerte de James Parnell,
Stephen Crisp fue llamado a escribir un corto testimonio
del carácter y ministerio de Parnell,
lo cual hizo en un espíritu que mostraba un precioso
recuerdo de Parnell como instrumento de Dios,
mediante el cual, su largo deambular y cansada alma fue vuelta a la Verdad.
Hablando tiempo después de la gran obra del Señor en aquellos días,
Crisp continúa diciendo:

[.embedded-content-document.letter]
--

Los bebés han sido Sus mensajeros y los niños Sus ministros,
quienes en su inocencia han recibido la revelación de Su Espíritu Santo,
por quien las cosas profundas de Su ley y de Su glorioso evangelio de vida y salvación,
han sido revelados.
Entre estos bebés,
que llegaron a recibir el conocimiento de los misterios
de Reino de Dios mediante la operación de Su divino poder,
estaba este noble niño, James Parnell.
Él era una vasija de honor, ciertamente,
y estaba fortalecido en el poder y Espíritu de Emanuel,
derribando y desolando muchas fortalezas y torres de defensa,
en las que el antiguo engañador se había fortificado con sus hijos.
Se podría decir mucho de este hombre,
y en mi corazón vive un gran testimonio de su bendita vida,
y del poder y sabiduría que abundaban en él.]

--

[.alt.centered]
==== De Regreso al Diario de Stephen Crisp

[.asterism]
'''

Al ver que mi sabiduría y mi razón eran superadas por la verdad,
no pude contender más contra ella.
Entonces, aquí, al principio mismo de mi convencimiento,
el enemigo de mi alma intentó matarme,
tentándome a mantener la verdad en la misma parte en la que yo
la había resistido anteriormente (en la mente natural),
y a defenderla con la misma sabiduría con la que yo la había resistido.
De esta manera, permanecí ajeno a la cruz que me tenía que crucificar,
pero me sentí en libertad en el espíritu hablador y argumentador,
empleando mi ingenio y mis habilidades a favor de la verdad.
Sin embargo, a pesar de que ofrecí lo mejor que mi tierra podía presentar,
pronto sentí que mi sacrificio no era aceptado y que algo más era pedido.
Había un clamor en mí que me llamaba a juicio,
y la tierra que por mucho tiempo había cubierto lo muerto empezó a ser movida,
aunque no sacada aún de su lugar.
Grandes fueron las luchas de mis pensamientos,
y un gran deseo de comprender la verdad en mi propio entendimiento fue encendido en mí,
como había sucedido con las doctrinas y principios de otras profesiones.
Sin embargo, todo mi esfuerzo fue para nada,
porque el Señor había determinado la muerte sobre
mi sabiduría. Por fin vi que mi trabajo era en vano;
en realidad, mientras trabajé en la oscuridad, no pude pescar nada en toda la noche,
ni tenía la guía de la luz.

Continué en este estado por uno o dos meses,
pero luego una rápida espada fue esgrimida contra esa mente sabia y entendida,
y una mano poderosa dio la estocada.
Y fui talado como un alto cedro que cae de inmediato al suelo.

Entonces, ¡oh, el ay, la miseria y la calamidad que se abrieron sobre mí! Sí,
incluso las puertas del infierno y de la destrucción estaban abiertas,
y me vi a punto de caer en su interior.
Mi esperanza, mi fe y todo lo demás huyeron de mí,
y no quedó ningún soporte sobre el cual yo pudiera descansar.
La lengua que era como un río, ahora era un desierto seco; el ojo que deseaba verlo todo,
ahora estaba tan ciego que no podía ver nada con certeza,
a excepción de mi presente estado desecho y miserable.
Luego, clamé en la amargura de mi alma:
"`¿En qué me ha beneficiado toda mi profesión cristiana?
¡Soy un pobre, ciego y desnudo,
que pensaba que había sido rico y que estaba bien adornado!`" ¡Oh,
entonces vi a la ramera despojada y traída a la memoria delante de Dios!
Vi que su juicio había llegado,
y yo no sabía cómo escapar del fuego de venganza que estalló luego.
¡Oh, cuán miserables eran mis noches y cuán tristes eran mis días!
Mis deleites se marchitaron, incluso en esposa, hijos y en todas las demás cosas,
y la gloria de todo el mundo pasó como un rollo que es quemado con fuego.
De hecho, vi que no quedaba nada en todo el mundo que me sirviera de consuelo.
Mi sol perdió su luz, mi luna se oscureció y las estrellas de mi senda cayeron.
No veía cómo dirigir mi camino,
y llegué a ser como alguien que es abandonado en
un absoluto desierto en medio de la noche más oscura.

Cuando vi lo que Dios había hecho (porque yo creía que esto era obra Suya),
estuve pronto a clamar: "`¡Estoy abandonado para siempre,
porque nunca ha habido una tristeza como la mía! Mi herida
es incurable y mi enfermedad nadie la puede sanar!`"
Por desgracia, ni mi lengua ni mi pluma pueden expresar las tristezas de aquellos días,
en los que me sentaba en silencio, temor y estupor, y me rodeaban dolor y tinieblas.
No conocía a nadie a quien pudiera presentar mi queja.
Yo oía del gozo y de la salvación,
pero apenas podía pensar que alguna vez sería partícipe de estos pues
yo todavía carecía de esa fe viva que el apóstol describió como "`el poder
de Dios que levantó a Jesús,`" quien es la verdadera Semilla,
la que yo todavía sentía gimiendo en mí,
buscando ser liberada de la carga del pecado y de la opresión de la mente carnal.

Después de largos dolores (como de parto) y fuertes clamores,
y muchas lágrimas y gemidos amargos, encontré una pequeña esperanza brotando en mí,
de que el Señor (en Su propio tiempo) haría germinar Su Semilla, es decir,
Su Semilla elegida, la Semilla de Su pacto,
para que gobernara en mí. Esto me fue dado en un momento en que la consciencia
de mi propia indignidad me había abrumado tanto con pena y angustia,
que pensaba que yo no era digno de ningún consuelo.
Entonces brotó en mí la esperanza de la resurrección
del Justo y fui enseñado a esperar en Dios,
y a comer y a beber en temor y vigilancia,
mostrando la muerte del Señor hasta que Él viniera a vivir y a reinar en mí.
Después esperé con la esperanza de que Dios sería misericordioso conmigo.
Había algo en mí que estaba ansioso de saber el momento, cuánto tiempo tenía que esperar,
pero también encontré un constante lloro en mí que llamaba mi impaciencia a muerte.

En una ocasión, estando cansado de mis pensamientos en la reunión del pueblo del Señor,
llegué a la conclusión de que nadie era como yo,
y que era en vano sentarme ahí con una mente tan errante
como la mía. Porque aunque me esforzaba por aquietarla,
descubrí que no podía hacerlo como quería. Al fin, decidí levantarme e irme,
y mientras me iba, el Señor tronó a través de mí diciendo:
"`¡Eso que está cansado debe morir!`"
Así que regresé a mi asiento y creyendo en Dios,
esperé la muerte de esa parte que estaba cansada de la obra de Dios.
Me volví más diligente en busca de esa muerte,
para saber cómo despojarme del viejo hombre con sus obras, palabras e imaginaciones,
sus modas y costumbres, su amistad y sabiduría,
y todo lo que le pertenecía. Entonces la cruz de Cristo fue puesta sobre mí y la llevé.

Cuando estuve dispuesto a tomar la cruz,
descubrí que ella era lo que había buscado desde mi infancia, a saber, el poder de Dios.
Pues por medio de la cruz yo era crucificado al mundo y este a mí,
algo que ninguna otra cosa podía hacer.
¡Oh,
qué contenta estaba mi alma cuando descubrí la manera de matar los enemigos de ella! ¡Oh,
el gozo secreto que estaba entonces en mí! Pues en medio de todos mis conflictos y combates,
tenía la confianza de que si tomaba la cruz obtendría la victoria,
porque ella es el poder de Dios para salvación a través de la fe.
Y que así como la había hallado ser en algunas cosas,
a su debido tiempo la encontraría ser así en todas.
Por tanto, el oprobio del evangelio se volvió júbilo para mí,
aunque en aquellos días era muy cruel y penoso para la carne y sangre.
Sin embargo, desprecié la vergüenza por el gozo que había sido puesto delante de mí,
pues tenía la esperanza de que a su tiempo y si permanecía fiel,
participaría del gozo de Cristo.
Esta era mi mayor preocupación noche y día,
mantenerme muy bajo y fuera de las obras de mi propia voluntad,
para poder discernir la mente de Dios y hacerla,
aunque fuera una cruz muy grande para mí.

Con todo, el enemigo de mi alma me seguía de cerca y muy secretamente.
Y al darse cuenta de cuán dispuesto estaba yo a obedecer al Señor,
luchó para colocarse en el asiento de Dios y moverse como un ángel de luz,
con el fin de traicionarme y conducirme a algo que se pareciera al servicio de Dios.
Sí, me topé con muchos conflictos dolorosos antes de poder distinguir en todas las cosas,
entre las operaciones del verdadero Espíritu y poder,
y eso que no era más que el espíritu de tinieblas transformado.
Sin embargo, en eso yo ya había probado, sin ninguna duda, el amor y la bondad de Dios,
y confiaba en Él,
y le confié a Él el bienestar de mi alma en sencillez
de corazón. Muchas y diarias fueron Sus liberaciones,
las cuales Él me dio a conocer más allá de todo relato o recuerdo humano.
¡Oh, alma mía, alaba al Señor para siempre,
porque Él cuidó de ti en tu infancia y te guardó en los días de tu angustia!

Cuánto más sentía y percibía el amor de Dios y Su bondad fluir sobre mí,
más humillado estaba,
y más inclinado en mi mente a servirle a Él y a los
más pequeños de Su pueblo entre quienes yo caminaba.
Cuando la Palabra de sabiduría empezó a brotar en mí y el conocimiento de Dios creció,
me convertí en un consejero para aquellos que eran
tentados de la misma manera en que yo lo había sido.
Sin embargo, yo era mantenido tan bajo,
que esperaba recibir a diario consejo de Dios y de los que estaban sobre mí en el Señor,
quienes estaban en Cristo antes que yo y contra quienes nunca me rebelé,
ni fui obstinado.
Descubrí que cuánto más me mantenía en sujeción,
más sujetados estaban los espíritus malos a mí,
y más capaz era de ayudar a los débiles y endebles.
Por tanto, los ojos de muchos se posaron sobre mí,
como alguien en quien había una medida de consuelo y entendimiento.

En aquellos días la iglesia de Dios estaba creciendo
y mi cuidado por ella también aumentaba día con día,
y se posó sobre mí el peso de las cosas relacionadas con
la condición interna y externa de los Amigos pobres.
Habiendo sido llamado por el Señor y Su pueblo a cuidar
al pobre y aliviar sus necesidades cuando viera la ocasión,
lo hice por muchos años fielmente, con diligencia y mucha ternura.
Yo exhortaba y reprendía al que era perezoso y animaba a los que eran diligentes,
haciendo la distinción según la sabiduría que Dios me había dado.

También continuaba prestando atención a mi propio estado y condición,
buscando el honor que viene sólo de Dios.
Había un clamor en mí que me llamaba a mantener puesta mi armadura espiritual,
porque aún no habían sido puestos bajo mis pies todos mis enemigos.
Por tanto, yo mantenía vigilancia,
porque no sabía dónde podría aparecer de nuevo mi enemigo, y después de un tiempo,
encontré una vez más que su aparición puede ser muy aguda, como en la ocasión que sigue.

Cerca del año 1659, a menudo sentía la abundancia del amor de Dios en mi corazón,
y había un clamor en mí de entregarme enteramente a Su voluntad,
sin saber o prever lo que el Señor estaba intentando hacer conmigo.
Pero Su ojo veía más lejos que el mío. Su amor,
ternura y compasión obraban tan poderosamente en mí,
que se extendían a todos los hombres sobre la faz de la tierra,
por lo que era llevado a clamar en espíritu: "`¡Oh, que todos los hombres Te conozcan,
y conozcan Tu bondad!`"
Una vez, mientras esperaba en el Señor,
Su Palabra se levantó en mí y me mandó a dejar y
a separarme de mi querida esposa e hijos,
padre y madre, e ir a Escocia a dar testimonio de Su nombre,
a esa nación orgullosa y profesante.
Cuando sucedió esto,
me di cuenta de que no todos mis enemigos habían sido asesinados aún,
porque los esfuerzos, luchas,
razonamientos y disputas contra el mandato de Dios con los que me encontré entonces,
no se pueden expresar.
¡Oh, cuánto hubiera argumentado mi falta de capacidad, el cuidado de mi familia,
mi servicio en nuestra reunión particular y muchas más cosas,
todo con tal de lograr ser liberado de hacer esta
única cosa que el Señor había puesto sobre mí,
la que yo no había pensado, ni buscado!

Después de muchos razonamientos, y de muchos días y semanas por mi propia cuenta,
pensé que sería mejor hablar de mi preocupación a algunos
de los ancianos y ministros fieles del evangelio eterno,
esperando secretamente que ellos me desanimaran de hacer esto.
Pero, muy por el contrario, ellos me animaron fuertemente y me instaron a ser fiel.
Por tanto, al final me rendí al Señor y le di a conocer a mi esposa el asunto,
lo que hizo que comenzara una nueva prueba,
ya que el enemigo obró fuertemente en ella para detenerme.
Pero mantuve mucha paciencia y tranquilidad,
y fui y visité reuniones de Amigos en Essex y parte de Suffolk,
principalmente para verlos y despedirme de ellos.
En algunas reuniones el Señor me abría la boca con
pocas palabras para el refrescamiento de los Amigos,
pero yo prefería escoger el silencio cada vez que podía.

El invierno se acercaba y algo en mí quería posponer mi viaje hasta el siguiente verano.
Pero el Señor me mostró que no debía ser en mi tiempo, sino en Su tiempo.
Entonces yo quería ir por mar, pero el Señor me resistió y mostró que no era a mi manera,
sino a Su manera; y que si yo era obediente, Él estaría conmigo y prosperaría mi viaje,
de lo contrario, Su mano estaría contra mí. Por tanto,
lo rendí todo y finalmente obedecí con alegría. Cerca del final
del séptimo mes salí y visité las iglesias de Cristo por el camino.

A medida que avanzaba en Lincolnshire y Yorkshire,
rápidamente percibí que el Señor estaba conmigo, más que en otras ocasiones,
y mi viaje se volvió gozoso.
Y aunque era débil, pobre y humilde,
el Señor me dio aceptación entre los ancianos de Su pueblo
y mi testimonio era reconocido en todo lugar,
y muchas personas fueron convencidas de la verdad eterna.
Entonces me maravillaba y decía: "`¡Señor, sólo a Ti te pertenece la gloria,
pues Tú has obrado maravillas por amor de Tu nombre y por amor a Tu Semilla santa!`"

Llegué a Escocia en el noveno mes de ese año,
y ese invierno viaje a pie de un lado para otro con mucha
alegría. Muchas estrecheces y dificultades me acompañaron,
las cuales me abstengo de mencionar,
pues era el tiempo del movimiento de los ejércitos de Inglaterra y Escocia,
con el que vino la revolución del gobierno y el regreso del rey Carlos II a Inglaterra.
Cerca del mes undécimo o duodécimo regresé a Inglaterra
y viajé al oeste a Westmoreland (parte de Lancashire),
y luego al sur,
y unos cinco o seis meses después fui llevado a casa
con mi esposa e hijos por la buena mano de Dios.
En todo mi viaje estuve dulcemente acompañado por la presencia del Señor,
y Su poder llenó con frecuencia mi vasija terrenal e hizo rebozar mi copa.
¡Alabado sea por siempre Su nombre!

En todo mi viaje, no me hizo falta ninguna cosa buena,
pues así como mi cuidado al servir al Señor era en sencillez,
así era Su tierno cuidado sobre mí, supliéndome de todo lo que era necesario en mi viaje.
Sin embargo, desde el principio una secreta esperanza vivía en mí,
de que cuando se cumpliera mi viaje,
yo sería liberado de este tipo de servicio y tendría
libertad de regresar a mi trabajo y a mi familia.
No obstante, resultó ser todo lo contrario,
porque cuando había estado en casa por unos pocos días,
me fue puesto ir a Londres a visitar a los hermanos y a la iglesia
de Dios ahí. Fui con mucho miedo y temor de Dios a esa ciudad,
y tras estar unos días ahí,
partí de nuevo hacia el norte por mandato del Señor. De hecho,
adondequiera que iba encontraba que mi camino era prosperado,
y diariamente recibía mucho ánimo del Señor, quien bendecía mi trabajo de amor.
Además de la paz y del gozo que sentía en mí mismo,
veía manifestado el resultado de mi trabajo y del laborioso esfuerzo de mi alma,
porque muchos fueron vueltos de las tinieblas a la luz,
y del poder del diablo al poder de Dios.
Aún así me acompañaban pruebas,
y una prisión vino a ser mi porción casi a doscientas millas de mi casa.
Se respiraban grandes y graves amenazas contra mí,
y encontré que el mismo espíritu que obraba en los perseguidores,
tanto en la crueldad como en la sutileza de ellos,
también se esforzaba por trabajar en mí.

Pero clamé al Señor y Él me ayudó,
y mi fe no me falló. Cumplí mi servicio y mi testimonio,
y al final fui liberado de mi prisión (junto con varios miles más),
por una proclamación pública del rey.
Entonces regresé a mi propia casa después de casi ocho meses de ausencia.
Mi corazón estaba fijo en servirle al Señor que había sido tan bueno conmigo,
sin embargo,
la esperanza de ser liberado de este tipo de servicio continuó en mí por mucho tiempo,
pues hallé que esta obra era cada día más grande que antes.
Muchos falsos espíritus se levantaron y se transformaron a semejanza de la verdad,
aunque eran enemigos de la vida de la verdad, que son los peores enemigos de todos.
Vi que el enemigo de Sión, al ser incapaz de prevalecer de otra manera,
ahora estaba intentando una falsa pretensión de santidad y obediencia,
en busca de engañar y tentar al sencillo.
Pero le pedí a Dios que me diera un corazón entendido y de discernimiento,
para comprender la trampa del enemigo y que yo pudiera ser de ayuda al débil;
y Él lo hizo.

Cuando vi que el fundamento era atacado por el enemigo,
me volví celoso por el Señor y su casa,
y testificaba libremente contra los engaños ocultos del enemigo.
Pero esto se convirtió en motivo de aún más prueba y dolor,
pues muchos que no podían ver la profundidad de las operaciones de Satanás,
juzgaban innecesario mi celo y fervor contra ese espíritu contradictorio.
Pero en mansedumbre y paciencia,
el Señor me mantuvo fuera de la mente combativa y esforzada,
porque yo no me atrevía a atacar a los que yo sabía que eran mis compañeros siervos,
sino únicamente a los que pretendían serlo y de esa manera servían y promovían
otro interés. A estos los herí a menudo con el arma que Dios me había dado,
y los que llegaron a amar el juicio, fueron sanados,
pero muchos perecieron en su rebelión y obstinación. De hecho,
el Señor se levantó y derribó la obra del enemigo,
abrió los ojos de muchos que estaban en tinieblas,
y ellos llegaron a ver el fin de lo que había sido el perturbador de Israel.
Entonces la paz,
la unidad y el verdadero amor fueron restaurados en todas nuestras fronteras,
mi gozo fue pleno y mi copa rebosó con alabanzas y agradecimiento a Dios,
quien había puesto Sus ojos sobre Su herencia y Su pueblo,
y los había liberado de las estratagemas del maligno.

Mi alma crecía cada día más en amor a Sión,
y no había nada en todo el mundo tan deseable para mí,
como la prosperidad del evangelio y el esparcimiento y publicación
del nombre y la verdad del Señor en toda la tierra.
Este amor me constreñía a viajar con gran diligencia de un país a otro,
para dar a conocer lo que Dios había hecho a mi alma, y publicar el Día del Señor. Sí,
el Día de redención (en el que el cautiverio del Israel espiritual es devuelto al Señor)
resultó ser de buenas noticias para muchos que recibieron el informe y lo creyeron.
Estos llegaron a contemplar la revelación del santo y poderoso brazo de Dios,
para satisfacción de sus almas.
En la mayor parte de los lugares de Inglaterra adonde viajé,
encontré al Señor añadiendo diariamente a la iglesia los que estaban siendo salvos.
Mi gozo verdaderamente se incrementaba en esto,
y comencé a estar más libremente rendido a la obra y servicio de Dios,
y al ministerio del evangelio.

Cerca de 1663 fui movido a cruzar el mar y visitar
la semilla de Dios en los Países Bajos,^
footnote:[Los Países Bajos consistían en lo que hoy es Holanda, Bélgica, Luxemburgo,
parte de Francia y Alemania.]
lo que hice con alegría. Aunque estaba en una tierra desconocida y con una lengua desconocida,
yo declaraba la verdad para el refrescamiento de
muchos y para traer de vuelta a algunos del error;
algunas veces a través de un traductor, otras veces en mi propia lengua.
Tras cumplir con esa visita, regresé en paz a Inglaterra.

Después de un tiempo, fui requerido de nuevo por Dios para ir al norte del país,
y trabajé en la palabra y doctrina con gran diligencia
y fervor a lo largo de la costa marítima,
y así hasta Newcastle y un poco más allá. Siendo conducido por el Espíritu,
regresé por un camino diferente, más al este, a través de la tierra,
y hallé a lo largo de todo mi viaje que la planta
del renombre de Dios estaba floreciendo y creciendo.
Las reuniones eran grandes y los corazones de los
Amigos estaba ensanchados en amor hacia mí,
como el mío hacia ellos.

Al regresar, se apoderó de mí un gran peso con respecto a la gran ciudad de Londres,
más fuerte que nunca.
Subí lleno de fuerza y poder, y cuando el Señor abría mi boca y me daba la orden,
yo los advertía día tras día de las abominaciones
y maldad que corrían entre ellos como un arroyo,
y les declaraba que los juicios de Dios se habían
acercado y estaban sobre ellos por su gran maldad,
los cuales se cumplieron rápidamente después, tanto por guerra como por fuego,
y muchas calamidades más.^
footnote:[Más notablemente:
Una guerra que comenzó en 1665 entre los ingleses y los holandeses,
y que terminó con una victoria holandesa.
La Plaga de Londres en 1665-1666 (en la que murieron entre 100.000 y 200.000 personas).
El Gran Incendio de Londres en 1666 que destruyó 13.200 casas y 87 iglesias parroquiales.]
Después de esto, alrededor de 1667, se me requirió de nuevo ir a Holanda,
junto con mi estimado compañero Josiah Coale.
Viajamos de un lado a otro, visitamos las iglesias por cerca de tres meses y regresamos.

De nuevo fui al norte de Inglaterra,
pues mi corazón se sentía muy atraído hacia la noble semilla de Dios en aquellos lugares.
El amor y la ternura de corazón que yo sentía hacia ellos, hizo que todos los esfuerzos,
trabajos y peligros fueran fáciles,
porque aún veía las tiernas plantas del Padre celestial
en una condición próspera y creciente.
Yo sentía la virtud de vida brotando en mí día a día,
la cual me fue daba para regar la herencia y jardín de Dios.
Tan pronto como me sentí libre, regresé,
sintiendo cada vez más sobre mí el cuidado de la iglesia de Dios.
Esto me obligaba a la diligencia y a ser tan rápido como pudiera,
para poder ser lo más útil que me fuera posible en mi generación,
y mantenerme libre de la sangre de todos los hombres,
y hallé que no era una obra fácil ni leve.

Después de que regresé seguro,
descubrí que la presencia y poder del Señor me seguían guiando de un país a otro.
Yo ya era obediente, no porque fuera obligado como antes, sino por una mente dispuesta,
estimando Su servicio como libertad y sintiéndome libre de los cuidados de esta vida,
pues había aprendido a echar todo mis cuidados sobre Él.
Después de uno o dos años de más viajes en Inglaterra,
el Señor puso sobre mí aún más peso y cuidado de
los asuntos de Su pueblo en los Países Bajos,
y hallé una inclinación hacia ellos.
Por lo tanto, en el año 1669 fui y visité las reuniones,
establecí varias nuevas reuniones,
y me deleité al ver el buen orden y gobierno de los
asuntos relacionados con la Verdad y los Amigos.

[.asterism]
'''

__Stephen Crisp continuó un ministerio fiel y diligente
en la Sociedad de Amigos hasta su muerte en 1692,
a los 64 años. Durante sus 35 años de ministerio,
él fue conocido por todos como un obrero incansable, un padre alentador en la iglesia,
un escritor prolífero y un gran sufriente por causa de la verdad.
Su diario omite o pasa por alto algunas de sus pruebas más dolorosas,
como si él deseara no llamar la atención sobre sí mismo.
Pero él soportó frecuentes abusos de los enemigos del evangelio,
sufrió varias veces encarcelamientos crueles,
perdió dos esposas en el curso de su peregrinaje,
y a todos sus hijos en la plaga de 1665.
A pesar de todo esto,
Stephen Crisp se apoyó en el poderoso brazo del Señor
y encontró que Su gracia era suficiente en todo.
En su lecho de muerte se le oyó decir:
"`Quiero que el Señor me libere de este cuerpo fastidioso y doloroso.
Con sólo que Él diga la palabra, será hecho.
No veo una nube en mi camino.
Tengo la plena seguridad de mi paz con Dios en Cristo Jesús.`"__
